### ISSUE TITLE
cursor position recover

### ISSUE THREAD

**Issue by misakisuna705** [mg979/vim-visual-multi#101]
1.
How can my cursor jump back to initial position when I leave cursor-mode like in plug "vim-multiple-cursors" ?

2.
I know I can remap <ESC> in cursor-mode like this:

fun! VM_Start()
    nmap <buffer> <C-C> <Esc>
endfun

fun! VM_Exit()
    nunmap <buffer> <C-C>
endfun

but if I use

fun! VM_Start()
    nmap <buffer> kj <Esc>
endfun

fun! VM_Exit()
    nunmap <buffer> kj
endfun

It seems that I cannot remap <ESJ> as kj.

**Comment by mg979** [comment]
1. `:help g:VM_reselect_first`
2. no idea

**Comment by misakisuna705** [comment]
Thank you so much for g:VM_reselect_first !
