### ISSUE TITLE
Tab width is ignored when setting column for all cursors

### ISSUE THREAD

**Issue by balta2ar** [mg979/vim-visual-multi#102]
**Describe the issue:**
It looks like actual tab width (tabstop) is ignored when pressing `|`.

**Steps to reproduce**  
```python
	def _replace_tag(self, text, initial_tag, target_tag):
		soup = BeautifulSoup(text)
		while soup.find(initial_tag):
			soup.find(initial_tag).name = target_tag
		return soup.prettify()
```
Place cursor on the first `soup`, press ctrl-d 4 times, press `|`.

Expected: cursors should be vertically aligned with the last `p` letter of the last `soup` word.
Actual: 
![visual-multi-set-cursor-columns](https://user-images.githubusercontent.com/340676/75286432-d426e680-5818-11ea-9000-824f184d0280.png)

This is especially a problem when working with Go code.

vimrc settings
```vim
set tabstop=4
set shiftwidth=4
set softtabstop=4
```

-----
- **Operating System**: Manjaro
- **Vim Version**: NVIM v0.4.3
- **commit SHA/branch**: 7417eaf

**Comment by mg979** [comment]
Thanks for reporting, it should be fixed, can you confirm please? Thanks

**Comment by balta2ar** [comment]
Now it works as expected, thank you so much!
