### ISSUE TITLE
Extra newline after applying completion

### ISSUE THREAD

**Issue by Shatur95** [mg979/vim-visual-multi#103]
**Describe the issue:**
When I applying auto-completion with `<CR>` it also inserts a newline.
[![asciicast](https://asciinema.org/a/nAB7Heh3Nc2eTvXGQQGAQRrsm.svg)](https://asciinema.org/a/nAB7Heh3Nc2eTvXGQQGAQRrsm)

**Steps to reproduce**

1. Select several words with this plugin
2. Start typing to have auto-completion
3. Press `<CR>`

**Expected behavior**
Auto-completion applied.

**Actual behavior**
Auto-completion applied with a newline.

**Setup**
The issue exists with this plugin and [asyncomplete](https://github.com/prabirshrestha/asyncomplete.vim). I tested it with only this two plugins installed and without any configuration.

- **Operating System**: Arch Linix
- **Vim Version**: Neovim 0.4.3
- **commit SHA/branch**: 32fa278c458d8790a2604a71f3ac3d2500112040

**Comment by mg979** [comment]
Normal behaviour for insert mode `<CR>` is to close popup (accepting completion) and insert `\n`, maybe you've configured `<CR>` to behave like `<C-Y>` in insert mode if popup is visible?. VM simply respect vim default in this, correct me if I'm wrong. Try using `<C-Y>` and see if it does what you expect from `CR>`.

**Comment by Shatur95** [comment]
> Normal vim behaviour for insert mode <CR> is to close popup (accepting completion) and insert \n, maybe you've configured <CR> to behave like <C-Y> in insert mode if popup is visible?

No, I just tested with only asyncomplete with the following minimal wimrc:

```vim
call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
    \ 'name': 'buffer',
    \ 'whitelist': ['*'],
    \ 'completor': function('asyncomplete#sources#buffer#completor'),
    \ }))
```
And `<CR>` confirms completion. Maybe this is the plugin defaults? Can I configure this plugin to respect it?

**Comment by mg979** [comment]
The asyncomplete github page mentions

    inoremap <expr> <cr>    pumvisible() ? "\<C-y>" : "\<cr>"

what's the output of `:imap <CR>`? I'm sure it's that plugin that maps it. And no, there's not a way to change this in VM, most insert mode mappings are not configurable. Using VM autocommands wouldn't work because they're called before mappings, but where's the big issue? I think the default way `<CR>` behaves in insert mode is the most logic, why press it two times to have a new line?

**Comment by Shatur95** [comment]
> what's the output of :imap <CR>?

It says that no mappings... It's weird.

> Using VM autocommands wouldn't work because they're called before mappings, but where's the big issue? I think the default way <CR> behaves in insert mode is the most logic, why press it two times to have a new line?

But `<CR>` becomes broken. It accepts completion and inserts a newline :(

**Comment by Shatur95** [comment]
I also tested [vim-compete](https://github.com/hrsh7th/vim-compete), but in this case `:imap <CR>` says that it was remapped to `<SNR>220_on_char("\n")`.

**Comment by mg979** [comment]
> It says "No mappings found"... It's weird.

It's strange, output of `:set completeopt?` ?

> But \<CR> becomes broken. It accepts completion and inserts a newline

`<CR>` does that by deafult, in vim, it's not broken, it's normal. All I could do is to add another autocommand that is triggered after mappings have been applied, so that you can replace it with a custom mapping, but to me it's just another option. If I don't want to add a new line I don't press CR, I just keep typing or exit insert mode, I don't know why one would expect CR to just accept completion.

**Comment by Shatur95** [comment]
> It's strange, output of :set completeopt? ?

`completeopt=menuone,noinsert,noselect`

Asyncomplete maps it be default, but also allow to disable it.

> <CR> does that by deafult, in vim, it's not broken, it's normal. All I could do is to add another autocommand that is triggered after mappings have been applied, so that you can replace it with a custom mapping, but to me it's just another option. If I don't want to add a new line I don't press CR, I just keep typing or exit insert mode, I don't know why one would expect CR to just accept completion.

Maybe we are talking about different things? If I select completion item, should it be completed with a newline insertion? As I know in all completion plugins it is a default.

**Comment by mg979** [comment]
But the output of `:imap <CR>` is empty  in your regular setup or in the minimal vimrc with asyncomplete? I tested `completeopt=menuone,noinsert,noselect` in a minimal vimrc and CR still adds a new line. It must be a plugin that changes that.

> Maybe we are talking about different things? If I select completion item, should it be completed with a newline insertion?

We're talking about the same thing. If you use a minimal vimrc without plugins, you'll see that CR closes the popup if open, and inserts a new line. I'm sure it's the same with asyncomplete with a minimal vimrc, if CR isn't mapped.

>  As I know in all completion plugins \<CR> only applies selected completion if presents.

Never occurred to me. `<C-Y>` is the mapping for that.

**Comment by Shatur95** [comment]
> But the output of :imap <CR> is empty in your regular setup or in the minimal vimrc with asyncomplete?

With the only asyncomplete installed and minimal vimrc that only enables buffer completion (from [this my message](https://github.com/mg979/vim-visual-multi/issues/103#issuecomment-609386243)):
[![asciicast](https://asciinema.org/a/AcgdDvOOq7wrLZp7P2H9mlXvP.svg)](https://asciinema.org/a/AcgdDvOOq7wrLZp7P2H9mlXvP)

**Comment by mg979** [comment]
I see, but no idea since it's not default vim behaviour. Anyway I'll add a new autocommand, but this is a weird use case, because CR shouldn't be used like that imho.

**Comment by Shatur95** [comment]
> Anyway I'll add a new autocommand, but this is a weird use case, because CR shouldn't be used like that imho.

Thank you! As for me there is no case to select completion and insert a newline. But just press `<CR>` to only select completion is more convenient.  So, if you will add autocomand to add the ability to configure it like in asycomplete, compete or MUcomplete it would be nice.

**Comment by mg979** [comment]
Would you please try the test branch? You should also put in your vimrc:

    autocmd User visual_multi_mappings  imap <buffer><expr> <CR> pumvisible() ? "\<C-Y>" : "\<Plug>(VM-I-Return)"

**Comment by Shatur95** [comment]
Tested f72b3b9a544e27661b135c6cc3f3dfd35cec33f1, but it not works. Also something wrong with undo. Here is the video:
[![asciicast](https://asciinema.org/a/oUKjLU5bnEy2GLTs1XWNbjWml.svg)](https://asciinema.org/a/oUKjLU5bnEy2GLTs1XWNbjWml)

**Comment by mg979** [comment]
I use mucomplete and I don't have the problems you describe. Tested with this new autocommand.

https://asciinema.org/a/Ip4BKZ5iOBmq0hvu0Lf4wDO0v

It must be something else, maybe asyncomplete. I have no idea, my suggestion is that you use `CR` to insert new lines with VM, otherwise you use Tab, Space or keep typing, you shouldn't need to use CR to select a completion.

**Comment by Shatur95** [comment]
> It must be something else, maybe asyncomplete.

You are right. I make the same test with `complete` and it works. Thank you a lot for looking into the issue. I will use other completion plugin with this autocmd.

**Comment by Shatur95** [comment]
> autocmd User visual_multi_mappings  imap <buffer><expr> <CR> pumvisible() ? "\<C-Y>" : "\<Plug>(VM-I-Return)"

I tried this mapping on the latest master, it works, but brokes multiline. If i select several lines and press `dw` (for example) it deletes only current line.

**Comment by mg979** [comment]
> it works, but brokes multiline. If i select several lines and press dw (for example) it deletes only current line.

I don't know what you mean. What I can see is that if I do `dw` it will remove the mapping, I have to fix it.

**Comment by mg979** [comment]
Can you tell me if it's fixed now? Or describe better the problem.

**Comment by Shatur95** [comment]
Thank you a lot, it fixed the problem!
