### ISSUE TITLE
Move Right do unexpected action.

### ISSUE THREAD

**Issue by kevinhwang91** [mg979/vim-visual-multi#104]
**Describe the issue:**
Move Right do unexpected action, but Move Left works fine.

**Steps to reproduce**  

1.Ctrl+Down
2.Tab
3.VM Move Right

I'm using neovim.

-----

- **Operating System**: 
- **Vim Version**: 
- **commit SHA/branch**:

**Comment by mg979** [comment]
Thanks for reporting, please reopen if there are still problems

**Comment by kevinhwang91** [comment]
It works fine now.
