### ISSUE TITLE
Ability to set different cursor shape in vm insert mode. 

### ISSUE THREAD

**Issue by kanashimia** [mg979/vim-visual-multi#105]
It would be nice to to have something like 'guicursor' in nvim; so you can have blinking/bar/underline cursor.

**Comment by mg979** [comment]
Totally impossible, there's not the API to do that in a GUI, and in a terminal I don't think it would be possible anyway, sorry.

**Comment by sblask** [comment]
I don't think this is impossible. You do have hooks for when you enter and exit vm insert mode, right? You can then send certain escape codes to your terminal using echo, see https://vim.fandom.com/wiki/Configuring_the_cursor This is what I did before I switched to nvim which has proper support for cursor shapes builtin. If I remember correctly it worked mostly well. I still use the echo method outside of vim to change cursor shape in ZSH when switching between insert and normal mode: https://github.com/sblask/dotfiles/blob/master/dotfiles_shared/.zshrc.d.symlink/cursor.zsh It's a bit hacky, but if you don't mind it you can give it a go.

**Comment by mg979** [comment]
I also used that trick in terminal vim, but the OP probably meant if it's possible to do that on all cursors, instead of the different highlight VM is using. If he meant that (otherwise why ask it here?) then I think it's impossible.
