### ISSUE TITLE
The color of the statusline in VM mode is the same with normal mode when airline is existed.

### ISSUE THREAD

**Issue by kevinhwang91** [mg979/vim-visual-multi#106]
**Describe the issue:**

**Steps to reproduce**  
I don't understand why you set the value of color to `%#airline_a_bold#` instead of `%#VM_Extend#` when airline is existed. It can't distinguish between normal and VM mode from their colors.
```vim
  let color  = exists('g:loaded_airline') ? '%#airline_a_bold#' : '%#VM_Extend#'
```

-----

- **Operating System**: ArchLinux
- **Vim Version**: NVIM v0.5.0
- **commit SHA/branch**: up to date

**Comment by mg979** [comment]
I thought it was better if it respected airline theme, but you are right.
