### ISSUE TITLE
Can I set the enter key for autocomplete selection in V-I mode?

### ISSUE THREAD

**Issue by ywpkwon** [mg979/vim-visual-multi#108]
Thanks for this great plugin. I'm trying to get more familiar. One good thing is, while at V-I insertmode, I still can use the autocomplete window (I'm using CoC). 

In the usual insert mode, I setup `enter` to select an item from autocomplete list (no new line). However, in V-I mode, if I hit `enter`, it selects the item from autocomplete and also adds new line to the buffer.

Can I change this behavior as in my usual insert mode (enter key for just selection)?

**Comment by mg979** [comment]
See #103.
