### ISSUE TITLE
VM-Visual-* bugs

### ISSUE THREAD

**Issue by eugen0329** [mg979/vim-visual-multi#109]
Hi, thanks for the great plugin.

I decided to not create separate issues, as most of them are likely to have the same origin, so please let me know if you prefer to have them separated.

**Steps to reproduce each**

- Deadlock:
`:call append(0, ['aaa', 'b']) | exe "norm 2gg\<C-v>gg$\<Plug>(VM-Visual-Add)"`
Expected: 2 regions with 'aaa' and 'b' selected.  

-  Wrong regions are selected 1:
`:call append(0, ['a b', 'c d']) | exe "norm gg0$\<C-v>2gg0\<Plug>(VM-Visual-Add)"`
Expected: 2 regions with 'a b' and 'c d' are selected. Got: 'b' and 'd' selected only.

- Wrong regions are selected 2:
`:call append(0, ['a b', 'c d']) | exe "norm 2gg0\<C-v>gg$\<Plug>(VM-Visual-Add)"`
Expected: 2 regions with 'a b' and 'c d' are selected. Got: 'b' and 'd' selected only.

- Can't add a single cursor from the visual mode:
`:exe "norm v\<Plug>(VM-Visual-Cursors)"`
Expected: 1 cursor is added. Got:
```
`:Error detected while processing function vm#commands#visual_cursors[3]..vm#visual#cursors:
line   23:
E684: list index out of range: -1
E116: Invalid arguments for function 119 // function {119} is s:Global.update_and_select_region
```

- Inconsistent x behavior in extended mode with vim's visual mode x.
`:call append(0, ['a b', 'c d']) | exe "norm gg0\<C-v>2gg0\<Plug>(VM-Visual-Add)$x"`
Expected: the same output as after `:call append(0, ['a b', 'c d']) | exe "norm gg0\<C-v>2gg0\<Plug>(VM-Visual-Add)$d"`. Got: only 'a' and 'c' are deleted.

Not sure if it's intentional or not, but it'd be better if `x` worked the same as pressing `d` in extended mode. Right now it deletes only single chars where regions start, while native vim visual selections are entirely cleared after pressing x, so it's slightly confusing.

-----

- **Operating System**: any 
- **Vim Version**: nvim v0.5.0
- **commit SHA/branch**: latest

**Comment by mg979** [comment]
Thanks for reporting.

> most of them are likely to have the same origin

It seems _visual add_ from visual block mode has some problems, I think it depends on where the actual cursor is (if it's in the bottom right corner it works ok), I'll look for a solution. Other visual modes seem ok.

> Can't add a single cursor from the visual mode

I'll fix it.

> Inconsistent x behavior in extended mode with vim's visual mode x

Yes right now `x` behaves like `normal! x`, not like `visual d`, I'll fix that too.

**Comment by eugen0329** [comment]
'x' work now, thanks.

----

Not sure how else it can be reproduced, but adding a cursor in an empty buffer throws an exception:

```
Error detected while processing function vm#commands#visual_add[3]..vm#visual#add[9]..<SNR>35_merge[5]..87[6]..86[8]..90:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "vim-visual-multi/python/vm.py", line 25, in py_rebuild_from_map
    vim.command('call vm#region#new(0, %d, %d)' % (start, end))
vim.error: Vim(return):E867: (NFA) Unknown operator '\%-'
Error detected while processing function vm#commands#visual_add[3]..vm#visual#add[9]..<SNR>35_merge:
   function 90(map, ...) abort dict
1      let l:dict = a:map
2      let l:range = a:0 ? a:1 : []
3      python3 vm.py_rebuild_from_map()
   endfunction
```

Can be reproduced with `%delete | exe "norm \<C-v>\<Plug>(VM-Visual-Add)"`

**Comment by eugen0329** [comment]
> I think it depends on where the actual cursor is

Yes, topleft and botright start positions work fine, while others not. I think there are two options to fix that - to swap columns in those positions to have the same order as with start in the topleft and botright corners or to maintain the main cursor position to remain on the same [line, col].

Now cursor always jumps to the bottom right corner, but more natural behavior is to stay where visual block ends. Example: if the block starts at [2,2] and goes to [1,1], it'd be nice to have 1/2 cursor to set as the current and direction is set to 0. If [1,2] to [2, 1] - cursors is 2/2 and direction is 0 etc. Although, it'd probably involve too much efforts, so it's up to you.

**Comment by mg979** [comment]
> Now cursor always jumps to the bottom right corner, but more natural behavior is to stay where visual block ends

Cursor actually jumps to the last region atm. Anyway I tried to do what you propose, but I don't see how, because I can't get the cursor position from inside visual mode, so I can't know exactly which corner of the selection is selected, visual markers only help so far (`col("'>")` always changes when `O` is pressed, for both possible positions, but `line("'<")` remains the same in these cases).

I'll keep it like this atm.

> Not sure how else it can be reproduced, but adding a cursor in an empty buffer throws an exception

Yes, lol, why should one want to do that... I could check the buffer size, but it's just more code thrown in, I'm not going to add an error check for this kind of things, you can get errors in vim if you do stupid things, I think it's fair if you can get them in VM too.

Other issues seem fixed as far as I can see.

**Comment by eugen0329** [comment]
> because I can't get the cursor position from inside visual mode

if i get it right, just `.` mark should work fine.
```vim
fu! s:end_corner() abort
  if line('.') ==# line("'<")
    echon (col("'<") > col("'>") ? 'topright': 'topleft')
  else
    echon (col("'<") > col("'>") ? 'botleft': 'botright')
  endif
endfu
xnoremap <cr> <esc>:<c-u>call <sid>end_corner()<cr>
``` 

> Yes, lol, why should one want to do that

Not a problem, just a notice in case there're any issues related to this.

> Other issues seem fixed as far as I can see.

For me as well, thanks!

**Comment by mg979** [comment]
xnoremap <cr> <esc>:<c-u>call <sid>end_corner()<cr>

Yes thanks, right now I'm using `:<c-u>` that makes it impossible, but it's doable.

**Comment by mg979** [comment]
I think it works as you proposed now, and issued should be fixed, thanks, please reopen if necessary.

**Comment by eugen0329** [comment]
Works great from each corner now. Thank you.
