### ISSUE TITLE
E117: Unknown function: AutoPairsInit

### ISSUE THREAD

**Issue by daniele-orlando** [mg979/vim-visual-multi#11]
vim-visual-multi: **c46689f** (HEAD -> test, origin/test) _restore plugins mappings/highlight matches on exit (ctrlsf, autopairs)_

> Error detected while processing function vm#reset[15]..vm#comp#reset:
> line   18:
> E117: Unknown function: AutoPairsInit
> Error detected while processing function vm#reset[15]..vm#comp#reset:
> line   18:
> E117: Unknown function: AutoPairsInit

I don't have any of the plugins listed in `s:plugins`.

**Comment by mg979** [comment]
Thanks. I botched a function name :(. It should be fixed now, can you confirm?

**Comment by daniele-orlando** [comment]
Yes I confirm the last commit closes the issue. Thanks!
