### ISSUE TITLE
Workflow question

### ISSUE THREAD

**Issue by urbainvaes** [mg979/vim-visual-multi#110]
Thanks for the great plugin!

My usual workflow with vim-multiple-cursors was the following: I would `<c-n>` on a word, then repeat `<c-n>` to select more occurences, then `<c-p>` once I reach an occurence that I did not wish to select, and finally I would operate on all the selected matches. With vim-visual-multi, if I go too far with `n` or `<c-n>`, there does not seem to be an easy way to discard the last match and go back to the previous state: `q` will unselect the match under the cursor but it will select the next, potentially undesired match. Do you have a recommended workflow for this?

The issue could be summarized as follows: when N matches are selected, it seems impossible to unselect either the first or the N-th match without selecting something else.

**Comment by mg979** [comment]
`Q` maybe?

**Comment by urbainvaes** [comment]
That's exactly what I was looking for, thanks! :)
