### ISSUE TITLE
Bind action to multiple keys

### ISSUE THREAD

**Issue by sQVe** [mg979/vim-visual-multi#112]
Hey :wave:,

I'd like to add multiple bindings for some actions, as my workflow differs somewhat depending on what keyboard I'm on. An example would be this:
```
let g:VM_maps["Add Cursor Down"] = '<M-j>'
let g:VM_maps["Add Cursor Up"] = '<M-k>'
```
I´d like to bind `<M-Up>` and `<M-Down>` too but it does not work to add multiple or adding:
```
nnoremap <M-Down> <M-j>
nnoremap <M-Up> <M-k>
```

How am I supposed to do this? :pray:

**Comment by mg979** [comment]
For basic (non-buffer) bindings it's easy (use `nmap` not `nnoremap`):

    nmap <M-Down> <M-j>
    nmap <M-Up> <M-k>

For `<buffer>` mappings there is an option you can use, I have this:

    let g:VM_custom_remaps = {'<c-p>': 'N'}

**Comment by sQVe** [comment]
@mg979 Ah, of course. Not sure how I missed that. Thanks for the quick response. 🙌🙏
