### ISSUE TITLE
Support for user text objects

### ISSUE THREAD

**Issue by Shatur95** [mg979/vim-visual-multi#113]
Your plugin supports awesome vim-surround plugin. But could you add a support for [vim-sandwich](https://github.com/machakann/vim-sandwich)? This is a similar plugin, but have more features. For example, allow to delete a surround with function or can automatically detect braces. Also it have better visual representation as for me.

**Comment by mg979** [comment]
I wanted to add support for user text objects, but I see that plugin uses `s` that is already used by VM, so it wouldn't work. Btw if you use the same mappings that vim-surround uses, it should work just the same (`ys`, `ds`, `cs`). VM currently doesn't check for vim-surround, it just accepts these mappings.

**Comment by Shatur95** [comment]
Thanks for explanations! I will wait for support for user text object. I leave it open to track the progress.

**Comment by mg979** [comment]
Consider that you can already use any mapping without specific support, if you need it

    :h visual-run-at-cursors

**Comment by Shatur95** [comment]
> Consider that you can already use any mapping without specific support, if you need it

Did not know about it, thanks :)

**Comment by mg979** [comment]
I'm closing this because there's not much I'm going to do beyond this

    :h visual-multi-run-at-cursors
    :h g:VM_user_operators
