### ISSUE TITLE
How to disable key mapping of <CR>?

### ISSUE THREAD

**Issue by xaljer** [mg979/vim-visual-multi#114]
**Describe the issue:**
How to disable key mapping of <CR>? `let g:VM_default_mappings = 0` seems not work.
I think map <CR> is not good, since even i can't use <CR> in quickfix!

**Steps to reproduce**  

1.
2.
3.

-----

- **Operating System**: 
- **Vim Version**: 
- **commit SHA/branch**:

**Comment by mg979** [comment]
What mapping are you talking about? `<CR>` is only mapped in insert mode.

**Comment by xaljer** [comment]
![image](https://user-images.githubusercontent.com/8309631/82750696-6755c500-9de4-11ea-8e9c-ed344e2c209e.png)

**Comment by mg979** [comment]
This is not a default mapping, you must have set it in your vimrc. Default for those is `<C-n>`.

**Comment by xaljer** [comment]
```
let g:VM_default_mappings = 0
let g:VM_maps = {}
let g:VM_maps['Find Under']         = '<C-m>'
let g:VM_maps['Find Subword Under'] = '<C-m>'
let g:VM_maps["Select Cursor Down"] = '<M-C-Down>'
let g:VM_maps["Select Cursor Up"]   = '<M-C-Up>'
nmap <C-LeftMouse>    <Plug>(VM-Mouse-Cursor)
nmap <C-RightMouse>   <Plug>(VM-Mouse-Word)
nmap <M-C-RightMouse> <Plug>(VM-Mouse-Column)
```
This are all my settings about visual-multi. I don't map the <CR>.

**Comment by mg979** [comment]
Also provide vim version.

**Comment by mg979** [comment]
It's because `<C-M>` is the same as `<CR>` in terminals, change those mappings.

**Comment by xaljer** [comment]
@mg979  Thank you.

**Comment by Adnios** [comment]
hello, I want to know how to disable the keymap of <CR> of insert mode. It is conflict with another plug(bullets)

**Comment by mg979** [comment]
@Adnios to disable a specific mapping, set it to an empty string:

    let g:VM_maps["I Return"] = ''

But I don't recommend it for insert mode mappings, if you have a plugin conflict you should solve the conflict

    :help vm-faq-functions

**Comment by Adnios** [comment]
> @Adnios to disable a specific mapping, set it to an empty string:
> 
> ```
> let g:VM_maps["I Return"] = ''
> ```
> 
> But I don't recommend it for insert mode mappings, if you have a plugin conflict you should solve the conflict
> 
> ```
> :help vm-faq-functions
> ```

thank you so much. My problem is solved
