### ISSUE TITLE
[Feature request] Improve some APIs performance and extension

### ISSUE THREAD

**Issue by kevinhwang91** [mg979/vim-visual-multi#115]
**Describe the issue:**
I wrote a wrapper script that let `vim-visual-multi` unite with `ctrlsf`  to preview files automatically.
![2020-05-25-01-19-34-lanczos](https://user-images.githubusercontent.com/17562139/82761316-5466e300-9e2c-11ea-9fa4-dc5fc0b02666.gif)
This's my code: ~~https://github.com/kevinhwang91/dotfiles/blob/master/nvim/navigation.vim#L64-L144~~   https://github.com/kevinhwang91/dotfiles/blob/master/nvim/nav.vim#L66-L165

I almost can preview file automatically in `ctrlsf`' window by invoking `VM-Exit` and `VM-Reselect-Last` API. But I found some issues about `vim-visual-multi` during the development.

1.   `VM-Exit`  and  `VM-Reselect-Last` are slow when selected a lot of targets (more than 100 selected targets in my laptop), I must manually close the option of preview file to keep it smooth.
2. ~~`ctrlsf` will highlight the targets using a pattern, I can get the pattern easily. But VM can't use an increasing or decreasing pattern to find next or find prev in VM mode. I want to feel free to use `<c-n>` to match the targets while entering VM mode, and then navigate or change them.~~(Sorry for my mistake, I have done for this feature)
3.  `VM-Reselect-Last` can't remember the pattern while entering the VM mode first time and the index position after exiting. I can record the pattern and position easily, but I suggest that VM should backup these data.

At the end, I like VM very much, it change my life of nvim.

**Comment by mg979** [comment]
1. ` VM-Reselect-Last` probably jumps from cursor to cursor and activates the preview every time? Maybe you can wrap that key as well.
2. you can disable VM mappings, navigate to new word, enable VM mappings again, add new pattern, then `n/N` will find both patterns, is this what you mean?

        :h vm-faq-disable-mappings

3. Agreed it should record the pattern

About the slowness in 1, if it goes away when you turn off preview feature, that must be the reason and you have to prevent it in your script, I don't think VM can do anything about that.

**Comment by kevinhwang91** [comment]
**To preview a file in ctrlsf window must exit VM mode, if I'm wrong please correct me.**
So I use `VM-Exit` and `VM-Reselect-Last` to exit and restore VM mode while activating to preview file in ctrlsf window.
> 2. you can disable VM mappings, navigate to new word, enable VM mappings again, add new pattern, then `n/N` will find both patterns, is this what you mean?
>    ```
>     :h vm-faq-disable-mappings
>    ```
I mean to search by a pattern like `VMFromSearch`. So I reassign `b:VM_Selection.Regions[-1].pat` to the target's pattern after `VM-Reselect-Last`,  then `VM-Find-Next` or `VM-Find-Prev` will work as expected. I have done for this feature.

>About the slowness in 1, if it goes away when you turn off preview feature, that must be the reason and you have to prevent it in your script, I don't think VM can do anything about that.

Yes, when turning off the preview feature in ctrlsf window, it's smooth. When turning on the preview feature but turning off VM, it's smooth as well. But It will be slow turnning on VM and the preview at the same time.

**Comment by mg979** [comment]
> To preview a file in ctrlsf window must exit VM mode, if I'm wrong please correct me.

I'm not sure it's necessary, if it changes the focus to the preview window it should exit automatically (because entering a new buffer) but I should exclude preview windows from doing this (then VM would be impossible in preview windows).

> I mean to search by a pattern like VMFromSearch.

You should be able to add a pattern directly by calling `b:VM_Selection.Search.add(pattern)`.

**Comment by mg979** [comment]
I pushed a commit to fix 3.

> To preview a file in ctrlsf window must exit VM mode, if I'm wrong please correct me.
It's actually right.

About 1., I made some test with CtrlSF and for me what made it slow are the mappings `[` and `]` but they aren't slow if I use `<nowait>`. So I think it's a question of mappings, not some lock-up.

For the rest I'm keeping it as it is because handling preview windows is hard, I have to quit VM on `BufLeave` and can't wait to see if the next buffer is a preview or not. Not all plugins use `&previewwindow` anyway (CtrlSF's preview for example is not really a preview window).

**Comment by kevinhwang91** [comment]
> I pushed a commit to fix 3.

I have switched the devel branch and tested the `VM-Reselect-Last`. It works as expected.

> About 1., I made some test with CtrlSF and for me what made it slow are the mappings `[` and `]` but they aren't slow if I use `<nowait>`. So I think it's a question of mappings, not some lock-up.

I already have made the map command use `<nowait>`, but I couldn't navigate the selected targets by keeping pressing key (`n` or `]` and so on ) until I released the key when enabling `ctrlsf_auto_preview`. 

Could you paste the tested script here let me check it out?

**Comment by mg979** [comment]
Please update devel branch and try this snippet (works for me)

```vim
function! Vm_ctrlsf()
  packadd ctrlsf.vim
  CtrlSF
  1wincmd w
  nmap <buffer><nowait> ] :let b:VM_skip_reset_once_on_bufleave = 1<cr><plug>(VM-Goto-Next):call ctrlsf#JumpTo("preview")<cr>
  nmap <buffer><nowait> [ :let b:VM_skip_reset_once_on_bufleave = 1<cr><plug>(VM-Goto-Prev):call ctrlsf#JumpTo("preview")<cr>
endfun
command! TVM call Vm_ctrlsf()
```

**Comment by kevinhwang91** [comment]
It also works for me. Now the user custom script is very simple. Thanks for your hard work.
If you think these patches are eligible to merge into the master branch, please close this issue.

> Airline will slow the navigation.

**Comment by mg979** [comment]
Thanks, it's in master now.
