### ISSUE TITLE
Problem with clipboard synchronization

### ISSUE THREAD

**Issue by Shatur95** [mg979/vim-visual-multi#116]
**Describe the issue:**

If made changes in clipboard outside vim with `set clipboard=unnamedplus` it is not synchronized with VM.

**Steps to reproduce**

0. `set clipboard=unnamedplus`
1. Yank any text inside vim.
1. `<C-n>` (at any word, of course)
2. Minimize vim and copy any other text outside in clipboard
3. `p`

**Expected behavior**

Selected word replaced with new text from clipboard.

**Actual behavior**

Selected word replaced with old text from clipboard.

**Notes**

I not sure that this is a bug. Pasting without VM works. If I use `"+p` in VM it works too. It looks like `set clipboard=unnamedplus` is not respected. I'm not sure if it expected.

-----
- **Operating System**: Arch Linux
- **Vim Version**: Neovim v0.5.0-539-g91e41c857
- **commit SHA/branch**: 40991d5

**Comment by mg979** [comment]
It's intentional, `&clipboard` is set to empty value, so `unnamedplus` won't work, but `"+p` will work. I had lots of problems with clipboard and neovim, keeping that setting broke lots of VM internal operations, you may find something in early issues. Atm I won't change this, I should mention it in the documentation though.

I don't think it's a big issue anyway, as you noted `"+p` works.

**Comment by Shatur95** [comment]
Thanks for explanations! Is it safe to remap `p` to `"+p` in VM?

**Comment by mg979** [comment]
Just try it.

**Comment by Shatur95** [comment]
I tried the following, but it do not work for me :(

```vim
autocmd vimrc User visual_multi_mappings imap p "+p
```

Is I doing something wrong?

**Comment by mg979** [comment]
Update master, then this should work:

    autocmd User visual_multi_mappings nmap <buffer> p "+<Plug>(VM-p-Paste)

But if you force a register this way, you won't be able to use other registers, I think this would be better:

    nmap \p "+p

and it would also work in VM (after you update master).

**Comment by Shatur95** [comment]
Thank you a lot, works as expected!
