### ISSUE TITLE
[Feature request] Sorting

### ISSUE THREAD

**Issue by eyalk5** [mg979/vim-visual-multi#117]
Hi, 
Could you please add the option to sort by the selected regions (assuming one per line)?

Thanks.

**Comment by mg979** [comment]
`:VMSort` from current master, please reopen if you have problems.

**Comment by eyalk5** [comment]
Thanks a lot. I think that by default it should expand the lines. That is, the lines should be kept and just the order of the lines should be changed according to the sorting.

**Comment by mg979** [comment]
That's a completely different thing (and not easily done). I'll see if I can come out with something but it won't be right now.

**Comment by mg979** [comment]
Ok in the test branch `VMSort!` should behave the way you want, can you test it please? thanks

**Comment by eyalk5** [comment]
It seems to work at first. Bizarrely, I tried to sort 400 lines using a column (of different lengths), and I got very strange results. I could understand the pattern, but it wasn't sorted.

**Comment by mg979** [comment]
So it isn't working with the 400 lines test?

**Comment by eyalk5** [comment]
Yes, it doesn't work. I suspect you might need to handle the case of a shorter region in  s:sort_lines. I am not sure.

**Comment by mg979** [comment]
Could you post the text for the test that doesn't work please?

**Comment by eyalk5** [comment]
Can I send it by email/twitter? it is a bit sensitive though not very much

**Comment by mg979** [comment]
You could replace the sensitive stuff with garbage text, or send it to the email in my github front page, thanks.

**Comment by mg979** [comment]
Btw in this case you can use the built in `:sort /pattern/` command, for example

    %sort /.*\%43v/

To sort lines on the base of what comes after column 42 in your file.

**Comment by mg979** [comment]
I don't think this will be done.
