### ISSUE TITLE
creating two columns

### ISSUE THREAD

**Issue by eyalk5** [mg979/vim-visual-multi#118]
Hi,
well, it is probably possible. currently, if I do `\\c` after selecting with `c-v` it works(btw raises on visual).
But then if I want to add another column, it doesn't work anymore. I select another region using c-v, clicking \\c and the older one got deleted. 

How should I do it?

PS, also similarly when doing \\A , the  older regions are deleted.

Thanks

**Comment by mg979** [comment]
You can do it either by:

1. I generally use (Ctrl+)arrows keys to move where I want, then add cursors
2. using mouse (`<Plug>(VM-Mouse-Column)`)
3. disabling mappings first, move with motions, enable mappings again, create cursors
> I select another region using c-v, clicking \c and the older one got deleted.

I must fix this.

**Comment by mg979** [comment]
A fix for the issue is in the test branch.
