### ISSUE TITLE
How can I remove the message `Press Enter or type command to continue` in small screen(mobile phone)

### ISSUE THREAD

**Issue by fcying** [mg979/vim-visual-multi#12]
I connect linux server by ssh client.
If I connect it by use pc, it work fine.
If I connect it by use mobile phone, it will pop message `Press Enter or type command to continue`  after I press `c-n`. I test both in `termius` and `juicessh`.

![image](https://user-images.githubusercontent.com/106934/43594647-57adeabe-96ad-11e8-87d6-e21a625f3d5d.png)

**Comment by mg979** [comment]
The problem is that the message string is long and already with `cmdheight=1` that happens. Try setting:

```vim
let g:VM_cmdheight = 3
```

**Comment by mg979** [comment]
I added an option to disable the infoline, and a command to show it manually:

```vim
let g:VM_manual_infoline = 1
```

Default for manual command is `<leader>l`.
