### ISSUE TITLE
Compatible with nvim-0.5 on_yank

### ISSUE THREAD

**Issue by kevinhwang91** [mg979/vim-visual-multi#121]
**Describe the issue:**
When I enable nvim-0.5 highlight on_yank feature, using `VM-Find-Under` to highlight will lag.

I'm not sure that is an issue for vim-visual-multi.

**Steps to reproduce**  

1.  `nvim -u mini.vim xxx`
2.  press `<C-n>`
3.  repeat step 2 quickly and found highlight lagged.

mini.vim
```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'mg979/vim-visual-multi'
if has('nvim-0.5')
    augroup LuaHighlight
        autocmd!
        autocmd TextYankPost * silent! lua require'vim.highlight'.on_yank('IncSearch', 800)
    augroup END
endif
call plug#end()
```
-----

- **Operating System**: ArchLinux
- **Vim Version**: nvim-0.5
- **commit SHA/branch**: latest commit

**Comment by mg979** [comment]
VM uses yanks a lot, you should do something like
```vim
if has('nvim-0.5')
    augroup LuaHighlight
        autocmd!
        autocmd TextYankPost * if !exists('b:visual_multi') | exe "silent! lua require'vim.highlight'.on_yank('IncSearch', 800)" | endif
    augroup END
endif
```

**Comment by kevinhwang91** [comment]
Thanks! I think the document should be improved, other users will also encounter this issue sooner and later.

**Comment by mg979** [comment]
Yes I will add it.

**Comment by kevinhwang91** [comment]
https://github.com/neovim/neovim/pull/12549, API has changed.

```vim
if has('nvim-0.5')
    augroup LuaHighlight
        autocmd!
        autocmd TextYankPost *
                    \ if !exists('b:visual_multi') |
                    \ execute "silent! lua vim.highlight.on_yank({higroup='IncSearch', timeout=800})" |
                    \ endif
    augroup END
endif
```
