### ISSUE TITLE
howto select the end of a sevral line ?

### ISSUE THREAD

**Issue by espilonlola** [mg979/vim-visual-multi#123]
Hi,
Sorry for this n00b question but I didn't find it in the wiki, quickstart, faq or help...
I'ld like to add caraters at the end of each selected lines.
I'd tried `$` + `C-n` +`space` + `C-arrow` or `$` + `C-v` + `C-n` and other thing without succes
A little help would be nice
Thanks

**Comment by mg979** [comment]
Several ways:

- `c-down` to add cursors on each line, then `$`
- select lines visually, then `\\c`, then `$`

If you want to start insert mode and add characters replace `$` with `A`.

**Comment by espilonlola** [comment]
Thanks and sorry for the trouble. 
I should have read before the very good tutorial that lay in `.vim` > `plugged` > `vim-visual-multi` > `tutorialrc` 
lauched with the command `vim -Nu tutorialrc` 
Saying that for the others lazzy n00bs like me ;-)
