### ISSUE TITLE
alignment is off on 1st cursor

### ISSUE THREAD

**Issue by antoinemadec** [mg979/vim-visual-multi#125]
**Describe the issue:**
```vim
echo "this"
  echo "this"
    echo "this"
```
after alignment on ```echo``` looks like this:
```vim
   echo "this"
    echo "this"
    echo "this"

```

**Steps to reproduce**  

1. ```\\\A``` on echo
2. ```\\\a``` to align

-----

- **Operating System**:  Debian Testing
- **Vim Version**:  NVIM v0.5.0-593-g1ca67a73c
Build type: Release
- **commit SHA/branch**:  master

**Comment by mg979** [comment]
Thanks for reporting, fix is ready, I'm waiting for your fixed PR.
