### ISSUE TITLE
Strange slowdowns with repeated guu/gUU at cursors

### ISSUE THREAD

**Issue by mg979** [mg979/vim-visual-multi#127]
See https://github.com/mg979/vim-visual-multi/issues/124#issuecomment-662068471.

Strange exponential slowdowns after repeating certain actions, as `guu/gUU` at cursors. Memory/CPU usage seems normal, and functions profiling times too. The slowdowns are still present after VM is exited and restarted, and even in different buffers.

Also tried running commands with:

- `lockmarks`
- `noautocmd`
- `set noswapfile`

The same commands run with `\\z` do not cause the problem.

**Comment by antoinemadec** [comment]
@mg979 , does this mean that we don't support custom operators anymore?
Are ```guu``` and ```gUU``` seen as custom operators?

I will create a pull request with timings/timeout tests soon.

**Comment by mg979** [comment]
Nothing changed, it was a bug and it's fixed. I called them `custom` just because they are using the same kind of call that custom operators use. The problem is that they were storing the changed text, and surely there is some problem with that. It may resurface again since the same mechanism is used by other commands, but I never saw it before.

**Comment by mg979** [comment]
> I will create a pull request with timings/timeout tests

What's their purpose?

**Comment by antoinemadec** [comment]
> > I will create a pull request with timings/timeout tests
> 
> What's their purpose?

Catching bugs like this one and making sure there is no drastic performance regression caused by a commit.
I was thinking of adding:
  - a global timeout (let's say no test should take more than 30 sec)
  - an optional file specifying a max time of execution (if not present, we don't check execution time)

What do you think?

**Comment by mg979** [comment]
Mmm I would not do it. Then timeouts should be per test, because some tests are much longer than others. But anyway it's much work for little gain. This was a very specal case that a regular test wouldn't have even caught (not doing tests with 20x repeated commands).

If it is done, it shouldn't be done for all tests, but only for performance-specific tests, for example you have a test that performs some intensive commands, and then you can see if there's some big performance difference between commits. But it doesn't make sense to do that for all tests.

**Comment by antoinemadec** [comment]
@mg979 maybe I was not clear in my previous enough, but I already addressed your remarks in my previous comment (and I agree with them).

The global timeout is a fail safe mechanism that says "if any test takes more than X time, there is a problem".
It is not necessary, but a nice to have.

The exec time would not be checked unless the **max_exec_time.txt** is found.

**Comment by mg979** [comment]
> The global timeout is a fail safe mechanism that says "if any test takes more than X time, there is a problem".

Ok I would use a second commented line instead of an extra file. There's the problem that test execution depends on machine speed too.

I think an exact measurement of the test duration would be more useful though, but only for tests that are specifically tailored for this purpose.

**Comment by antoinemadec** [comment]
> Ok I would use a second commented line instead of an extra file.

I have built a lot of those "verification/performance check" flows in my previous jobs.
Comments in files and home made parsing are generally not a good idea.

If you want to add more options later and you don't want to add new files each time, a good option would be to add a **config.json** per test for instance.
There is a really good python package that parses JSON.

I will propose a PR with an extra file, but file free to modify it :smiley: 

>There's the problem that test execution depends on machine speed too.

It will measure CPU time, it should not vary too much from one machine to another.
The margin of error will be high enough to absorbe that.

> I think an exact measurement of the test duration would be more useful though, but only for tests that are specifically tailored for this purpose.

Agreed.

**Comment by mg979** [comment]
Ok. 

By the way looking back at this issue definitely the problem was a VM bug, it was concatenating stuff in the unnamed register (reaching 20K lines and beyond when it was slow), because `guu/gUU` command weren't changing the register, and storing text should have only happened in that case.

**Comment by mg979** [comment]
> If you want to add more options later and you don't want to add new files each time, a good option would be to add a config.json per test for instance. There is a really good python package that parses JSON.

That maybe would be better right away. Built in `json` module should be enough though.
