### ISSUE TITLE
Test branch: Undefined variable: g:mapleader

### ISSUE THREAD

**Issue by joereynolds** [mg979/vim-visual-multi#13]
As soon as I start NVIM v0.3.2, I'm greeted with the following message:
```
Error detected while processing function <SNR>37_VM_Init[64]..vm#maps#default[4]..<SNR>66_build_permanent_maps:
line   15:
E121: Undefined variable: g:mapleader
Error detected while processing function <SNR>37_VM_Init[64]..vm#maps#default[4]..<SNR>66_build_permanent_maps:
line   15:
E15: Invalid expression: g:mapleader ==? '<Space>' || g:VM_leader ==? '<Space>'
```
I'm happy to provide more information if you can let me know what it is you'd like to know :)

Thanks!

**Comment by mg979** [comment]
It seems you don't have a g:mapleader defined in your vimrc. Is it possible? Or it only happens in nvim 0.3.2?

I'm not checking if one is defined, I'll fix it, for now you can add to the vimrc:

```vim
let g:mapleader = "\\"
```

**Comment by joereynolds** [comment]
Ah correct, I don't have a mapleader defined.
Thanks for the help!

**Comment by mg979** [comment]
My mistake that I didn't check for the existance. I'll fix it in the next commit.
