### ISSUE TITLE
In Cursor mode, `ci"` `ca"` is not correct.

### ISSUE THREAD

**Issue by l-qing** [mg979/vim-visual-multi#131]
# This plugin is real real awesome!!!
Thank you!

# Describe the issue:
In Cursor mode, `ci"` `ca"` is not correct.

# Steps to reproduce:
1. Open vim
	```
	vi -Nu xxxx/vim-visual-multi/tutorialrc
	```
2. Add test text
	```
	{"hello 1" 1}
	{"hello 2" 2}
	{"hello 3" 3}
	```
3. Active visual-multi (`*` expression the cursor)
	```
	{"*hello 1" 1}
	{"*hello 2" 2}
	{"*hello 3" 3}
	```
4. Exeute `ci"` <br>
	Result
	```
	{"* 1}
	{"* 2}
	{"* 3}
	```
	Expect

	```
	{"*" 1}
	{"*" 2}
	{"*" 3}
	```
5. `ca"` is not correct too.
	```
	{"*hello 1" 1}
	{"*hello 2" 2}
	{"*hello 3" 3}
	```

	Result

	```
	{*}
	{*}
	{*}
	```
	Expect

	```
	{*1}
	{*2}
	{*3}
	```
6. `ci}` is correct.
	```
	{*}
	{*}
	{*}
	```

# Environment:
* Operating System: MacOS 10.15.6
* commit SHA/branch: master(f317dca3ba4a0bc7fb1737770d92f29db1d038e8)
* Vim Version: 8.2.1300

**Comment by mg979** [comment]
Thanks for the report, I see why this is happening, I didn't notice because I use [welle/targets](https://github.com/wellle/targets.vim) and it doesn't happen with it. I should fix it today.

**Comment by mg979** [comment]
Please reopen if there are still problems.

**Comment by l-qing** [comment]
Pefect!

It works fine now.
