### ISSUE TITLE
Plugin behavior is not as expected in the macro run by bufdo

### ISSUE THREAD

**Issue by l-qing** [mg979/vim-visual-multi#134]
# This plugin is awesome!!!
I am coming again.😁

I encountered a problem when recommending the plugin to my friends.
I do not know if this is my problem or the plugin problem.

I did not find a similar issue in the document and issue list.
So, let me consult.

# Plugin behavior is not as expected in the macro run by bufdo
But when I run it manually or `:normal @a`, it meets expectations.

# Test case
Two files with the same content.
```
# a.txt
begin_search_nocase()
beGin_seaRch_noCase()
_beGin_seaRch_nocase_100_()

# b.txt
begin_search_nocase()
beGin_seaRch_noCase()
_beGin_seaRch_nocase_100_()
```

# Steps to reproduce
## 1. Open file
```
vi a.txt b.txt
```

## 2. Use regular matching content
```
\<_*\zs[a-zA-Z]\w*\ze(
```

## 3. Record macro
Key sequence:
```
qaggVG\\f\\CP^[q
```

The registers:
```
:registers "a
Type Name Content
c  "a   ggVG\\f\\CP^[
```

### a. `:normal @a`
It meets expectations.
The content of the file is modified to this:
```
BeginSearchNocase()
BeginSearchNocase()
_BeginSearchNocase100_()
```

### c. `:bufdo normal @a`
*Plugin behavior is not as expected.*
The content of the file is modified to this:
```
beGin_seaRch_nocase_100_()
beGin_seaRch_nocase_100_()
_beGin_seaRch_nocase_100_()
```

I don't know where the problem is.

# Environment
Operating System: MacOS 10.15.6
commit SHA/branch: master(cb994375fcbf032adfef6d31d8fcfa59bab381c8)
Vim Version: 8.2.1350

**Comment by mg979** [comment]
First, VM runs in a single buffer, so commands that run in multiple buffers are untested/unsupported. This doesn't mean that they can't work but I don't see the point other than experimenting for fun. Second, with `bufdo` are the files changed in the same way? Or it's the second file that is wrong?

**Comment by l-qing** [comment]
> First, VM runs in a single buffer, so commands that run in multiple buffers are untested/unsupported. This doesn't mean that they can't work but I don't see the point other than experimenting for fun. Second, with `bufdo` are the files changed in the same way? Or it's the second file that is wrong?

Thank you for your reply.

With `bufdo`, are the files changed in the same way.
Thy are both changed to this:

	beGin_seaRch_nocase_100_()
	beGin_seaRch_nocase_100_()
	_beGin_seaRch_nocase_100_()

I don't know the internals of `bufdo`,
Before, I thought `bufdo` was executed one by one.
That's why I have this question.

<hr>
I add the macro `@q`.It can fulfill the needs of this scene.

Key sequence:
```
qq@a:bn^Mq
```
The registers:
```
:registers "q "a
Type Name Content
  c  "a   ggVG\\f\\CP^[
  c  "q   @a:bn^M
```

## 1. Go to first buffer by `:bfirst`
## 2. Execute `10@q`
## 3. All buffers changed meet expectations.
```
BeginSearchNocase()
BeginSearchNocase()
_Beginsearchnocase100_()
```

**Comment by mg979** [comment]
Now I remember that `bufdo` and similar commands disable a lot of autocommands to increase speed. So it's clear that it can't work with VM.

**Comment by l-qing** [comment]
> Now I remember that `bufdo` and similar commands disable a lot of autocommands to increase speed. So it's clear that it can't work with VM.

Thank you for your reply.
This plugin is very powerful, Thanks!
