### ISSUE TITLE
Plugin does not seem to handle the exception when use vm-filter `\\f`

### ISSUE THREAD

**Issue by l-qing** [mg979/vim-visual-multi#135]
# This plugin is awesome!!!
Here I come again.😁

# Plugin does not seem to handle the exception when use vm-filter `\\f`
After using `\\f`, when I pressed the `y`, vim reported the following error:
```
处理 function <SNR>10_Yank 时发生错误:
第1 行: E716: Dictionary 中不存在键: Global.region_at_pos())
```

Only when the regex cannot match anything, this error will happen.

# Test case
```
# a.txt
aaaaaaaa
bbbbbbbb
```

# Steps to reproduce
## 1. Open file
```
vi a.txt
```

## 2. Use regular matching content
```
/cccccc
```

## 3. Use `vm-filter`
Key sequence: `ggVG\\f`
There are currently no exceptions.

But, when I pressed the `y`, vim reported an error on the above.

# Environment
Operating System: MacOS 10.15.6
commit SHA/branch: master(cb994375fcbf032adfef6d31d8fcfa59bab381c8)
Vim Version: 8.2.1400
Vimrc : visual-multi/tutorialrc (add one line in the head of `tutorialrc`:`set nocompatible`)

**Comment by mg979** [comment]
Thanks for the report, it shoud be fixed.

**Comment by l-qing** [comment]
> Thanks for the report, it shoud be fixed.

Great, you deal with issue quickly each time.

**Comment by mg979** [comment]
Yeah, I don't like bugs.
