### ISSUE TITLE
Remap shift+{left,right}

### ISSUE THREAD

**Issue by saucesaft** [mg979/vim-visual-multi#136]
Hi, this plugin is great. Just have one concern, before installing this tweak I had applied "behave mswin" which made shift+{left,right} select one character in visual mode. This plugin remaps those keybinds, so is there an option to remap them to something like Alt+{Left, Right} ?
Thanks :)

**Comment by mg979** [comment]
: vm-faq-mappings

**Comment by mg979** [comment]
In particular,  for `<S-left>` and `<S-right>` plugs are `Select h` and `Select l` (you can see with `:nmap`).

**Comment by saucesaft** [comment]
Thanks a lot!
