### ISSUE TITLE
Question: why does not add `set nocompatible` in tutorialrc?

### ISSUE THREAD

**Issue by l-qing** [mg979/vim-visual-multi#138]
# Description
Without `set nocompatible`, a lot of the feature of the plugin is almost unusable.
If I press `\\\` or `Ctrl-n`, will show many errors.

# Environment
Operating System: MacOS 10.15.6
commit SHA/branch: master(37a9a0070c23d058584760db21444807d9534be3)
Vim Version: 8.2.1400
Vimrc : visual-multi/tutorialrc

**Comment by mg979** [comment]
I thought it was not necessary, fixed it just in case.
