### ISSUE TITLE
Is there a way to immediately exit insert mode?

### ISSUE THREAD

**Issue by npearson72** [mg979/vim-visual-multi#139]
**Describe the issue:**

While editing in insert mode, I have to hit `<esc>` twice to exit insert mode. Is there a way to configure it so I will exit immediately?

**Steps to reproduce**  

1. Select multiple items
2. Hit `c` for change
3. Hit `<esc>`

Notice that you are in a different mode, but not released back to standard NORMAL.

-----

- **Operating System**:  Mac OS 10.5
- **Vim Version**: NVIM v0.4.3
- **commit SHA/branch**: `0bbcfa8`

**Comment by mg979** [comment]
Maybe it depends on our terminal, try to disable arrow keys in insert mode:

```
let g:VM_maps = {}
let g:VM_maps["I Left Arrow"] = ''
let g:VM_maps["I Right Arrow"] = ''
let g:VM_maps["I Up Arrow"] = ''
let g:VM_maps["I Down Arrow"] = ''
```

**Comment by mg979** [comment]
Or are you saying that you want to quit VM entirely after you exit insert mode? Currently this isn't possible, but I can add an option for it.

**Comment by npearson72** [comment]
Thanks for reply. Unfortunately it didn't work.

**Comment by mg979** [comment]
Please read my second comment.

**Comment by npearson72** [comment]
> Or are you saying that you want to quit VM entirely after you exit insert mode? Currently this isn't possible, but I can add an option for it.

Yes, I would really appreciate it. I always expect `<esc>` to immediately quit insert mode, and when it doesn't, I end up hosing a few lines of text forgetting that I'm in some VSM mode.

**Comment by mg979** [comment]
Well `<esc>` quits insert mode, but it doesn't quit VM if you were in VM. So you must hit it twice to quit VM.
Anyway I'll add an option to quit VM automatically after you leave insert mode.

**Comment by npearson72** [comment]
Awesome, thank you. Thanks for the plug-in too. Very useful!

**Comment by mg979** [comment]
Set `g:VM_quit_after_leaving_insert_mode` to 1, also read the help:

    :help g:VM_quit_after_leaving_insert_mode

**Comment by npearson72** [comment]
Nice, thanks for the update!
