### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by blayz3r** [mg979/vim-visual-multi#14]
![image](https://user-images.githubusercontent.com/12205650/45066745-c4986880-b08d-11e8-8199-29bb3bcb5703.png)

**Comment by mg979** [comment]
I'm trying to reproduce it but couldn't yet. The variable is initialized on VimStart. Are you using vim or neovim?

**Comment by mg979** [comment]
By the way until we find out what's happening, you can set:
```
let g:VM_highlight_matches = 0
```
to disable it (restores previous behaviour).

**Comment by blayz3r** [comment]
Ok that solves it works for now

**Comment by mg979** [comment]
Ok, I made `g:VM_highlight_matches` default to 0, so you don't need to add it to the `vimrc` anymore, if you update. Thanks.

**Comment by blayz3r** [comment]
Ok works now
