### ISSUE TITLE
Unexpected cursor jump with VM_highlight_matches

### ISSUE THREAD

**Issue by kovetskiy** [mg979/vim-visual-multi#140]
Nevermind, I incorrectly understood what VM_highlight_matches does and thought it's a sort of boolean. 

The cursor jumps to the start of the file and completely breaks the main feature of the plugin.

1. Create a file with contents:
```
111 222
333 333
333
```
2. Navigate to the line with `333 333`, execute: `let g:VM_highlight_matches = 1`
3. Press `<C-N>`

Actual result:
cursor jumps to the beginning of the file and 111 is selected.

Expected:
333 selected on the same line

(I used the minimal vimrc, latest version of the plugin)

```
NVIM v0.5.0-567-g4496628c1
```

**Comment by mg979** [comment]
let g:VM_highlight_matches = 1

The content of that variable is executed `as-is` so you're brought on line 1. I can add a pattern test to ensure it's some `hi` command but in the documentation is stated what that variable does.

**Comment by kovetskiy** [comment]
> I can add a pattern test to ensure it's some hi command 
No need but thanks!
