### ISSUE TITLE
[Question] trigger visual regex search with scripted pattern

### ISSUE THREAD

**Issue by ipod825** [mg979/vim-visual-multi#141]
Hi, I would like to know how to do regex search in visual mode with scripted patterns.
I've managed to do it for `VM-Start-Regex-Search`, but I can't figure out how to do it for `VM-Visual-Regex`.
Here's how I do it for `VM-Start-Regex-Search`:
```vim
function! s:SelectAllMark()
    call feedkeys("\<Plug>(VM-Start-Regex-Search)".msearch#joint_pattern()."\<cr>")
    call feedkeys("\<Plug>(VM-Select-All)")
endfunction
nmap <leader>r :call <sid>SelectAllMark()<cr>
```
where `msearch#joint_pattern()` will return a search pattern like `\<SelectAllMark\>\|\<call\>`.
The limit of the previous functions is that it will select all matching words in the entire document. But I sometimes only want to select words within a range. How do I achieve it?

context: [msearch.vim](https://github.com/ipod825/msearch.vim) can select multiple word/patterns, I found it useful to use it with `vim-visual-multi` so that I can select the patterns instead of typing them.

**Comment by mg979** [comment]
First:

    :h VMFromSearch

But it doesn't accept a range. I should rename it in `:VMSearch` and let it accept a pattern and a range.

Look also at:

    :h vm-find-operator

You can start the regex search, without selecting all matches, then use the `m` operator.

**Comment by ipod825** [comment]
`VMFromSearch` (with range support) seems to be close to what I want. However, it assumes the pattern is in the `quote/` register.  So I still need to type the search pattern manually, which is what I am trying to avoid. It would be better to have a separate function that takes the pattern as argument and start searching the pattern. `VMFromSearch` can be implemented by this function by passing in `quote/`'s content as the argument. And I can call this function passing in my patterns obtained easily without typing the pattern manually.

**Comment by mg979** [comment]
You can do

    let @/ = your_pattern

from your script, hen start `VMFromSearch`. I'll make it accept a range anyway.

**Comment by mg979** [comment]
In the `test` branch there is a reworked command `:VMSearch` if you want to try it

    :h :VMSearch

**Comment by ipod825** [comment]
Nice! For proprietary here's the script to integrate with [msearch.vim](https://github.com/ipod825/msearch.vim)
```vim
function! s:SelectAllMark()
    exec 'VMSearch'.msearch#joint_pattern()
    call feedkeys("\<Plug>(VM-Select-All)")
    call feedkeys("\<Plug>(VM-Goto-Prev)")
endfunction
function! s:VSelectAllMark()
    let [line_start, column_start] = getpos("'<")[1:2]
    let [line_end, column_end] = getpos("'>")[1:2]
    exec line_start.','.line_end-1.' VMSearch '.msearch#joint_pattern()
endfunction
function! s:VSelectAllMark()
    let [line_start, column_start] = getpos("'<")[1:2]
    let [line_end, column_end] = getpos("'>")[1:2]
    exec line_start.','.line_end.' VMSearch '.msearch#joint_pattern()
endfunction

nnoremap <leader>r :call <sid>SelectAllMark()<cr>
vnoremap <leader>r :<c-u>call <sid>VSelectAllMark()<cr>
```
