### ISSUE TITLE
VM_before_auto and VM_after_auto

### ISSUE THREAD

**Issue by kovetskiy** [mg979/vim-visual-multi#142]
Hi

Back in the day there were functions which I could implement in my .vimrc and they would be called:
VM_after_auto
VM_before_auto

Now I see it's missing for some reason (and I don't know when and why.

Is there any alternative (and example if possible) on how to do actions before and after entering visual-multi mode?

**Comment by mg979** [comment]
I replaced them some times ago with autocommands, but I forgot to document them
```vim
autocmd User visual_multi_before_cmd  call MyFunc1()
autocmd User visual_multi_after_cmd   call MyFunc2()
```

**Comment by mg979** [comment]
But those are triggered before/after commands. If you want functions that are called on start/exit, see

    :h vm-faq-functions

**Comment by kovetskiy** [comment]
Thanks!
