### ISSUE TITLE
[Question] Creating cursors in macros

### ISSUE THREAD

**Issue by nswerhun** [mg979/vim-visual-multi#143]
I am trying to make a macro which creates multiple cursors for me to insert in a specified template. A simplified version of what I have in my vimrc:
```
inoremap ;h This is pos1:<CR>pos2:<esc>\\\<up>8<right>\\\a
```
My goal is that, when I press `;h`, I can type after the colons. The problem is, the new cursors are not created, and after I press `;h`, I am in normal mode, however, the text is there, and my cursor is in the right position. What am I doing wrong?

**Comment by mg979** [comment]
You use `inoremap`.

**Comment by nswerhun** [comment]
> You use `inoremap`.

What should I use instead?

**Comment by mg979** [comment]
Learn vim first, plugins later.
