### ISSUE TITLE
How to integrate with chaoren/vim-wordmotion?

### ISSUE THREAD

**Issue by ipod825** [mg979/vim-visual-multi#145]
[chaoren/vim-wordmotion](https://github.com/chaoren/vim-wordmotion) defines motion mapping to traverse camel cases more easily. For example: `nmap w <Plug>WordMotion_w`, then `w` moves the cursor in `|CamelCase` to the start of `Case`.

It seems the closest mechanism to integrate it with visual-multi is `g:VM_custom_motions`. However, the function `vm#commands#motion` doesn't seem to take effect for the following form `let g:VM_custom_motions  = {'w':'<Plug>WordMotion_w'}`.

**Comment by mg979** [comment]
Atm I don't want to bother with this kind of things, sorry. If you stick with vim motions I think it's ok in cursors mode.
