### ISSUE TITLE
<S-left/right> selection produces errors

### ISSUE THREAD

**Issue by savchenko** [mg979/vim-visual-multi#147]
**Describe the issue:**
<S-left/right> produce errors.

**Steps to reproduce** 

1. nVim 0.3.4, Debian stable
2. Create a new, empty file. Insert: `abc`.
3. Exit insert mode, select text with \<Shift> and arrow button.
4. Try to enter input mode.
5. The following error is returned:
```
Error detected while processing function 447[47]..448[13]..449[6]..366:
line    5:
E716: Key not present in Dictionary: ticks, backup.last)
E116: Invalid arguments for function index
E15: Invalid expression: index(backup.ticks, backup.last)
Press ENTER or type command to continue
```

-----

- **Operating System**: Debian 10.6
- **Vim Version**: NVIM v0.3.4, Build type: Release, LuaJIT 2.1.0-beta3.
- **commit SHA/branch**: N/A
-----

**Additional notes**
Using <Ctrl+up/down> and entering insert mode with multiple cursors works just fine.

**Comment by mg979** [comment]
Thanks for reporting. I can't reproduce with a more recent nvim or vim 8.1. Anyway I'll add an error check in that function.

**Comment by mg979** [comment]
Actually I'd like to be able to reproduce the problem, because it shouldn't be happening.

**Comment by savchenko** [comment]
> Actually I'd like to be able to reproduce the problem, because it shouldn't be happening.

`:VMDebug` returns nothing... Any other things that might help you to investigate?

**Comment by savchenko** [comment]
> Actually I'd like to be able to reproduce the problem, because it shouldn't be happening.

`:VMDebug` returns nothing... Is there anything else that might help you to investigate?

**Comment by savchenko** [comment]
...Skipping empty lines works fine. Triggering via:
```vim
function! SkipEmptyLines()
  if exists("g:VM_skip_empty_lines")
    if(g:VM_skip_empty_lines == 1)
      let g:VM_skip_empty_lines = 0
      echo "VM: Not skipping empty lines"
    else
      let g:VM_skip_empty_lines = 1
      echo "VM: Skipping empty lines"
    endif
  else
    let g:VM_skip_empty_lines = 1
    echo "VM: Skipping empty lines"
  endif
endfunc
```

**Comment by mg979** [comment]
I was actually asking for a way to reproduce the problem reliably. I can't reproduce with nvim 0.4.4 and vim 8.1, following the instructions in the OP.

**Comment by savchenko** [comment]
I have tried nVim v0.4.4 with no plugins/bundles except of the `vim-visual-multi` and was able to trigger an error. 
 Probably my `.vimrc`, investigating further...

**Comment by mg979** [comment]
Did you try the minimal vimrc that is recommended in the issue template?

**Comment by mg979** [comment]
Also, are you on master branch?

**Comment by savchenko** [comment]
Yes, I was able to narrow it down to this snippet:
```vim
" multi-cursors
let g:VM_silent_exit = 1
let g:VM_exit_on_1_cursor_left = 1 
```

**Comment by mg979** [comment]
Ok I can reproduce... It's `VM_exit_on_1_cursor_left`.

**Comment by mg979** [comment]
I removed the option, rather useless and I had even forgot about it. Thanks for taking the time to debug it anyway.
