### ISSUE TITLE
[Question] - Can you add cursors to unrelated words or sections of text?

### ISSUE THREAD

**Issue by skamsie** [mg979/vim-visual-multi#148]
I have red through the documentation and the wiki, but I am interested in a particular feature and can't really tell if it can be done with this plugin or not. 

I would like to apply the same edit on words in a buffer that are unrelated between them, and by this I mean they are not the same word, they are not one underneath the other, can't be easily matched by regex, etc. For example, given the text below:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Donec euismod, orci vel venenatis laoreet, lectus justo
scelerisque sem, id commodo diam risus et justo.
Cras dui diam, dignissim sed turpis ac, finibus lobortis nisl.
```

I would like to visually select (or add cursor) to the following words `sit`, `lectus` and `turpis` and then replace them with "foo". How can I do this with vim-visual-multi?

**Comment by MuhammedZakir** [comment]
1. `Ctrl-n` - if the word under cursor is not in existing selection, it will be added:

> `C-n` will select a word with word boundaries, unless pressed on an existing selection. Also note that if you move to a different word with arrow keys and press `C-n` again, a new pattern will be added, and all of them will be searched when pressing `n`.

2. You can select a word or range in *visual mode* and then press `Ctrl-n` to add it.


* Note: There might be other ways to do this.

**Comment by skamsie** [comment]
@MuhammedZakir <C-n> is not really doing what I want. Once I press it, the cursor is now bound to only a couple of movements. What I want to do is, select `sit` on first line, then go on the second line and select `lectus`, then go on the last line and select `turpis`, then run `ciwfoo` and it replaces all these 3 words with `foo`.

**Comment by MuhammedZakir** [comment]
> @MuhammedZakir is not really doing what I want. Once I press it, the cursor is now bound to only a couple of movements. What I want to do is, select `sit` on first line, then go on the second line and select `lectus`, then go on the last line and select `turpis`, then run `ciwfoo` and it replaces all these 3 words with `foo`.

I think you used *hjkl* keys? You can only use arrow keys. From what I understood, text navigation keys (`hjkl`, `w`, `e`, etc.) are used for extending current selection, like *visual mode*. To navigate, you will have to use either arrow keys or search. [1] But, search has it's own limitation, i.e. you can only jump to the first match because VM map `n/N` for it's own use. You can limit search by going down/up some lines (skipping  matches) and also by adding characters after the word you want to go to.

After testing it out, it is indeed a little cumbersome. Is it possible to use `n/N` for search navigation while using VM? That will make selecting text easier.

[1] I have only started using this recently, so I maybe wrong.

**Comment by skamsie** [comment]
@MuhammedZakir thanks, I see it works if I move with just the arrow keys, no need to press Alt / Meta for that.

So the anwser would be, `<C-n>` on the 'sit', move with arrow keys to 'lectus' `<C-n>` again, move with arrow keys to 'turpis' `<C-n>` and then `cfoo`

**Comment by MuhammedZakir** [comment]
> @MuhammedZakir thanks, I see it works if I move with just the arrow keys, no need to press Alt / Meta for that.

Yes, but that would be reeaally tedious. Just think about going down a half page to select some words. If it's somewhere nearby or I can use search to quickly jump there, then fine. Else, I will use `Alt+<keys>`. 
 
> So the anwser would be, `<C-n>` on the 'sit', move with arrow keys to 'lectus' `<C-n>` again, move with arrow keys to 'turpis' `<C-n>` and then `cfoo`

You could also use "search" to go to those words.

**Comment by skamsie** [comment]
@MuhammedZakir It works in this case, but if there are multiple occurences of that word, it does not work as expected.

**Comment by mg979** [comment]
@skamsie read:

    :help vm-add-cursor
    :help vm-toggle-mappings
    :help vm-quick-reference
    :help g:VM_mouse_mappings

**Comment by mg979** [comment]
If you do it often, enabling mouse mappings should be faster than toggling mappings/move/toggle again.

**Comment by skamsie** [comment]
@mg979 Thanks, I understand how it works now, but I find it a bit cumbersome to be honest. I also do not like to use the mouse or arrow keys.

I realise this plugin requires a lot of effort and I think it is pretty awesome, but if you don't mind asking, why was this not implemented in a way that it respects the normal vim movement pattern. For example, cursor is over 'foo', I press `<C-n>`, it is now added to VM. Next I can navigate with `hjkl`, or use `/bar` for searching, and in case I used `/bar` I can now go to next or previous search result with `n` or `N` and in case I find an occurence of 'bar' that I want to add to the selection I can use `<C-n>` on it and so on.

**Comment by mg979** [comment]
Doing `/` and then `<C-N>` works, but `n` and `N` are used by VM by default. You could use `<C-G>/<C-T>` in the search command line to change word, or remap `n` and `N` so that vim mappings are not shadowed.

Personally I do

    let g:VM_maps["Toggle Mappings"]    = '<Space>'

so that toggling mappings is easier, if I need to. And consider that with mappings toggled off, some VM commands work anyway (only buffer mappings are disabled), so you can:

- toggle off mappings with spacebar
- you're free to move around
- add words with `<C-N>` or single cursors with `\\\` or whatever is your mapping to add single cursors
- enable buffer mappings again with spacebar

**Comment by skamsie** [comment]
@mg979 Thank you for the detailed explaination, my question has been answered :). I will close this 'issue' now.

**Comment by mg979** [comment]
Anyway, if you don't like `n` and `N` being taken over by VM, you can use mappings like these:
```
let g:VM_maps["Find Prev"]      = '['
let g:VM_maps["Find Next"]      = ']'
let g:VM_maps["Goto Prev"]      = '{'
let g:VM_maps["Goto Next"]      = '}'
```

For me it's not worth it, but anyway.

**Comment by MuhammedZakir** [comment]
> @skamsie read:
> 
> ```
> :help vm-add-cursor
> :help vm-toggle-mappings
> :help vm-quick-reference
> :help g:VM_mouse_mappings
> ```

Thanks! `Toggle mappings` is what I was looking for. So does that mean we can do it in 2 ways? One, with `Alt` and 2, by toggling? Is `Alt+<key>` VM feature or is it a native command?

> Doing `/` and then `<C-N>` works, but `n` and `N` are used by VM by default. You could use `<C-G>/<C-T>` in the search command line to change word, or remap `n` and `N` so that vim mappings are not shadowed.
>  **--snip--**

I did not know about `<C-g>/<C-t>`. Thanks a lot for this plugin and the shortcuts! :heart:
