### ISSUE TITLE
highlight is not obvious and strange underline

### ISSUE THREAD

**Issue by xyz1001** [mg979/vim-visual-multi#150]
**Describe the issue:**

With my vimrc, highlight of selection is not obvious and unselected words have strange underline.
![image](https://user-images.githubusercontent.com/14332136/101346272-4a399d00-38c3-11eb-9691-9adb3ca03612.png)

The colorsheme of terminal and vim is solarized-dark

**Steps to reproduce**  

1. Install plug
2. select words with `Ctrl-N`
3.

I tried minimal vimrc below and underline also exists.

![image](https://user-images.githubusercontent.com/14332136/101346404-72290080-38c3-11eb-8237-3a67847ee91b.png)

-----

- **Operating System: *Manjaro 20.2* 
- **Vim Version: *VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 17 2020 21:54:53) patch: 1-1704*: 
- **commit SHA/branch*aa66db40e6c765fd6293c69e71b38b6a87dd3a08*:

**Comment by mg979** [comment]
:h visual-multi-highlight

If you don't like the underline:

    :h g:VM_highlight_matches

**Comment by xyz1001** [comment]
Thank you for your reply。But I find it is  a little difficult for me to get the result like `README` after an hour of trying. Could you give me some example?

**Comment by mg979** [comment]
Try a theme first:

    VMTheme <tab>

When you find one that it's ok, put in the vimrc:

    let g:VM_theme = {theme name}

About the underline stuff, the docs are clear I think.

**Comment by xyz1001** [comment]
I got it. Thank you very much.
