### ISSUE TITLE
how to select like MultipleCursorsFind?

### ISSUE THREAD

**Issue by ri-aje** [mg979/vim-visual-multi#151]
**Describe the issue:**
I read all docs under the doc dir but couldn't seem to find this behavior. I use multiple cursors before and MultipleCursorsFind will select all regions matching a regex. how do I do that with visual-multi? I found a few related, but none worked to satisfaction. `Select All Words` doesn't work with regex. `Find with Regex` only select the first match. I searched issue history here, and only found https://github.com/mg979/vim-visual-multi/issues/2 talking about the same request. there was a long discussion there, and in the end, it's claimed `Alt-j` (and `ctrl-d`) does the job, but it doesn't seem working for me. this isn't a bug report, so I will skip the repro steps. thanks.

**Steps to reproduce**  

-----

- **ubuntu 18.04**: 
- **Vim 8.2 patches: 1-1897**: 
- **20a59dd/master**:

**Comment by mg979** [comment]
Maybe `:help :VMSearch`?

**Comment by ri-aje** [comment]
> Maybe `:help :VMSearch`?

that's it. thanks.
