### ISSUE TITLE
"Handle function vm#commands#ctrln[11]..vm#commands#find_under[5]..vm#commands#find_next[13]..<SNR>121_get_region[3]..<SNR>121_get_next Error

### ISSUE THREAD

**Issue by gVimer** [mg979/vim-visual-multi#152]
From
`        silent keepjumps normal! ngny`]
        silent keepjumps normal! NgNy`]
`
To
`        silent! keepjumps normal! ngny`]
`
`  silent! keepjumps normal! NgNy`]
`

**Comment by mg979** [comment]
How do you get this error? Explain better please.

**Comment by mg979** [comment]
Please open a new issue in an understandable way and follow the template, thanks.
