### ISSUE TITLE
[regex search/colemak] extend mode selections

### ISSUE THREAD

**Issue by ri-aje** [mg979/vim-visual-multi#153]
**Describe the issue:**
this isn't bug report, so I will skip the repro steps.

I am trying to find out how to extend visual selection (or extend mode selection). I noticed two scenarios not working intuitively. I would like some pointers if they are doable, and if so, how.
1. once I have extend-mode selection, how do I use keyboard arrow keys to manipulate the selections? `hjkl` works, but the equivalent array keys don't. S-arrow works, but it only supports left and right keys, up and down don't work.
2. how do I use `/` to search and extend-mode to select up to next match?
in both cases, I see the vim cursor moved, but the plugin cursors/extents didn't change. I recall multiple-cursors did support these usages, what's the equivalent in visual-multi? I checked the docs and didn't find what I need. thanks.

**Steps to reproduce**  

1.
2.
3.

-----

- **Operating System**: ubuntu 18.04 
- **Vim Version**: VIM - Vi IMproved 8.2 Included patches: 1-1897 
- **commit SHA/branch**: https://github.com/mg979/vim-visual-multi/commit/c8c8407802d922e80ea174475633e3746e9bddc6

**Comment by mg979** [comment]
1. arrow keys aren't mapped, only `hjkl` work to extend selections. Shift-arrows work because they have a different usage (they can create selections from nothing). `jk` only change line if `multiline` is enabled (mapping is `M`)
2. `/` used that way isn't supported. I never used the other plugin so I can't say, but I find it a bit surprising if that would be possible. It would be difficult (normally) that a `/` match is found after every cursor. If there was some very far away match selections would be messed up.
    - maybe you  are trying to do it on a single cursor, so that you can then extend it and then select similar regions? To do this kind of things, I start VM from visual mode, I select some text (I can use `/` in this case) then do `<C-n>`
    - if instead you want to extend all cursor up to a point using a regex patter (like `f` with regex) read `:h vm-goto-regex`

**Comment by mg979** [comment]
By the way now you can use `g/` to do what you'd normally do with `/`: it extends selections in extend mode, and moves cursors in cursor mode, much like vim `/`. You still need multiline enabled to be able to reach matches in different lines.

Tell me if this is what you were looking for.

**Comment by ri-aje** [comment]
@mg979 thanks. after playing it some more, I realized there is a good reason arrows and `/` aren't mapped, since visual-multi supports adding additional patterns in the middle of visual-multi mode, so some way is needed to move the vim cursor to locate these patterns without affecting vm selections.

I thought this is a continuation of vim-multiple-cursors, since the other plugin announced deprecation and named visual-multi as its replacement. maybe I should work with visual-multi as-is without trying to impose another plugin's workflow on it. in my case I need to clean up highly structured test cases, so when I search for pattern with `/`, there is always a next match on the same line, e.g., I start with
```
Input: values = [1,2,3,4,5], targets = [4,5] Output: 2
Input: values = [1,2,3,4,5,6,7,8,9], targets = [1] Output: 1
Input: values = [2,4,6,8,10,12], targets = [4,8,12] Output: 5
```
and I want to get
```
{{1,2,3,4,5},{4,5}, 2},
{{1,2,3,4,5,6,7,8,9},{1}, 1},
{{2,4,6,8,10,12},{4,8,12}, 5},
```
below is my workflow with visual multi. let me know how to better optimize it.
1. I place cursors on each line beginning, either by `ctrl-down` or `ctrl-n`.
2. I then search for `= ` to identify the end of the first removal group. I didn't know `g/` before, so I had to rely on multiple `f<space>` for the job, or S-right.
3. with `g/= `, I noticed my cursors are placed on the beginning of `= `, so I have to press S-right to have the extent to include the `<space>` char.
4. now I press `x`, and my text becomes
```
|[1,2,3,4,5], targets = [4,5] Output: 2
|[1,2,3,4,5,6,7,8,9], targets = [1] Output: 1
|[2,4,6,8,10,12], targets = [4,8,12] Output: 5
```
the `|` sign marks cursor positions after these operations. I then basically repeat the above steps to take care the remaining groups. the critical step is in step.2. here, my options are `f`, or `g/`, or S-right, but neither is ideally, `f` only works with one char, so I have to jump through multiple matches and pay attention to each one and judge whether it is the terminating condition. `S-right` requires two hands and pressing shift, and is pretty slow in movement anyway. `g/` is twice expensive as `/` and `g` isn't at a great location on keyboard and the extent it constructs only covers the first char in the match, and I have to make additional moves to cover the whole match. here, the cursor rendering is pretty confusing when `cursorline` and `cursorcolumn` is enabled, and I often ended up with missing a char, or removing one more than necessary.

are there more efficient ways to do the removals? the only other alternative I have is to visual select `Input: values = ` in vim in which case establishing the exact selection is efficient, then do `ctrl-n` to mark them all. but this workflow would have to force me exit visual-multi to work on the next ` targets =` group. but `ctrl-n` could be a lengthy process when there are many lines, so ideally I would like to reuse the previous cursor positions, and establish the extent inside visual-multi.

**Comment by ri-aje** [comment]
related to cursor movement, I use non-querty keyboard layout (colemak specially) and made vim mappings (normal and visual) to retain original vim key placement as much as I can. however, visual-multi doesn't seem to honor this mapping, any idea why and how to make it work? e.g., on my keyboard, the physical `l` key gives `i` keycode, so after system translation, pressing `l` is as if I have pressed `i`, which breaks the (physical) `l` key moving vim cursor to the right behavior, so I compensated it with a vim mapping `noremap i l` to keep my fingers on the home row. this worked in normal and visual, but not with visual-multi, which has to take the `i` keycode as-is. can you make visual-multi to have vim "translates" the keycode first? that would make it work with any user defined mappings automatically, so you don't even need `g:VM_custom_motions` for customization, sounds reasonable?

btw, `g:VM_custom_motions` supported charset is too small. in reality with different keyboard layout, once a key is moved/remapped, it pushes the original key into a different location (otherwise, that original key will become inaccessible), which will push another key into a different location, and trigger a chain reaction. eventually the closure set includes pretty much all keys on the keyboard. so I would think it makes better sense to leave this work to vim (and user may set it up once in one place), than making up a specific customization just for visual-multi.

**Comment by mg979** [comment]
I assume you have vim-surround installed. Anyway it's the kind of things where using a macro isn't that different.

In VM it would look like this

![vm](https://user-images.githubusercontent.com/26169924/103180542-abd3a280-4896-11eb-9e68-39dc54dcd4e0.gif)

And I'm just using commands like `f` and `dt`, plus vim-surround commands that you should have installed.

About the colemak thing, I don't really know. Maybe you can check `:h langmap` but I don't know if it will work with VM.

**Comment by ri-aje** [comment]
> I assume you have vim-surround installed. Anyway it's the kind of things where using a macro isn't that different.
> 
> In VM it would look like this
> 
> ![vm](https://user-images.githubusercontent.com/26169924/103180542-abd3a280-4896-11eb-9e68-39dc54dcd4e0.gif)
> 
> And I'm just using commands like `f` and `dt`, plus vim-surround commands that you should have installed.
> 
> About the colemak thing, I don't really know. Maybe you can check `:h langmap` but I don't know if it will work with VM.

thanks. yes, I have vim-surround, though I just mass replace `[]` with `{}` as the last step, so I didn't need surround in this use case. I see your key sequence mostly rely on several vim movements, such as `t[`, which are somewhat messed up in my case, since visual-multi doesn't honor my vim mapping. I guess that's where it breaks for me, since my muscle memory results in unexpected results. I tried `:h langmap` before and it didn't really work well.

am I right that visual-multi creates new modes in vim? so my vim mappings don't apply. `noremap` covers normal, visual and select mode, which is pretty broad and has been working fine with other plugins. if so, can `g:VM_custom_motions` support full keyboard charset?

**Comment by mg979** [comment]
It doesn't support a full charset, but that should be enough. That option doesn't remap keys, it assigns the correspondent plug to a certain key. But it won't work with `d` for example. Try to assign directly keys to plugs using `:h vm-functions`. Like, assign them on _start() and remove them on _end() (they should be `<buffer>` mappings). I would just assign a few (like `d/y/c`) and the rest with `g:VM_custom_motions`. Read the plug names in the plugs.vim file. For `d/y/c` they would be

    <Plug>(VM-Delete)
    <Plug>(VM-Yank)
    <Plug>(VM-c)

You shouldn't remap operator pending mappings, because VM doesn't map those, it parses the input (and you can read it in the command line when you use an operator).

**Comment by mg979** [comment]
Just a final word on this: you can remap all plugs by using g:VM_maps, look in the files `autoload/vm/maps/all.vim` and  `autoload/vm/plugs.vim` to see which are the mappings that you need, if `g:VM_custom_motions` isn't enough.

I think that between `g:VM_maps`, `vm-functions` and related autocommands there are enough means to set up these things.
