### ISSUE TITLE
ctrl-n errors out when no next match

### ISSUE THREAD

**Issue by ri-aje** [mg979/vim-visual-multi#154]
**Describe the issue:**
keep pressing `ctrl-n` to select the next match will eventually exhaust all matches. once that happens, `ctrl-n` gives this error
```
Error detected while processing function vm#commands#ctrln[11]..vm#commands#find_under[5]..vm#commands#find_next[13]..<SNR>27_get_region[3]..<SNR>27_get_next:
line    2:
E385: search hit BOTTOM without match for: int
Press ENTER or type command to continue
```
can you clean it up? it should be pretty obvious there is no next match any more since the cursor won't move.

same behavior goes for `n/N` when there is no next match.

**Steps to reproduce**  

1. type `int<enter>int`. buffer should look like this
```
int
int
```
2. visual select the first `int`, then press `ctrl-n` twice. this will select the second `int` as well.
3. now press `ctrl-n` again, vm will show the error above status bar.

note `nowrapscan` has to be enabled to see this error. use this min repro vimrc.
```
set nocompatible

set nowrapscan
call plug#begin('~/.vim/bundle')
 Plug 'mg979/vim-visual-multi'
call plug#end()
```

looks like same issue as https://github.com/mg979/vim-visual-multi/issues/152.

-----

- **Operating System**: ubuntu 18.04 
- **Vim Version**: VIM - Vi IMproved 8.2 Included patches: 1-1897
- **commit SHA/branch**: https://github.com/mg979/vim-visual-multi/commit/29face82877b1bb05429c9536a6da6f24dde9fa0

**Comment by mg979** [comment]
I'm not changing `wrapscan` setting, that's why you see the error. It's the same error you'd get in vim. Maybe I can make it less intrusive, I'll fix it later.

**Comment by ri-aje** [comment]
> I'm not changing `wrapscan` setting, that's why you see the error. It's the same error you'd get in vim. Maybe I can make it less intrusive, I'll fix it later.

fix works much better. thanks.
yeah, please preserve user `wrapscan` setting as it's a behavioral difference.
