### ISSUE TITLE
Issue with multi-byte characters

### ISSUE THREAD

**Issue by urbainvaes** [mg979/vim-visual-multi#156]
First, thanks again for this absolutely great plugin! :)

My issue occurs with both `vim` and `nvim`. Assume I want to change all the occurences of `φ` by `ψ` in the following file:
```
φ φ φ φ φ φ
```
After selecting all the occurences using `ctrl-n`, and then `c<ctrl-k>q*` (I use the digraph mechanism here),
I obtain the file
```
ψψψψψψ    
```
without spaces between the symbols. Any idea what might cause this? I have the same issue with other special characters, such as `¹` or `∫`.

**Comment by mg979** [comment]
Thanks for reporting, please reopen if it's not fixed.

**Comment by urbainvaes** [comment]
It works now! Thank you very much @mg979 ! :)
