### ISSUE TITLE
Some mappings won't work for me

### ISSUE THREAD

**Issue by Godnyx** [mg979/vim-visual-multi#157]
**Describe the issue:**
I'm using my own keyboard layout and I'm trying to remap HJKL to HTLN and it doesn't seem to work as expected. My config is:

let g:VM_maps = {}
let g:VM_custom_remaps = {'e': 'n', 'E': 'N', 'u': 'q', 't': 'j', 'n': 'l', 'l': 'k'}
let g:VM_default_mappings = 0
let g:VM_mouse_mappings = 1
let g:VM_maps['Find Under']         = '<A-e>'
let g:VM_maps['Find Subword Under'] = '<A-e>'
let g:VM_maps['Select All']         = '<A-a>'
let g:VM_maps['Visual All']         = '<A-a>'

Everything seems to working as expected except 'n' which stills goes to the next instance (just like 'e')

**Steps to reproduce**  
I'm just trying to use it and it doesn't work...

- **Operating System**: Void Linux
- **Vim Version**:NVIM v0.4.4
                                 Build type: Release
- **commit SHA/branch**: Not sure where to find the hash but I used VimPlug and I have the latest possible plugin from master

**Comment by mg979** [comment]
https://github.com/mg979/vim-visual-multi/issues/153#issuecomment-751869640
