### ISSUE TITLE
Add cursors to block of lines selected in visual mode

### ISSUE THREAD

**Issue by FreddieOliveira** [mg979/vim-visual-multi#158]
In terryma/vim-multiple-cursors it was possible to select multiple lines in visual mode and then `Ctrl+n` would add a cursor in every selected line:

https://github.com/terryma/vim-multiple-cursors#add-a-cursor-to-each-line-of-your-visual-selection

How can I do this?

**Comment by mg979** [comment]
`\\c` is the default mappings, see `:h vm-mappings`.

**Comment by FreddieOliveira** [comment]
Thanks, it worked 👍
