### ISSUE TITLE
Cursors invisible on empty lines in cursor mode

### ISSUE THREAD

**Issue by zhixuan-lin** [mg979/vim-visual-multi#159]
**Describe the issue:**

In cursor mode, cursors (except the current one) are invisible on empty lines. I tested the minimal vimrc but this issue still happened.

Not sure if this is a bug or intended behavior. If it is intended, maybe adding an option for making the cursor visible would be better?

Thanks for the nice plugin BTW :)

**Steps to reproduce**  

1. Copy this file. Put the cursor on line 1.
```
abc

abc

abc

end
```
2. \<C-n\> \<C-n\> \<C-n\> \<Tab\> j
3. Cursors on lines 2 and 4 would be invisible, which is unexpected. Only the current cursor (line 6) is visible.
4. Enter insert mode, all three cursors would be visible, though.

-----

- **Operating System**: macOS Mojave 10.14.6
- **Vim Version**: NVIM v0.4.3 
- **commit SHA/branch**: 4ca5978 (current master)

**Comment by mg979** [comment]
It's a limitation more than a bug, because vim `matchaddpos()` doesn't work with empty lines.

**Comment by mg979** [comment]
It should be fixed.

**Comment by zhixuan-lin** [comment]
Awesome, thanks a lot!
