### ISSUE TITLE
Any way to make `Ctrl-N` case sensitive ?

### ISSUE THREAD

**Issue by aurels** [mg979/vim-visual-multi#160]
I've read the README and could not find if it's possible or not. I'd like `Ctrl-N` to match words with case sensitivity.

My vimrc ignores case, if it's related : 
`:set ignorecase => noignorecase`

Thanks.

**Comment by mg979** [comment]
Thanks for reporting, I thought it was already respecting the case setting, but it wasn't, it should be fixed now. If you are using a previous session you might need to `unlet g:VM_case_setting`, because it could be stored in the session file.

**Comment by aurels** [comment]
Thanks, it works as expected now :-)

**Comment by jackcogdill** [comment]
For anyone who finds this in the future: you can use "find with regex" (`\\/`) and then prefix the search with an explicit case option like `\c` or `\C` (ignore or match case, respectively).
