### ISSUE TITLE
pasting with multi cursor is using " register rather than the * or +

### ISSUE THREAD

**Issue by JoseConseco** [mg979/vim-visual-multi#167]
**Describe the issue:**
Paste with with  visual multi seems to be using " register  which gives unexpected results when pasting content from external apps (vims normally seems to be using + reg)

Registers when I copied something in external app (affects * and + ): 
![image](https://user-images.githubusercontent.com/13521338/115961116-470f1880-a515-11eb-998e-3876553b1631.png)

Reg on yank inside neovim (+ and " are affected):
![image](https://user-images.githubusercontent.com/13521338/115961154-7756b700-a515-11eb-885c-15caaed741bf.png)

- `*`  affected by external copy
- `+`  affected by yoink inside vim and external copy
- `"`   afffected by yoint inside vim

Default paste in vim is using +  register  - thus always gives expected result (because + reg is affected by both yoink and external copy)

**Steps to reproduce**  

1. Copy something from external app
2. in vim use <c-n> to select eg. 2 words in adjacent lines - one after another 
3. Paste when in visual multi mode - externally copied text will be ignored (and " reg seems to be used) . But normal paste (without using visual-multi) will work ok (it will paste external text into vim)

- **Manajro**
- **Vim Version**: latest Neovim
- **commit SHA/branch**: latest build

I hope someone can confirm this.

**Comment by mg979** [comment]
VM doesn't use the `clipboard` option (it is reset in VM), because of problems I had with it in the past (in neovim specifically). You can use the `+` register, but you must use it explicitely as with `"+p` (it works for me).

**Comment by JoseConseco** [comment]
Ok, thanks for info. Closing this then.
