### ISSUE TITLE
How to yank multiple cursors?

### ISSUE THREAD

**Issue by simondrake** [mg979/vim-visual-multi#168]
**Describe the issue:**

Take the following example:

```
asggsgsdgsg-startword
dsds-startlongerword
gd-startareallylongword
gggsdgsdgwewettwetwetwet-startareallyreallylongword
sdgsdgsgavvxgsdgsg-startonemorereallylongwordfordemonstrationpurposes
```

I want to select everything from `-start` to the end of the line and yank it into my clipboard (which uses `unnames,unnnamesplus` to also go into my OS clipboard).

**Steps to reproduce**  

1. Select `-start` on line 1 (`<C-v>`)
2. Select each occurence using `n` x 4
3. Move to extend mode (Tab)
4. Enter visual mode (`v`)
5. Move to end of line (`$`)
6. Yank (`y`)
7. Nothing is copied to the clipboard

-----
- **Operating System**: Mac OS 10.15
- **Vim Version**: 
```
NVIM v0.4.4
Build type: Release
```
- **commit SHA/branch**: master

**Comment by mg979** [comment]
Can you update and try again? You should do `"+y` by the way, simply `y` doesn't work, see my answer to #167.

**Comment by simondrake** [comment]
Perfect, that works. 

Note: It doesn't work if I'm in extend mode, so if I leave out that step and use `"+y` it works fine. 

Thanks for the response, fix, and for maintaining this project.

**Comment by mg979** [comment]
The commit I pushed should fix it for extend mode too.

**Comment by simondrake** [comment]
It's entirely possible I'm doing something wrong, but it doesn't seem to work in extend mode for me.

**Comment by mg979** [comment]
By _extend mode_ I mean VM extend mode. Before, doing `<c-n>"+y` wouldn't work, now it should work, at least it works for me. I'm on Windows atm.

**Comment by simondrake** [comment]
I wouldn't waste any more time, I've literally just moved over to `vim-visual-multi` from `vim-multiple-cursors` so there's a definite possibility I'm just not fully understanding the terminology.

Appreciate the time and replies!

**Comment by simondrake** [comment]
But, just in case you are curious, I run the same steps as the issue description and it doesn't work (at least not the way I'm trying to do it)...

```
asggsgsdgsg-startword
dsds-startlongerword
gd-startareallylongword
gggsdgsdgwewettwetwetwet-startareallyreallylongword
sdgsdgsgavvxgsdgsg-startonemorereallylongwordfordemonstrationpurposes
```

I want to select everything from -start to the end of the line and yank it into my clipboard (which uses unnames,unnnamesplus to also go into my OS clipboard).

Steps to reproduce

* Select -start on line 1 (`<C-v>`)
* Select each occurence using `n` x 4
* Move to extend mode (Tab)
* Enter visual mode (`v`)
* Move to end of line (`$`)
* Yank (`y"+`)
* Only `-start` is copied to the clipboard

Here's a video as well:

https://user-images.githubusercontent.com/62928647/118152392-8b068680-b40c-11eb-87e9-74dc15707740.mp4

**Comment by mg979** [comment]
That doesn't work for a different reason. When VM exits it restores the registers as they were. You are yanking something in visual mode while you're still in VM. Then you exit VM and that yank is lost. Anyway I don't see good reasons why you should yank visual selections while staying in VM. If you want to yank multiple selections you can, but you don't enter visual mode to do that, visual mode in VM has very limited uses (like selecting subword patterns).

**Comment by simondrake** [comment]
> That doesn't work for a different reason.

 I assumed it was a case of [PICNIC](https://en.wiktionary.org/wiki/PICNIC). 

> When VM exits it restores the registers as they were.

Now for the stupid/obvious question - `VM` in this context means `visual-multi` (i.e. this plugin), right? Or have I missed something? 

> You are yanking something in visual mode while you're still in VM. Then you exit VM and that yank is lost.

That makes sense.

> Anyway I don't see good reasons why you should yank visual selections while staying in VM. If you want to yank multiple selections you can, but you don't enter visual mode to do that, visual mode in VM has very limited uses (like selecting subword patterns).

That's fair. It works perfectly fine in non-extend mode, so I have exactly what I need. 


Appreciate the time, the replies, and the effort involved in creating the plugin.
