### ISSUE TITLE
Question - Change selected words

### ISSUE THREAD

**Issue by midnio** [mg979/vim-visual-multi#17]
I tried to press `c` to change selected regions, but I cant have done it. Is there a way to do it?

**Comment by mg979** [comment]
It doesn't work? Are you pressing `c` in cursor mode or extend mode? How do you start VM?

**Comment by midnio** [comment]
I just pressed ctrl-d then pressed c. It doesnt work actually. It asks to change *case.

**Comment by midnio** [comment]
Maybe the reason is because of my leader is space. Maybe?

**Comment by midnio** [comment]
yeah, the link you showed is right.

**Comment by mg979** [comment]
When space is the leader, inside VM it is set to `\`. Space won't work as leader inside VM, but it doesn't mean you have to change it. I tested it with space as leader and `c` worked. `c` has nothing to do with `leader` so it should work, but try just in case:

`let g:mapleader = "\\"`

**Comment by midnio** [comment]
I changed the leader to space and it worked.

**Comment by midnio** [comment]
Then I can use \ too. Thanks.

**Comment by mg979** [comment]
How, *to* space? What was it before? What leader doesn't work?

**Comment by mg979** [comment]
Ok I could reproduce it, so there's something to fix.

**Comment by midnio** [comment]
It's still broken.

**Comment by mg979** [comment]
How is it broken? Can you give details, please? I tested both:

(mapleader backspace, what I use)
`let g:mapleader = "\\"`

(mapleader space)
`let g:mapleader = "\<space>"`

I tested them with a minimal vimrc too and they're working.

**Comment by midnio** [comment]
let g:mapleader = "\<space>" isnt working exactly.

**Comment by mg979** [comment]
> let g:mapleader = "<space>" isnt working exactly.

You have to escape `<`, you have to write

`let g:mapleader = "\<space>"`

not

`let g:mapleader = "<space>"`

**Comment by midnio** [comment]
I know this, i already added \ to escape.

**Comment by mg979** [comment]
Did you update to last master/test? Here it's working, I have no idea what else could be.

Also, I'm talking about the 'c' command. If you use 'space' as leader, it won't work inside VM because space is used to toggle mappings. Read [here](https://github.com/mg979/vim-visual-multi/wiki/M.-Mappings#leader) if this is the case.

**Comment by midnio** [comment]
So is this not possible to use space as leader :cry:

**Comment by mg979** [comment]
It is possible. Just not inside VM. When you exit VM, leader works as usual. You're not supposed to stay in VM mode for longer than you need. Also, it has its own commands and your remappings can't work inside of it. If you must run normal commands at cursors etc, there are specific commands for that.

**Comment by midnio** [comment]
Then, cant we remap VM's space key with something else?

**Comment by mg979** [comment]
> Then, cant we remap VM's space key with something else?

For now it's not possible. `Space`, `Tab`, `Enter` and `Escape` are basic mappings and not customizable.

You can remap the VM leader, but not to space:
```
let g:VM_leader = ","
```
But you can use `space` as leader outside VM, so what's the problem? This only concerns some special commands inside VM, such as alignment (`<leader>a`), transpose  (`<leader>t`) and some others.

I repeat that you are not supposed to use your leader mappings inside VM, so it doesn't matter what your leader is.

If your leader isn't `space`, that leader will be used by VM, but if it's `space`, VM will use another one, default is `\`, but you can set another one (not space).

**Comment by midnio** [comment]
I solved it, thank you so much :heart:
