### ISSUE TITLE
when setting vim.highlight.on_yank(), VM triggers it when moving in Extend Mode

### ISSUE THREAD

**Issue by PascalZh** [mg979/vim-visual-multi#170]
**Describe the issue:**
When setting `au TextYankPost * silent! lua vim.highlight.on_yank {timeout=150}` according to `lua.txt`, VM triggers it when moving in Extend Mode. This is some kind of disturbing.

-----

**Comment by mg979** [comment]
You should rewrite the autocommand so that it checks if it's inside VM. There was a similar issue in the past, look for it. Maybe I even mentioned it in `:help vm-troubleshooting`, I seem to remember.

**Comment by PascalZh** [comment]
@mg979 thanks a lot!
I work around by the following codes, may be helpful for others:
Notice: `MUtils` is a global registered with `_G.MUtils = {}`.
```lua
function MUtils.highlight.on_yank(args)
  if (vim.b.visual_multi == nil) then
    vim.highlight.on_yank(args)
  end
end
```
