### ISSUE TITLE
Conflicting issues when used with other plug-ins

### ISSUE THREAD

**Issue by onlycalm** [mg979/vim-visual-multi#172]
**Describe the issue:**
There is a conflict between Vim-visual-multi and the following plug-ins : auto-pairs, coc.nvim
Maybe it's not the Vim-Visual-multi problem, but I don't know who to turn to.  These are all great plugins, and I want to use them all together.
I would be very grateful if you could give me some advice. 

**Steps to reproduce**  

Vim-visual-multi and auto-pairs conflict: 
1. Install the two plug-ins with the default configuration.
2. Open a file and enter multi-cursor mode.

![2021-06-20_12-51-36](https://user-images.githubusercontent.com/48640489/122662599-cee86a80-d1c6-11eb-88a5-91526d5101a7.gif)

The high probability results in abnormal functioning of auto-pairs.

```VMDebug
b5: Overwritten imap: <CR> (I Return)  ->  <CR><SID>AutoPairsReturn
b5: Overwritten imap: <BS> (I BS)  ->  <C-R>=AutoPairsDelete()<CR>
```

Vim-visual-multi and coc.nvim conflict: 
1. Install the two plug-ins with the default configuration.
2. Open a file into multi-cursor mode and press the backspace key.

![2021-06-20_13-22-18](https://user-images.githubusercontent.com/48640489/122663222-69e34380-d1cb-11eb-97bb-822e8c63f893.gif)

When the COC detects a syntax error or warning in the file, using backspace in multi-cursor mode will cause an exception.  

-----

- **Operating System**: 
- **Vim Version**: 
- **commit SHA/branch**: 
Windows 10. WSL Ubuntu 20.04 LTS.
VIM8.1

**Comment by mg979** [comment]
1. Issue with CR has been discussed, look for it in issues.
2. about autopairs, I tried to make it ccmpatible but maybe I didn't succeed. It uses buffer mappings for something that wouldn't need buffer mappings (imho), maybe you can contact autopairs author and ask if he's interested in making the plugins compatible because I can't fix this kind of issues on my part. Autopairs should be aware of VM to be compatible.

**Comment by mg979** [comment]
About coc issue, I'm not sure. If there is a more general problem that is reproducible with all plugins (or with nvim lsp in similar situations, for example), I may look into it, but if it's a coc.nvim specific thing honestly I don't care.

**Comment by onlycalm** [comment]
I've fed back the questions to the author of auto-pairs. I used other LSP plug-in tests (ALE), and there was no exception. It seems that this problem is only related to coc. I try to feed this back to the COC authors.

Thanks!

**Comment by LunarWatcher** [comment]
For the record, the original auto-pair author hasn't been online in a couple years (https://github.com/jiangmiao/auto-pairs/issues/309) -- and based on the pattern, they're probably not gonna come back, at least any time soon.

That being said, this is vim-visual-multi's fault. Some update is now causing errors. It doesn't have anything to do with keybind overrides, though -- those weren't an error in the earlier version I had installed, anyway. While testing, I couldn't repro with my plugin. Installed jiangmiao and updated everything, reproduced, and thought it had always been broken. Rolled back to my auto-pairs and it now broke, so it's definitely something related to vim-visual-multi.

Gonna have to look into this though (I'm maintaining [a fork](https://github.com/LunarWatcher/auto-pairs/) of auto-pairs -- I assume there's some plugin config that can be done for compatibility now too), but it really depends on what's classified as an error now. `:VMDebug` doesn't really give any useful information on what's actually going wrong.

**Comment by onlycalm** [comment]
![2021-06-20_18-27-29](https://user-images.githubusercontent.com/48640489/122671651-4e436180-d1fa-11eb-827e-8702b4cc4ae8.gif)

Here's more information.
Press `d` in multi cursor mode to get an error message.

**Comment by mg979** [comment]
@onlycalm that error looks like #75, you should either update vim or use nvim.

@LunarWatcher I don't know what to say, other than this: plugins can be made easily compatible with VM, they only need a command to be disabled and one to be reenabled. Autopairs has these commands, but they don't reset `<cr>` and `<bs>`, so VM overwrites them anyway. It's not something I can fix on my part, it's autopairs commands that are broken (imho).

**Comment by onlycalm** [comment]
@mg979 
For the second question.
Like you say. I updated VIM8.1 to VIM8.2 and it worked fine. Thanks for your help.

**Comment by chancez** [comment]
I have the same issue with a different autopairs plugin: `windwp/nvim-autopairs`. It sounds like toggling the plugins keycaps is what's needed when the VM starts. How does one go about that?

**Comment by ronandalton** [comment]
I just wanted to share my solution to the conflict with the `windwp/nvim-autopairs` plugin. This should allow <BS> to continue to work for both plugins:
```lua
return {
  'mg979/vim-visual-multi',
  init = function()
    -- Hack around issue with conflicting insert mode <BS> mapping
    -- between this plugin and nvim-autopairs
    vim.api.nvim_create_autocmd('User', {
      pattern = 'visual_multi_start',
      callback = function()
        vim.keymap.del('i', '<BS>', { buffer = 0 })
      end,
    })
    vim.api.nvim_create_autocmd('User', {
      pattern = 'visual_multi_exit',
      callback = function()
        require('nvim-autopairs').force_attach()
      end,
    })
  end,
}
```

**Comment by ulises-castro** [comment]
> I just wanted to share my solution to the conflict with the `windwp/nvim-autopairs` plugin. This should allow backspace to continue to work for both plugins and get rid of the warning:
> 
> ```lua
> -- lazy.nvim plugin spec
> return {
>   'mg979/vim-visual-multi',
>   init = function()
>     -- Hack around issue with conflicting insert mode <BS> mapping
>     -- between this plugin and nvim-autopairs
>     vim.api.nvim_create_autocmd('User', {
>       pattern = 'visual_multi_start',
>       callback = function()
>         pcall(vim.keymap.del, 'i', '<BS>', { buffer = 0 })
>       end,
>     })
>     vim.api.nvim_create_autocmd('User', {
>       pattern = 'visual_multi_exit',
>       callback = function()
>         require('nvim-autopairs').force_attach()
>       end,
>     })
>   end,
> }
> ```

Thank you, this solve my problem when I was working on TSX files.

**Comment by kohane27** [comment]
Or we could disable `backspace` being handled by `nvim-autopairs`:

```lua
return {
  "windwp/nvim-autopairs",
  opts = {
    map_bs = false,
    map_c_h = false, -- map <C-h> key to delete a pair
    map_c_w = false, -- map <C-w> to delete a pair
  },
}
```
