### ISSUE TITLE
select all occurences under cursor with <C-D>

### ISSUE THREAD

**Issue by alexzanderr** [mg979/vim-visual-multi#173]
**Describe the issue:**

**Steps to reproduce**  

1.
2.
3.

-----

- **Operating System**: 
- **Vim Version**: 
- **commit SHA/branch**:

**Comment by farzadmf** [comment]
@mg979 I think you closed this issue because it wasn't complete, but I was wondering about the same thing: is there a way to select _all_ occurrences of something without having to go through each one by one (doing `ctrl+n` and then `n` to go through each one to add them to the selection)

**Comment by alexzanderr** [comment]
i solved the problem myself.
here's the solution:
```vimL
" select all occurences in of that selection
nmap <C-D> <Plug>(VM-Select-All)
imap <C-D> <ESC><Plug>(VM-Select-All)
vmap <C-D> <ESC><Plug>(VM-Select-All)
```
let the issue be closed.

**Comment by farzadmf** [comment]
Oh nice, thank you @alexzanderr

**Comment by alexzanderr** [comment]
my pleasure, @farzadmf.

**Comment by alexzanderr** [comment]
for people who want to see other people settings here my configuration on `vim-visual-multi`:

```vimL
" vim visual multi
" https://github.com/mg979/vim-visual-multi
"
"
" 
let g:VM_mouse_mappings = 1
" nmap   <C-LeftMouse>         <Plug>(VM-Mouse-Cursor)
nmap   <C-LeftMouse>         <Plug>(VM-Mouse-Word)
" nmap   <C-S-LeftMouse>      <Plug>(VM-Mouse-Column)

" select all occurences in of that selection
nmap <C-e> <Plug>(VM-Select-All)
imap <C-e> <ESC><Plug>(VM-Select-All)
vmap <C-e> <ESC><Plug>(VM-Select-All)



" check this
" https://github.com/mg979/vim-visual-multi/blob/master/autoload/vm/maps/all.vim
"
"
let g:VM_maps = {}
" new cursor down
let g:VM_maps["Add Cursor Down"] = '<S-Down>'
" new cursor up
let g:VM_maps["Add Cursor Up"] = '<S-Up>'
" new cursor at cursor location
let g:VM_maps["Add Cursor At Pos"] = '<space><CR>'


" in order to cancel S-Left selection
" go in nvim/plugged/visualmulti/autoload/nv/maps/maps.vim
" line 60
" and comment these
" let maps["Select l"][0]              = '<S-Right>'
" let maps["Select l"][0]              = ''
" let maps["Select h"][0]              = '<S-Left>'
" let maps["Select h"][0]              = ''
```

**Comment by farzadmf** [comment]
@alexzanderr  Just one thing: is there a way to select occurrences of the selection in visual mode? I see in your `vmap` you're `<ESC>`ing first, so I think it won't take into consideration what you have selected and it will always select the entire word under the cursor

**Comment by alexzanderr** [comment]
yes, thats true. it will ignore selection and expand to `cword`.
btw, do you wanna chat about this problem? because i really want to fix this

**Comment by farzadmf** [comment]
I didn't have discord, but I just created a server :stuck_out_tongue:: [link](https://discord.gg/ANYJvu7x) (hopefully I did it right)

**Comment by Xaelias** [comment]
> yes, thats true. it will ignore selection and expand to `cword`.
> 
> btw, do you wanna chat about this problem? (do you, @farzadmf have discord or something) because i really want to fix this

Hey. Sorry to resurrect this, but what would the way to do say "select a few words or a while line and select all occurrences of that"?
Thx

**Comment by farzadmf** [comment]
Hey @Xaelias , I searched my config and I think the setting that worked for me was this:
```viml
let g:VM_maps = {}
let g:VM_maps["Visual All"] = '<M-D>'
let g:VM_maps["Select All"] = '<M-D>'
```

**Comment by Xaelias** [comment]
> Hey @Xaelias , I searched my config and I think the setting that worked for me was this:
> 
> ```viml
> 
> let g:VM_maps = {}
> 
> let g:VM_maps["Visual All"] = '<M-D>'
> 
> let g:VM_maps["Select All"] = '<M-D>'
> 
> ```

I just did a quick test that seem to be working awesome thanks!
