### ISSUE TITLE
How do I make extend mode yank default to "+y?

### ISSUE THREAD

**Issue by rcywongaa** [mg979/vim-visual-multi#174]
I tried the following but it didn't work
```
autocmd User visual_multi_mappings nmap y "+y
autocmd User visual_multi_mappings nmap <buffer> y "+y   # this causes vim to freeze with 100% CPU usage
```

**Comment by mg979** [comment]
Right now you can't. Try:

    autocmd User visual_multi_mappings nmap <buffer> <leader>y "+y

Currently clipboard options aren't supported. Maybe in the future, maybe not.
