### ISSUE TITLE
Suggestion: binding to convert a visual block selection into multiple cursor's 

### ISSUE THREAD

**Issue by IndianBoy42** [mg979/vim-visual-multi#176]
I think this would make the plug in integrate a bit better into the normal vim workflows 

In fact, for a bit more inspiration i would look at kakoune and how it handles multi cursor's. There's a lot of cool features there, including one that allows you to take a selection and split it into multiple selections each with their own cursor, according to arbitrary patterns. 

There is also add the next word as a new selection with its own cursor

**Comment by mg979** [comment]
You can do all that in VM. Read the docs.

    :h vm-visual-mode
    :h vm-subtract-pattern
