### ISSUE TITLE
Arrow keys don't work as expected when multiple selections active

### ISSUE THREAD

**Issue by pragdave** [mg979/vim-visual-multi#177]
**Describe the issue:**

Arrow keys don't work as expected when multiple selections active

**Steps to reproduce**  

* select a word with ^N
* select next occurrence with n
* using h/l  moves the cursors in *both* selections
* using left and right cursor keys, and only the cursor in the most recent selection's cursor moves

Verified using minimal .rc

- **Mac OS 11.4**: 
- **NVIM v0.6.0-dev+1-g62d67de59/Build type: Release**: 
- **f994695813ebaecc9e37c7ea216c65d9cd659767**:

**Comment by mg979** [comment]
It's intentional (and written somewhere in the documentation). I'm not remapping the whole keyboard.

**Comment by pragdave** [comment]
Fair 'nuf.

Back to vim-multiple-cursors I guess.

**Comment by ChillerDragon** [comment]
@mg979 what is the intention behind it?

And could you maybe add a section to the README.md on how to enable arrow key navigation support.

**Comment by ChillerDragon** [comment]
> ```
> nmap <buffer> <left> h
> ...
> ```



Wonderful that is exactly what I was looking for! Works like a charm!
Thanks @mg979  :heart:
