### ISSUE TITLE
Issue with remapping `d` to blackhole

### ISSUE THREAD

**Issue by Shatur** [mg979/vim-visual-multi#178]
**Describe the issue:**

The plugin behaves wrong If I remap d to blackhole (`_`).

**Steps to reproduce**

Let's consider the following text:

```
vim.g.VM_mouse_mappings = true
vim.g.VM_show_warnings = false
```

1.  Put cursor on each line.
2. `fV` <-- Jump to `V`
3. `yE`
4. `p` <-- Works as expected
5. `u` <-- To undo
6. `b`
7. `dE`
8. `p`  <-- Pastes two lines on each line.

I would expect that `dE` just removes all text without changing any register.

-----
- **Operating System**:  Archlinux
- **Neovim Version**: 0.5
- **commit SHA/branch**: f994695813ebaecc9e37c7ea216c65d9cd659767 (latest commit at the time of writing).

**Comment by mg979** [comment]
https://github.com/mg979/vim-visual-multi/issues/95?

**Comment by Shatur** [comment]
> #95?

@mg979 Thanks, I set `VM_recursive_operations_at_cursors` to `false` and now `d` is cut. I'm okay with this behavior, but can I use a black hole instead and map `m` for actual cut for this plugin?

**Comment by mg979** [comment]
I'm not a fan of complicated behaviours, I'll see if it can be solved in some simpler manner. I don't like this option either and totally forgot about it. Right now it's how things are though.

**Comment by mg979** [comment]
I should have fixed a bug related to this, now you should be able to use `_` register in mappings without setting that option.

**Comment by Shatur** [comment]
> I should have fixed a bug related to this, now you should be able to use _ register in mappings without setting that option.

Awesome, I removed this option and now it works as expected.
I also mapped `m` to `d` (cut). Can I somehow make my `m` mapping works?

**Comment by mg979** [comment]
Read the mappings faq for that, it's possible but cumbersome. Not explaining stuff that it's in the docs sorry.

**Comment by Shatur** [comment]
> Read the mappings faq for that, it's possible but cumbersome. Not explaining stuff that it's in the docs sorry.

Sorry, I should have phrased my question more precisely.
I tried to use `let g:VM_custom_remaps = {'m': 'd'}`. And `m` behaves like `d`. But it behaves like my `d` that removes to black hole, but I trying to achieve "cut" with this key. Is this possible?

**Comment by mg979** [comment]
I don't know because `_` causes problems in recursive mappings, as I wrote in #95. If it can work, it's with the mappings autocommand. If it doesn't work, maybe it can't work.

**Comment by Shatur** [comment]
> I don't know because _ causes problems in recursive mappings, as I wrote in #95.

Okay, the last question. If I set `VM_recursive_operations_at_cursors` to 0, then `d` behaves like cut. Is this expected?

**Comment by mg979** [comment]
Yes because your `d` mapping is then ignored.
