### ISSUE TITLE
ctrl-n on visual selection overrides "+ and "* when having clipboard=unnamedplus set

### ISSUE THREAD

**Issue by sblask** [mg979/vim-visual-multi#179]
**Describe the issue:**

According to https://github.com/mg979/vim-visual-multi/issues/167 `"+p` should work, but for me sometimes it did and sometimes it didn't until I figured out why: if you have your cursor on a word and press `ctrl-n`, the word gets selected and `"+p` pastes the right thing, but if you make a visual selection, press `ctrl-n` and then `"+p` it doesn't (and it seems like nothing is being done). Turns out that when you press `ctrl-n` in visual mode `"+` and `"*` get overridden by the current selection.

Minimal vim config:

```
source ~/.vim/autoload/plug.vim
call plug#begin('~/.vim/plugged')
    Plug 'mg979/vim-visual-multi'
call plug#end()
set clipboard=unnamedplus
```

Removing the last line fixes the problem, but I want to keep it.

Sample file:

```
foo
foo
foo
```

**Steps to reproduce**  

1. `viw`
2. `ctrl-n`
3. `:registers`

-----

- **Operating System**: Mac OS 10.5
- **Vim Version**:  NVIM v0.5.0 Build type: Release
- **commit SHA/branch**: 46c082aad84fd83c3c3d962c65afa800c2c33d85/master

**Comment by mg979** [comment]
Can you test now? Please reopen if it's not fixed.

**Comment by sblask** [comment]
Works now, thank you so much!

**Comment by rafaeldelboni** [comment]
Hi good day, after this change now I'm having the following error:
```
Error detected while processing function <SNR>22_Visual[7]..provider#clipboard#Call[6]..291:
line    8:
E691: Can only compare List with List
Press ENTER or type command to continue
Error detected while processing function <SNR>22_Visual[7]..provider#clipboard#Call[6]..291:
line    8:
E15: Invalid expression: match(&clipboard, '\v(unnamed|unnamedplus)') >= 0 && get(s:selections[a:reg].data, 0, []) == clipboard_data
Press ENTER or type command to continue
Error detected while processing function <SNR>22_Visual:
line    7:
clipboard: provider returned invalid data
Press ENTER or type command to continue
Error detected while processing function <SNR>22_Visual:
line    7:
E171: Missing :endif
```

The minimal config is exactly the same as this issue, but you need to ctrl+n before copy anything from vim to your clipboard.

If I force Plug to use the commit before this change the error doesn't appears:
`Plug 'mg979/vim-visual-multi', {'commit': '46c082aad84fd83c3c3d962c65afa800c2c33d85'}`

**Comment by mg979** [comment]
> but you need to ctrl+n before copy anything from vim to your clipboard.

I'm not understanding this... And I can't reproduce in Linux. Can you please open a new issue with precise reproduction steps? Thanks.

**Comment by ranelpadon** [comment]
Thanks for this. Had a similar issue with visual selection + VM. Glad that simply updating the plugin fixed it. Confirmed working on Mac OS - Mojave.
