### ISSUE TITLE
No text in startup

### ISSUE THREAD

**Issue by midnio** [mg979/vim-visual-multi#18]
This can be a little bit dumb question by me, sorry but I like the default startup screen of vim. When i added this plugin, I got a screen like this:

![image](https://user-images.githubusercontent.com/36359066/45262131-5e0ea400-b419-11e8-9584-8e9e53f2b110.png)

But when I remove the plugin, I got the screen that I want:

![image](https://user-images.githubusercontent.com/36359066/45262139-7f6f9000-b419-11e8-9f0b-283c3a4ff494.png)

Is there a way to get second screen without removing the plugin?

**Comment by mg979** [comment]
This must be because of a change I made recently, I'll make it optional.

**Comment by midnio** [comment]
sure i'll test it now.

**Comment by midnio** [comment]
It works fine, merge it.

**Comment by mg979** [comment]
Thanks, I updated master. Btw could you make `c` work(https://github.com/mg979/vim-visual-multi/issues/17)?
