### ISSUE TITLE
Yank inside regions

### ISSUE THREAD

**Issue by eyalk5** [mg979/vim-visual-multi#184]
**Describe the issue:**

I want to be able to copy at once all the content in all the selected cells. 

I am not sure if it is a real issue. I saw that after I do twice ctrl-n and y , I get the contents of both cells yanked.

Whereas , after selecting multiple cells using `saw` from normal , doing then `y` did nothing. 
I actually did `y` , esc , opened new tab and paste. 
is it related that I have `clipboard+=unnamedplus`

Thanks.

-----

- **Operating System**: linux 
- **Vim Version**: 5.0
- **commit SHA/branch**: uptodate

**Comment by mg979** [comment]
It works for me, I can't reproduce, try with minimal vimrc.
