### ISSUE TITLE
[feature] Add support for smartinput

### ISSUE THREAD

**Issue by Freed-Wu** [mg979/vim-visual-multi#185]
```
Some plugins have built-in compatibility:

-   jiangmiao/auto-pairs
-   AndrewRadev/tagalong.vim
-   dyng/ctrlsf.vim
-   Shougo/deoplete.nvim
-   ncmw/ncm2
```

<https://github.com/kana/vim-smartinput> is an alternative for jiangmiao/auto-pairs. It provides some functions for user to customize.

**Comment by mg979** [comment]
https://github.com/mg979/vim-visual-multi/issues/172#issuecomment-864557105

Seems nice but it doesn't have a way to be switched off temporarily, that is needed for compatibility. You could ask @kana to add a `when` rule that checks if a condition is met, or insert the normal key, or a command to toggle the feature on and off.

**Comment by Freed-Wu** [comment]
I notice <https://github.com/mg979/vim-smartinput> seems to fix some bugs of kana's plugin (e.g. command map). Can it support vim-visual-multi?

**Comment by mg979** [comment]
Working now?

**Comment by Freed-Wu** [comment]
No. Now, press `(` still get `(` not `()<Left>`.

**Comment by mg979** [comment]
By compatibility I actually meant to disable properly, not to have pairing in VM, so it should be ok.

**Comment by Freed-Wu** [comment]
How to enable it? I cannot found any text about smartinput in vim-help.txt.
