### ISSUE TITLE
Issue when remapping to O (Other End/Invert Direction)

### ISSUE THREAD

**Issue by ranelpadon** [mg979/vim-visual-multi#187]
**Describe the issue:**
I use a Colemak keyboard layout, so I remap most of the default Vim keys. For example, I have these mappings which works as intended. I use these mappings since `a`/`A` and `o`/`O` are the farthest letters in the Colemak home row, making them intuitive for the "prepend" and "append" behaviors of `i`/`I` and `a`/`A`:
```vim
nnoremap a i
nnoremap A I
nnoremap o a
nnoremap O A
```

With those mappings, all of them works as intended when in the `vim-visual-multi` mode, **except** the `O` which seems to obey the Visual Block's **Other** end behavior (I think it's the `Invert Direction` command also in your plugin which is bound to `o`).

So, I tried to force the mappings, but `O` still didn't work:
``` vim
let g:VM_maps = {}
let g:VM_maps['i'] = 'a'
let g:VM_maps['I'] = 'A'
let g:VM_maps['a'] = 'o'
let g:VM_maps['A'] = 'O'
```
and even un-mapping some of the related mappings:
```vim
let g:VM_maps['Invert Direction'] = ''
let g:VM_maps['o'] = ''
let g:VM_maps['O'] = ''
```

Shuffling the mappings work though, although it's not what I need:
```vim
let g:VM_maps['i'] = 'o'
let g:VM_maps['I'] = 'O'
let g:VM_maps['a'] = 'a'
let g:VM_maps['A'] = 'A'
```

**Expectation**
`O` should move the cursor/selection at the end of the line, just like the default `A` behavior. The workaround is to hit `$` then `a` which moves the cursor at the end and enter the append mode. But this is not ideal due to extra keystroke needed.

**Environment**
- **Operating System**: Mac OS 10.14.6 (Mojave)
- **Vim Version**: NVIM v0.6.0-dev+nightly-430-gc642f3ac2 / Build type: Release

BTW, thanks for this awesome plugin. It's one of my favorites since I love the multi-cursor even in VS Code/PyCharm before. :)

**Comment by mg979** [comment]
This should work:

    let g:VM_custom_remaps = {'o': 'a', 'O': 'A'}

**Comment by mg979** [comment]
Ok this works:

```
let g:VM_maps['i'] = 'a'
let g:VM_maps['I'] = 'A'
let g:VM_maps['a'] = 'o'
let g:VM_maps['A'] = 'O'
let g:VM_maps['o'] = 'i'
let g:VM_maps['O'] = 'I'
```

Otherwise two mappings for `o` and `O` are generated and they overwrite each other.

**Comment by ranelpadon** [comment]
@mg979 OMG this works! Didn't imagine having those mapping galore. And yes tried tinkering also with `g:VM_custom_remaps` but it didn't help. Thanks a lot! I could live in peace now. Feel free to close this issue. :)

**Comment by mg979** [comment]
I updated the documentation to make it clearer:

`:h vm-colemak`

**Comment by ranelpadon** [comment]
Seen it, the explanation is clear and useful indeed. Thanks!
