### ISSUE TITLE
Error detected while processing function 438[61]..444[48]..442

### ISSUE THREAD

**Issue by simondrake** [mg979/vim-visual-multi#189]
**Describe the issue:**

Frequently getting the following error when using `<C-n>`.

```
Error detected while processing function 438[61]..444[48]..442:
line    5:
E803: ID not found: 114
Press ENTER or type command to continue
```

Unfortunately, I'm not entirely sure what function it's having issues with so I can't debug very much. 

**Steps to reproduce**  

1. Open a file with several lines of `fmt.Println("Hello World")`
2. Go to the first instance of `Hello` and `<C-n>` a few times
3. Hit `c` (to change the text)
4. Start typing `Goodbye` and observe the error

Note: When running with the minimal vimrc provided in the template, this issue does not occur.

I've provided a video of the issue below:

https://user-images.githubusercontent.com/62928647/132235030-bd7a9dc5-71df-4061-8326-149c6d89b521.mp4

-----

- **Operating System**: Mac 11.5.2 (20G95)
- **Vim Version**:

```
NVIM v0.5.0
Build type: Release
```

- **commit SHA/branch**: I'm not sure...

**Comment by simondrake** [comment]
One thing I haven't done is remove all plugins and add them all one-by-one to see if it's another plugin causing this..... Doing this now....

**Comment by mg979** [comment]
It's probably something that clears the buffer highlight with `clearmatches()`, clearing everything also stuff that doesn't belong to it. Do you see the error already in insert mode? Then I'd do

    au InsertEnter

and see what plugins can cause this.

**Comment by mg979** [comment]
Also

    au TextChangedI
    au TextChangedP
    au CompleteDone

depending on when the error exactly triggers.

**Comment by simondrake** [comment]
OK - the plugin that's causing this is [nvim-colorizer](https://github.com/norcalli/nvim-colorizer.lua). Should have checked this before raising an issue, apologies! 

I did a keyword search, for all of the above, in that repo and didn't get a single match so I've no idea why these two plugins conflict....

**Comment by mg979** [comment]
No problem.

**Comment by simondrake** [comment]
Nope. I was wrong. It has nothing to do with nvim-colorizer; I think I just got _lucky_ when I tried again after disabling that plugin.

The actual issue is related to [these](https://github.com/simondrake/dot/blob/fb8d1e64133d0033f23e80db62874235cf30165b/.config/nvim/general.vim#L38-L44) lines in my dot files. 

I got there from your recommendation regarding `au InsertEnter`.

**Comment by mg979** [comment]
Try doing just `match` (with no arguments) instead of `call clearmatches()`.

**Comment by simondrake** [comment]
Yep! That works a treat, thanks @mg979! 

You called it with your [first comment](https://github.com/mg979/vim-visual-multi/issues/189#issuecomment-913721302)!

> It's probably something that clears the buffer highlight with clearmatches(), clearing everything also stuff that doesn't belong to it.

Thanks for humouring me, it was my own fault all along :)

**Comment by mg979** [comment]
I got an instinct for this kind of things :). I'm closing this.
