### ISSUE TITLE
Able to exchange two selected regions with using tommcdo/vim-exchange

### ISSUE THREAD

**Issue by midnio** [mg979/vim-visual-multi#19]
Actually i really want to use this feature, if you add it it will be much more better. I asked to tommcdo but actually i think he can not do it because understanding this plugin how works can be a little bit hard. I requested for him in this issue:

https://github.com/tommcdo/vim-exchange/issues/45

As he said, (he) i want something like this:

```
So would the desired workflow be something like this?

Use multiple-cursors to select multiple occurrences of the same word
Type X to mark the multiple selections for an exchange
Use multiple cursors to select another set of a different word
Type X to invoke the swap of all occurrences of the first word with all occurrences of the second word

- tommcdo
```

Actually it should be pretty useful, thanks :smile:

**Comment by midnio** [comment]
Actually not.You will select multiple words

```
hello (SELECTED)
hello (SELECTED)
hai
hello (SELECTED)
```

Then you will press <leader>e (For exchange).

```
hello (SELECTED)
hello (SELECTED)
hai
hello (SELECTED)

--EXCHANGE--
```

Then you will selected the word with cx. If you press cx on that word you want, boom!

```
hai
hai
hello
hai
```

Will be cool featurei maybe :p

**Comment by mg979** [comment]
You can do that with [expressions](https://github.com/mg979/vim-visual-multi/wiki/C.-Special-commands#transform-regions-with-expression), in your case the expression would be:

`%t == 'hello' ? 'hai' : 'hello'`

If that isn't enough (that is you want a custom command), you can make commands that you can run in VM.

For example this will do what you want, and work with as many different texts it can find:

```vim
fun! VM_exchange()
  let VM = b:VM_Selection
  if empty(VM)
    return
  endif
  let txt = VM.Global.regions_text()

  " create a list of the unique regions contents
  let unique = []
  for t in txt
    if index(unique, t) < 0
      call add(unique, t)
    endif
  endfor

  " move first unique text to the bottom of the stack, but make a copy first
  let old = copy(unique)
  call add(unique, remove(unique, 0))

  " create new text
  let new_text = []
  for t in txt
    call add(new_text, old[index(unique, t)])
  endfor

  " fill register and paste new text
  call VM.Edit.fill_register('"', new_text, 0)
  normal p
endfun
```

You can then create a mapping if you use it often. Anyway this is the kind of things that can be done with this kind of custom commands, it's not possible to add features that cover every single special need/use case.
