### ISSUE TITLE
Confliction with nvim-treesitter's incremental_selection

### ISSUE THREAD

**Issue by you-n-g** [mg979/vim-visual-multi#190]
**Describe the issue:**

**Steps to reproduce**  

1. install   `vim-visual-multi` and  `nvim-treesitter`
2. Use the following config for incremental_selection 
```
require'nvim-treesitter.configs'.setup {
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "<tab>",
      node_incremental = "<tab>",
      -- scope_incremental = "<tab>", 
      node_decremental = "<s-tab>",
    },
  },
}
```
3. Create multi cursor with `vim-visual-multi`.
4. Press Tab to switch between «cursor» and «extend» mode
4. Expect to enter extend mode. However,  incremental_selection of nvim-treesitter is triggered. 

So my question is:
- Do we have any method
    - to stop `nvim-treesitter` to override the behavior of when entering `vim-visual-multi`'s mode,
    -  while keeping the key mapping of `<tab>` after leaving `vim-visual-multi`'s mode,

-----

- **Operating System**: Ubuntu 18.04
- **Vim Version**:   NVIM v0.6.0-dev+59-g2475161de

- **commit SHA/branch**:  46c082a (HEAD -> master, origin/master, origin/HEAD) Prevent unnamed register infinite concatenation

**Comment by you-n-g** [comment]
My current compromised solution is
```
require'nvim-treesitter.configs'.setup {
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "<tab><tab>",
      node_incremental = "<tab>",
      -- scope_incremental = "<tab>", 
      node_decremental = "<s-tab>",
    },
  },
}
```

**Comment by mg979** [comment]
If it works for you, I don't debug new neovim features. sorry.
