### ISSUE TITLE
Why ctrl+down and ctrl+up don't work?

### ISSUE THREAD

**Issue by kingluo** [mg979/vim-visual-multi#191]
After installation, I just press Ctrl + down (down arrow, right?), but nothing happens.

**Comment by kingluo** [comment]
It's weird that this issue only happens on CentOS vim. When I switch to Ubuntu, everything works then.

**Comment by anne-gert** [comment]
This happens for me too.
I'm using headless Debian 12.11 and vim 9.0.2142 over ssh.

\<C-Down\> doesn't work, but other methods like vj\\\\c does.

Can you help me? Is there a work-around? Or should this issue be re-opened (or otherwise, create a new issue)?
