### ISSUE TITLE
add/fix compatibility with nvim-cmp completion plugin

### ISSUE THREAD

**Issue by WANDEX** [mg979/vim-visual-multi#192]
#### add/fix compatibility with [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) plugin.

Currently vim-visual-multi does not work properly with [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) plugin.

I'm not sure, which plugin need a fix specifically: *nvim-cmp* or *vim-visual-multi*.
I decided to write issue at this project because i assume, that this plugin is more sophisticated, more mature, and multiple cursors are added by vim-visual-multi, not by completion engine plugin.

**Steps to reproduce**

1. add multiple cursors
2. enter insert mode
3. type any long enough word till error occurs (for me it occurs almost instantly)

#### Here is output of the :messages command with occurred error
```
Error detected while processing function 384[61]..390[48]..388:
line    5:
E803: ID not found: 16
Error detected while processing function 384[61]..390[48]..388:
line    5:
E803: ID not found: 16
Error detected while processing function 385[10]..384[61]..390[48]..388:
line    5:
E803: ID not found: 16
```

What do you think about it as a developer? **Could you fix this?**

**If you think that it's necessary to create an Issue/PR at nvim-cmp in order to fix this, \
could you create/do it as the author of vim-visual-multi project?**

Because you have clean understanding on how vim-visual-multi plugin works, and what changes required to make at nvim-cmp, to properly work with multiple cursors provided by vim-visual-multi plugin.

Thank You For This Great Plugin! :rocket:

**Comment by mg979** [comment]
I tried nvim-cmp with buffer source and I can't reproduce.

Try with a minimial vimrc, then add sources one by one and see which source is causing this.
It could also be something in your vimrc (see #189, it's similar), so try with a minimal vimrc.

The problem is that somebody deletes some highlight matches and VM can't find them anymore.
