### ISSUE TITLE
Question: How to repeat "select" operator ?

### ISSUE THREAD

**Issue by NDK2020** [mg979/vim-visual-multi#193]
Dear Ad,

**Describe the issue:**

Assume that I have the following paragraph

> "aaaa"
> 0000000000000000000000000000000000000
> "bbb"
>  0000000000000000000000000000000000000
>  0000000000000000000000000000000000000
> "ccccc"
> 

Goal:  I want to select words inside quotation mark. In this case are: ` aaaa ` and ` ccccc `
I have achieved that by using VMSearch in Visual Mode or manually select every " and then pressed ` si" `

but I think I can figure the manually way to do this in more natural manner such as:
- Put cursor at the 1st " in the first line, then pressed ` si" ` 
- Move the cursor to next occurrence (the quote ") and repeat the "select in quote" by pressing a special key like a dot to repeat (and can **skip**  the repeat to the next occurrences)

Can I achieve those steps?
-----
- **Operating System**: MX Linux 19
- **Vim Version**: 

> - VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  9 2021 02:24:58)
> Included patches: 1-2845

Thank for this great plugins,

**Comment by mg979** [comment]
`:VMSearch pattern` then `nnnnn....`
