### ISSUE TITLE
Some issues with ctrl-o in insert mode

### ISSUE THREAD

**Issue by woodensquares** [mg979/vim-visual-multi#196]
**Steps to reproduce** 

Assume a file with the following lines

```
"something is here"
"something else is here"
```

1. Create two cursors at the beginning of lines just after `"` and press `i` for insert
2. type `Hi ,` then `ctrl-o f "` to move the cursor to just before the second `"`, note a spurious `s` is inserted
3. type ` also`, this will be put only in the second line ending up with

```
"Hi, ssomething is here"
"Hi, ssomething else is here also"
```

instead of

```
"Hi, something is here also"
"Hi, something else is here also"
```

I have tried this with the minimal vimrc file as per the template

- **Operating System**: debian bullseye
- **Vim Version**: NVIM v0.5.1 / Build type: Debug
- **commit SHA/branch**: e20908963d9b0114e5da1eacbc516e4b09cf5803

**Comment by mg979** [comment]
`ctrl-o` isn't supported, but I don't know why this happens, it seems it triggers some autocommands, but it doesn't matter because it would be too difficult to implement. You have to exit insert mode, then do `f"ialso`.

Maybe I'll just disable it with a mapping that does nothing.
