### ISSUE TITLE
Issue with cmp autocomplete

### ISSUE THREAD

**Issue by cj** [mg979/vim-visual-multi#198]
Hi,

I just ran into this issue and thought I'd make a cross post https://github.com/hrsh7th/nvim-cmp/issues/644 that issue has a minimal config to recreate.

Cheers!
-----
- NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
- NVIM v0.6.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
- e20908963d9b0114e5da1eacbc516e4b09cf5803

**Comment by mg979** [comment]
Please minimal vimrc (the one posted in that thread isn't minimal, requires packer).

**Comment by mg979** [comment]
Ok I could load them with this minimal vimrc, but it works for me, I can't see bugs.

```lua
vim.cmd([[
set runtimepath=$VIMRUNTIME
set packpath=$VIMRUNTIME,~/.local/share/nvim/site/testing
packadd! vim-visual-multi
packadd! nvim-cmp
packadd! cmp-buffer
packadd! nvim-snippy
]])

vim.g.VM_maps = {
  ["Add Cursor Down"] = '<c-j>',
  ["Add Cursor Up"] = '<c-k>',
}

vim.o.completeopt = "menu,menuone,noselect"
local snippy = require("snippy")
local cmp = require 'cmp'
local has_words_before = function()
  local line, col = unpack(vim.api.nvim_win_get_cursor(0))
  return col ~= 0 and
  vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col,
    col)
    :match("%s") == nil
end
cmp.setup({
    snippet = {
      expand = function(args)
        require'snippy'.expand_snippet(args.body) -- For `snippy` users.
      end,
    },
    mapping = {
      ["<Tab>"] = cmp.mapping(function(fallback)
        if cmp.visible() then
          cmp.select_next_item()
        elseif snippy.can_expand_or_advance() then
          snippy.expand_or_advance()
        elseif has_words_before() then
          cmp.complete()
        else
          fallback()
        end
      end, {"i", "s"}),
  },
  sources = cmp.config.sources({{name = 'buffer'}}),
})
```

**Comment by cj** [comment]
@mg979 I hope you are doing well! Going back tom this, It selects the first word in the cmp list, you should be able to tab through them.

**Comment by tobealive** [comment]
Same issue over here 

In `V-M` mode cmp completion only selects the first item in the cmp list. Cycling is not possible. Tested with multiple cmp mappings. 

Is there some more info i can provide for a potential fix?
@mg979

**Comment by mg979** [comment]
I think `nvim-cmp` uses its own completion window, that is not vim completion popup, the fix should be in `nvim-cmp` (it should trigger `CompleteChanged` when a different item is selected).
