### ISSUE TITLE
Some mappings not working as expexted

### ISSUE THREAD

**Issue by blayz3r** [mg979/vim-visual-multi#20]
Windows 10 GVIM(most recent)

zn tries to paste from register. Doesn't add numbers
![image](https://user-images.githubusercontent.com/12205650/45589075-86047880-b8ed-11e8-969a-f8c2782769c3.png)

![image](https://user-images.githubusercontent.com/12205650/45589080-a6ccce00-b8ed-11e8-8e4e-2a745b13d294.png)

\<leader\>c (,c) doesn't toggle case.
![image](https://user-images.githubusercontent.com/12205650/45589095-e8f60f80-b8ed-11e8-8c5a-301646a4698b.png)

![image](https://user-images.githubusercontent.com/12205650/45589100-f4e1d180-b8ed-11e8-9da1-e43c05b7a36e.png)

**Comment by mg979** [comment]
Using `comma` as `leader` won't work because `,` is used for the `f`/`t` motion. Try setting:
```
let g:VM_leader = '\'
```
and use `\` for commands that require a leader inside VM (such as `<leader>c`).

**Comment by blayz3r** [comment]
Ok the test branch works, but I run into issues if ** set clipboard+=unnamed**

**Comment by mg979** [comment]
I could reproduce that kind of bugs in gvim by setting `set clipboard=unnamed,unnamedplus`, I guess it's the setting you're using? If so, you can either update from test branch, or try with `set clipboard=`

**Comment by blayz3r** [comment]
Instead of performing the command it pastes from the register. Sorry for being vague.

Normally when you change case:

![2018-09-16_16-48-51](https://user-images.githubusercontent.com/12205650/45600798-a5280680-b9d0-11e8-8790-a50cdd751500.png)

when **set clipboard+=unnamed** is on and try to change case

![2018-09-16_16-50-05](https://user-images.githubusercontent.com/12205650/45600805-b96c0380-b9d0-11e8-925c-443540a14458.png)

**Comment by mg979** [comment]
I'm testing this on Gvim (Windows 10, test branch) right now. Using `set clipboard+=unnamed`, and I can't reproduce your problem. Are you sure you updated the test branch? [This](https://github.com/mg979/vim-visual-multi/commit/a1969ece04193848579f87e9b6c9e6bdd404c406) should be the commit.

**Comment by mg979** [comment]
And, are you by chance changing the clipboard setting ***inside VM***? That will not work for sure.

**Comment by blayz3r** [comment]
Just updated again, the commit came through. it works now. thanks for everything.

**Comment by mg979** [comment]
Ok, sorry for the issue and thanks to you for reporting it.

**Comment by blayz3r** [comment]
NP, the plugin is awesome btw. Should I keep using the test branch?

**Comment by mg979** [comment]
I'll merge it into master since it works. Master is better for now, and they're even. I keep test to fix bugs like this one, for now. Thanks :)

**Comment by blayz3r** [comment]
Perfect, thanks again!
