### ISSUE TITLE
Unselect last match, move to last known match

### ISSUE THREAD

**Issue by DonutEspresso** [mg979/vim-visual-multi#201]
When using the Find Word feature (<C-n>), a match will sometimes go farther than you'd like (e.g., crossing into another section of documentation or function). It's not always obvious since the next match may cause the buffer to scroll to the next page. Is there a way to easily unselect the last match while also moving to the last match? Basically, functionality that is like `N` but also unselects the most recent match. 

I've checked the documentation/FAQ but didn't see anything obvious - it's possible I missed something but couldn't quite figure it out. Thanks!

- **Operating System**: MacOS 12.3
- **Vim Version**: 8.2.4550
- **commit SHA/branch**: e20908963d9b0114e5da1eacbc516e4b09cf5803

**Comment by mg979** [comment]
`Q` ?

**Comment by DonutEspresso** [comment]
Urf. Not sure how I missed that when I was reading through the mappings. Thank you, and apologies for the noise!
