### ISSUE TITLE
Error on master, Vars.noh?

### ISSUE THREAD

**Issue by Dhamma-valence** [mg979/vim-visual-multi#203]
```
Error detected while processing function vm#commands#add_cursor_up[3]..<SNR>147_set_extend_mode[4]..<S
line   11:
E605: Exception not caught: VM cannot start, unhandled exception.
Error detected while processing function vm#commands#add_cursor_up[3]..<SNR>147_set_extend_mode:
line    4:
E171: Missing :endif
```

and

```
Error detected while processing function vm#themes#statusline:
line    4:
E716: Key not present in Dictionary: "Vars.noh"
```

which I believe is a reference to the "Vars.noh" found in `https://github.com/mg979/vim-visual-multi/blob/ccb024c03dda7eb01a5c057408b1828334d97e0a/autoload/vm/plugs.vim`

and lastly,

after these errors when I try to press <Enter> I get the output `-1-1-1` each time I press it, and a new error message:

```
Error detected while processing function <SNR>102_Insert:
line   17:
E716: Key not present in Dictionary: "Insert.replace | return s:Replace(a:key) | endif"
```

Edit/correction:
Last working commit was `e20908963d9b0114e5da1eacbc516e4b09cf5803`

**Steps to reproduce**  

1. Do `<C-Down>` or `<C-Up>` and then get the error messages. 

-----

- **Debian Sid** 
- **NVIM v0.6.1
Build type: Release** 
- **master/4fcd3797e380f2e4c8ea8be31ec6469e6f86f971**

**Comment by mg979** [comment]
I cannot reproduce. Which colorscheme are you using? Can you post output of:

    highlight Search

and

    echo g:Vm.Search

**Comment by Dhamma-valence** [comment]
`:highlight Search`
`
Search         xxx cterm=reverse ctermfg=214 ctermbg=234 gui=reverse guifg=#fabd2f guibg=#1d2021
`

`echo g:Vm.Search`
`
E716: Key not present in Dictionary: "Search"
`

**Comment by mg979** [comment]
> That last one may have something to do with it, eh.

That's normal if you didn't start VM yet.

You didn't tell me the colorscheme you're using, maybe it has something to do with it. I still can't reproduce.

**Comment by Dhamma-valence** [comment]
Sorry, I'm using the original [gruvbox](https://github.com/morhetz/gruvbox)

**Comment by mg979** [comment]
Sorry but I can't reproduce it with my config, or with a minimal vimrc.

I need a minimal config that can reproduce it. Please post your VM settings, or try to reproduce it in a minimal fashion.

If everything fails, you can still use the old commit that worked for you.
