### ISSUE TITLE
Conflict with neovim which-key plug

### ISSUE THREAD

**Issue by JoseConseco** [mg979/vim-visual-multi#205]
**Describe the issue:**
I'm on latest neovim 0.7 (but issue was same sice 5.0). As soon as [nvim-which-key](https://github.com/folke/which-key.nvim) popup is shown,
then [V-M] mode is 'abandoned'.  See this report:
https://github.com/folke/which-key.nvim/issues/115
The witch-key dev is not active, but when I think about it I do not think he can fix it. 

**Steps to reproduce**  
1. `<c-n>`  few times to select some words (or any other way to go into [V-M] mode)
2. Press VM leader  - `\\`
3. if you perform VM operation (eg Align)  before which-key popup is show, action is performed ok. But after WhichKey popup is shown, then VM mode is left (in buggy state, with VM highlights), and we are back in visual/normal mode. No VM action (eg. align) is not executed.

Default config:

```lua
use {
  "folke/which-key.nvim",
  config = function()
    require("which-key").setup {
      -- your configuration comes here
      -- or leave it empty to use the default settings
      -- refer to the configuration section below
    }
  end
}
```
Which key should now show popup with available actions when u are in VM mode, and press `\\ `
-----

- **Operating System**: Manjaro 
- **Vim Version: latest daily, but issue is there since long time**:

**Comment by JoseConseco** [comment]
Just to show which-keys usefulness, after pressing VM leader we get: 
![image](https://user-images.githubusercontent.com/13521338/162633946-581c5067-2b59-4581-b7eb-a9aaf929b35b.png)
I do not imagine remembering these without WKey.

**Comment by mg979** [comment]
:help vm-compatibility

**Comment by JoseConseco** [comment]
I assume you are suggesting to put which-key to VM_plugins_compatibilty, but then we will loose all the suggestions shown above (around 45 suggestions with hotkeys!) 
I any case I hacked a bit which key, and it seems the reason VM stops working is WKey popup defined in lines below: 
```lua
  M.buf = vim.api.nvim_create_buf(false, true)
  M.win = vim.api.nvim_open_win(M.buf, false, opts)
  vim.api.nvim_buf_set_option(M.buf, "filetype", "jk")
  vim.api.nvim_buf_set_option(M.buf, "buftype", "nofile")

```
I assume VM has some autocmd: BuffEnter or WinEnter that when fired disables VM or something. So I tried :
```
   au!
        au BufLeave     * if index(['WhichKey'], &ft) < 0 | call s:buffer_leave()
        au BufEnter     * if index(['WhichKey'], &ft) < 0 |call s:buffer_enter()
```
But no luck (code above supposed to ignore WhichKey) . However removing - call s:buffer_leave() **worked ok** :
```
    augroup VM_global
        au!
        au BufLeave     * echo &ft
        au BufEnter     * echo &ft   
```
File type is not printed though, but now WhichKey popup, is not messing up with VM. @mg979  any chances you could fix code above, and put it into VM?

**Comment by JoseConseco** [comment]
Ok, the bufLeave and enter cannot detect &filetype, thus it autocommand method (from inside VM) did not work. 
Autocmd did not work,  so I had to change WhichKey -  detect VM variable `b:visual_multi`. If true then restore previous regions (\\gs) when closing popup.  Thx for @mg979 for feedback. 
Since which-key dev is not active any more, then I do not think there are any chances for merging this into WKey.

**Comment by mg979** [comment]
I might add some kind of whitelist variable for buffers that won't cancel VM, that would help. I just don't want to add plugin-specific stuff.

**Comment by JoseConseco** [comment]
I think  any popup that causes issues could be whitelisted (but I cant remember any other plugin that would show popup in the middle of executing keyboard command) .  
As mentioned above,  BuffEnter and BuffLeave - did not correctly detected &filetype = 'WhichKey', I think because:
 - first temp window and buffer is created (buffEnter is fired, but filetype is 'empty') 
 - after that  buff filetype is set  (this fires  au FileType event).
 
 I'm not pro at this, so maybe I'm missing something.

**Comment by mg979** [comment]
Yes but popups don't have some special way to be identified as such, so that they can be whitelisted automatically. It should still be possible to use VM in scratch buffers. I'll see what can be done.
