### ISSUE TITLE
[help] How to remap `Add Cursor Up` and `Add Cursor down` ?

### ISSUE THREAD

**Issue by askfiy** [mg979/vim-visual-multi#206]
The default keys `<c-down>` and `<c-up>` are too far from the F area of the keyboard.

So I set it to `<c-j>` and `<c-k>`, but unfortunately this doesn't work.

Below is my configuration:

```
vim.g.VM_default_mappings = 0

vim.g.VM_maps = {
    ["Switch Mode"] = "<tab>",
    ["Find Under"] = "<c-n>",
    ["Skip Region"] = "<c-s>",
    ["Remove Region"] = "<c-p>",
    ["Add Cursor Up"] = "<c-k>",
    ["Add Cursor Down"] = "<c-j>"
}
```

Right now I can only modify the mapping in the source code for it to take effect. But this is not a good solution.

what should I do?

I'm using Neovim 0.7 and the same problem happens with Neovim 0.6.

**Comment by askfiy** [comment]
I found the answer, I can map the keys myself
it works with neovim 0.7

```
vim.keymap.set(
    {"n"},
    "<c-k>",
    ":call vm#commands#add_cursor_up(0, v:count1)<cr>",
    { noremap = true, silent = true }
)


vim.keymap.set(
    {"n"},
    "<c-j>",
    ":call vm#commands#add_cursor_down(0, v:count1)<cr>",
    { noremap = true, silent = true }
)

```

**Comment by kohane27** [comment]
@askfiy I was trying to remap some keys in neovim too and those two commands are exactly what I needed. Thank you!
