### ISSUE TITLE
[improvement] - Multi select without regarding the case (Capitalize, uppercase, lowercase

### ISSUE THREAD

**Issue by ametthey** [mg979/vim-visual-multi#207]
I'm multi selecting my elements but what I want to achieve, it's to select the element with different case element. in my video
I want to select both  **'Contenu'** and **'contenu'**

https://user-images.githubusercontent.com/7902934/166943699-874fcd7a-c162-4a98-8927-2a092716739f.mov

**Comment by mg979** [comment]
VM respects your `ignorecase` setting. There's a mapping to change that inside VM (default `\\c`).

**Comment by mg979** [comment]
Also see `:help g:VM_case_setting`
