### ISSUE TITLE
How to create number sequence with visual-multi selections?

### ISSUE THREAD

**Issue by cander111** [mg979/vim-visual-multi#208]
Using `g<C-a>` in vanilla visual block mode increments selections sequentially, and works with padded numbers as well.

For example, selecting the last 4 lines and typing `g<C-a>`

```
1
1
1
1
1
```
becomes
```
1
2
3
4
5
```
and similarly
```
0001
0001
0001
0001
0001
```
becomes
```
0001
0002
0003
0004
0005
```

But `g<C-a>` does not appear to work with visual-multi selections. For instance if I make a number of selections using `<C-n>` and execute

`g<C-a>` -> no change
```
1
1
1
1
1
```

`<C-a>` -> increments all by the same amount
```
2
2
2
2
2
```

What I want is to increment like `g<C-a>` but using regions, since selections are often not in column format. Is it currently possible to do this with visual-multi?

I can envision a command with the syntax `[n]g<C-a>` where `n` is an optional integer increment amount. The result of this command would be, for each selected region, `<C-a>` would be executed `N` times on that region, with `N=n*i_reg`, where `i_reg` is the index of each region in the selection (indexed from 0). For example, with the following 5 lines selected as 5 regions:

```
0
0
0
0
0
```

typing `5g<C-a>` would execute the following for each region respectively:

region 1: nothing, since `N=0` 
region 2: `5<C-a>`
region 3: `10<C-a>`
region 4: `15<C-a>`
region 5: `20<C-a>`

and the result would be

```
0
5
10
15
20
```

Is it even possible to run region-dependent commands like this? Or is it only possible to execute exactly identical commands on all selections?

**Comment by mg979** [comment]
It's not supported atm, but it's a good idea.

**Comment by mg979** [comment]
Should be working now, tell me if it works for you.

**Comment by cander111** [comment]
Wow this is great, thanks! It is working great for me. The only bug I have found is that undo in visual-multi mode seems to break something when the number of selections is greater than 9. Steps to reproduce:

file, 10 lines of `0`:
```
0
0
0
0
0
0
0
0
0
0
```

highlight first `0` with `<C-v>`
add all others with `<C-n>`
execute `1g<C-a>`
execute `u`
execute `1g<C-a>`

**Comment by mg979** [comment]
I don't see anything breaking on my side. What do you see?

**Comment by mg979** [comment]
Are you using VM undo, or just vim undo?

**Comment by cander111** [comment]
This was with typing `u` in extend mode, which I assume is VM undo, but maybe I'm mistaken. If I exit extend mode and use `u` in normal mode, then re-make the selections it works fine. The result I see is that the last line instead of becoming `10` again is `0`. If I do the same procedure with many more lines (20 or 30 lines of `0`), I get an error about an invalid index `-1` and the numbers do not fill in order. Will reproduce asap Monday.

**Comment by mg979** [comment]
Undo must be enabled

    :help vm-undo-redo

**Comment by cander111** [comment]
I made sure vm-undo-redo is enabled and duplicated the issue. It appears that undo is working properly, however the numbering is incorrect for long sequences. Below is an example that show the issue, specifically, for long sequences all numbers ending in 8 and 9 are skipped:

Open an empty buffer and type the following to generate 50 lines of 0000 and increment them:

i0000<ESC>yy49pgg<C-v>lll<C-n>49<C-n>1g<C-a>

**Comment by mg979** [comment]
I can't reproduce. Vim version/OS?

**Comment by cander111** [comment]
Setting `nrformats=bin,hex` solved the issue, sequences generate correctly. Thanks!!
