### ISSUE TITLE
Question - How to select a word by word in extend mode

### ISSUE THREAD

**Issue by midnio** [mg979/vim-visual-multi#21]
Basically, I did not found that keybindings in unsynched transportation. Can you share those bindings you press in each gif?
![Unsynched transportation](https://camo.githubusercontent.com/3c5a4e1dd41b7548a7a2ffe4d443754feeb368ec/68747470733a2f2f692e696d6775722e636f6d2f55514f437879662e676966)

**Comment by mg979** [comment]
It's the same mapping (`<leader>t`).

**Comment by midnio** [comment]
Actually, I'm not asking this, how did you select the words to transpose? And can you add that bindings clicked by order?

**Comment by mg979** [comment]
> can you add that bindings clicked by order?

I don't understand. You select multiple words as usual, since motions extend the selection, to move around:

* use arrows and add words
* hit `space` to disable temporarily mappings, then you can use motions and add words
* use the mouse to add words (ctrl+rightclick)

**Comment by midnio** [comment]
Nevermind
