### ISSUE TITLE
Leader commands just does't works

### ISSUE THREAD

**Issue by otavioschwanck** [mg979/vim-visual-multi#210]
**Describe the issue:**

The maps just doesn't works.  I Think it can be something related to which key

**Steps to reproduce**  

1. Press C-n to select multiple items
2. Press \\C

Minimal config: https://github.com/otavioschwanck/mood-nvim/tree/multiedit

**Comment by mg979** [comment]
Sorry but I'm not going to debug personal vimrcs. You have to remove stuff until you find the problem, I can't help you with that.
