### ISSUE TITLE
Difficult to exit the vim-visual-multi

### ISSUE THREAD

**Issue by ametthey** [mg979/vim-visual-multi#212]
Hello, 

I'm using your amazing plugin but I have one issue, when I'm finish editing multi-select, I'm having a hard time exiting the mode with escape, did you have the same issues ? Can you help me out ? Thanks

**Comment by mg979** [comment]
Start here:

    :help vm-faq
    :help g:VM_quit_after_leaving_insert_mode

**Comment by unrealapex** [comment]
~~@mg979 Perhaps make <kbd>Ctrl-C</kbd> an alternate bind to exit because it is synonymous with <kbd>Escape</kbd>? I find <kbd>Ctrl-C</kbd> much easier to press than <kbd>Escape</kbd.~~

This is  wrong, please don't do this.

**Comment by sblask** [comment]
I just added this to my config:

```
autocmd BufWrite * call vm#reset()
```

and it seems to work great. So saving a file automatically exits vim-visual-multi.

**Comment by sblask** [comment]
Actually, I had to wrap that with try catch:

```
autocmd BufWrite * try | call vm#reset() | catch | endtry
```

Otherwise it would throw loads of exceptions if vim-visual-multi was not actually active. It would be nice if vim-visual-multi would expose a function that could be called cleanly regardless of whether it is on or off. That could then be mapped to whatever people want.

**Comment by UnrealApex** [comment]
The autocommand would be useful but would not be practical for me because I have set up an autocommand that auto saves files when they are modified:

```
" auto save file when it is modified
augroup auto_save
  autocmd!
  " call save function
  autocmd BufModifiedSet * call AutoSave()
augroup end

" save function that is called when buffer is modified
function AutoSave()
  if (bufname() != "" && &buftype == "" && &filetype != "")
    silent write
  " prevent empty, readonly, etc... buffers from being saved
  else
  endif
endfunction

```

**Comment by mg979** [comment]
@UnrealApex there is a `VM-Exit` plug, you can remap the exit key like any other mapping. It doesn't work in insert mode, but any key you use to exit insert mode will work. It's in the `vm-faq`.

@ametthey Now also `<C-C>` can be used to exit insert mode safely in VM.

@sblask I fixed `vm#reset` to avoid errors.

**Comment by rainbow-bash** [comment]
for someone using nvim 
```lua
local VM_maps = vim.g.VM_maps or {}
VM_maps['Exit'] = '<C-;>'
vim.g.VM_maps = VM_maps
```
put this at the beggining of your init.lua or any place before the plugins
