### ISSUE TITLE
ideavim support

### ISSUE THREAD

**Issue by codercodingthecode** [mg979/vim-visual-multi#218]
Would this work with ideaVim? 
I tried a few things, didn't work for me. But then again, I'm too expert on this.
There is another multi-cursor deprecated that works, but it is very limited compared to this.
It would be really awesome if it worked.

**Comment by mg979** [comment]
I have no idea about this, nor I have interest in it because it's entirely another program, I doubt they can be compatible.
I mean, if it doesn't work there, it means they aren't.
