### ISSUE TITLE
luasnip is partially broken

### ISSUE THREAD

**Issue by yashamon** [mg979/vim-visual-multi#219]
1. create multiple cursors 
2. try to expand a snippet like br for <> 
3. the snippet only expands partially at each cursor, i only get < instead of <>

Of course I tried with other snippets, some similar corruption happens.

**Comment by mg979** [comment]
It's expected, snippets and abbreviations that don't change cursor position are fine, others are not. It's mentioned in the documentation, it's not possible to have this kind of compatibility.
