### ISSUE TITLE
Can't leave visual multi

### ISSUE THREAD

**Issue by hcarver** [mg979/vim-visual-multi#220]
**Describe the issue:**

Can't leave visual-multi. Since updating to the latest version, and the latest version of vim, once I enter VM / Multi mode, using <Esc> or <C-C> fails to exit visual multi.

I'm afraid my vim understanding is not strong enough to debug this without help from you!

**Steps to reproduce**  

1. Move to some text, hit <C-n> to make an initial selection
2. Type <Esc> (nothing happens, text still selected, still in visual multi mode)

This still happens with the minimal vimrc provided.

-----
- **Operating System**: Mac OS 13.1
- **Vim Version**: VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 12 2022 18:56:32)
macOS version - arm64
- **commit SHA/branch**: 724bd53

**Comment by mg979** [comment]
Does it work with an older vim version?

**Comment by hcarver** [comment]
> Does it work with an older vim version?

Yes! I narrowed it down to between 9.0.0950 and 9.0.0.1000. I can leave the plugin on 9.0.0.0950 but I can't on 9.0.0.1000.

**Comment by mg979** [comment]
See if it exits with a delay (press esc, wait some seconds), rather than not exiting at all.

Anyway you can try remapping the exit key

    let g:VM_maps = {}
    let g:VM_maps["Exit"] = '<C-c>'

Maybe it handles differently the esc key, my system vim version is lower (9.0.630 I think) and I can't test the new one atm.

**Comment by hcarver** [comment]
It doesn't exit with any delay - I waited about 30 seconds.

But remapping *did* work. With that change to the Exit key, C-c worked to quit VM mode.

**Comment by mg979** [comment]
If anybody uses a vim version that exhibits this behavior, can try to change this line:

https://github.com/mg979/vim-visual-multi/blob/724bd53adfbaf32e129b001658b45d4c5c29ca1a/autoload/vm/maps.vim#L96

and also add

    && !has_patch(###)

Replace `###` with the patch that introduced the different behavior of the esc key. I don't know what it is, but it should be between 9.0.950 and 9.0.1000, as @hcarver said [here](https://github.com/mg979/vim-visual-multi/issues/220#issuecomment-1355625814).

**Comment by mg979** [comment]
I gave it a try and it doesn't work. But it's a vim issue, if I do:

    nnoremap <esc> o

it doesn't work. The key esc produces a different code no and `<esc>` isn't recognized anymore.

**Comment by mg979** [comment]
Fixed by https://github.com/vim/vim/commit/32030a9f3be25e1343ef15028511614fb4c20e9f
