### ISSUE TITLE
lualine integration / workaround

### ISSUE THREAD

**Issue by farzadmf** [mg979/vim-visual-multi#224]
**Describe the issue:**

Hi, I went through #64 (Integration with vim-airline), and I see mentions of a "function" that, when I click on the link, goes to Wiki home page. I'm guessing it would be the `VMInfos()` function.

I'm currently using [vim-airline](https://github.com/vim-airline/vim-airline), and currently, visual-multi's line works perfectly, and I was wondering if this is something begin done in this plugin or in `vim-airline`'s side.

Asking because now that I'm swithing to Lua and [lualine](https://github.com/nvim-lualine/lualine.nvim), it seems that lualine is somehow overriding visual-multi's one: I see VM status appear and then disappear.

I tried to set `VM_set_statusline = 3`, but still it disappears

So, I was hoping if you could give me some pointers on how to tackle this

---

PS: I hope you don't mind, but since this is more a question rather than a real issue, I didn't fill out the whole template. Let me know if that's necessary

**Comment by mg979** [comment]
If lualine replaces all statuslines it finds, it's not VM problem. The `VM_set_statusline` setting exists for this use case, and it works with airline and maybe others. But I can't prevent other plugin to overwrite the statusline. So you should ask lualine maintainers.
