### ISSUE TITLE
How can I remap "start selecting right or left (S-Right / S-Left)" 

### ISSUE THREAD

**Issue by ApolloTang** [mg979/vim-visual-multi#226]
**Describe the issue:**

How can I remap "start selecting right or left (S-Right / S-Left)" 
I can't seem to find that item in the [full-mappings-list](https://github.com/mg979/vim-visual-multi/wiki/Mappings#full-mappings-list)

**Comment by mg979** [comment]
Select h and Select l I think.

**Comment by ApolloTang** [comment]
Thanks, @mg979 !

So the undocumented default mapping for *start selecting right or left (S-Right / S-Left)* is like this? 
```
let g:VM_maps["Select h"]  = 'S-Left'  
let g:VM_maps["Select l"]  = 'S-Right'  
```

**Comment by ApolloTang** [comment]
Yes, This seems to work! 
```
let g:VM_maps = {}
let g:VM_maps["Add Cursor Down"]             = '∆'  "/ M-j
let g:VM_maps["Add Cursor Up"]               = '˚'  "/ M-k
let g:VM_maps["Select h"]                    = '˙'  "/ M-h
let g:VM_maps["Select l"]                    = '¬'  "/ M-l
```

Thank you, closing this issue now!
