### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by daniele-orlando** [mg979/vim-visual-multi#23]
As a sign of appreciation for your work, I would contribute with a small donation.

Any plan to insert in the repo a badge for [BountySource](https://salt.bountysource.com), [Ko-Fi](https://ko-fi.com) or PayPal?

**Comment by mg979** [comment]
Thanks! But it's not necessary. This plugin is still a WIP, there are still bugs to fix, and possible misbehaviours. Also, the initial keybindings setup is still messy and reflects the keys I was using when I started, and should be streamlined at one point.

For the moment I prefer to improve it little by little, it's not really a "finished product", I'd feel guilty to accept donations, appreciation is enough and appreciated though :).
