### ISSUE TITLE
Keymaps

### ISSUE THREAD

**Issue by AndreM222** [mg979/vim-visual-multi#235]
Hello. amazing plugin and just wanted to ask if there is a way of disabling the key \\\\\\ because I like to use the map \\\\ for something else and if it has the \\\\\\ then it takes time before loading . If not could you add a function to disable default configs from the plugin.

**Comment by IndianBoy42** [comment]
Set VM_leader to something else

**Comment by IndianBoy42** [comment]
VM_Maps then?

**Comment by mg979** [comment]
I'm using these settings:

    let g:VM_mouse_mappings             = 1
    let g:VM_leader                     = {'default':'\', 'visual':'\', 'buffer':'\\'}
    let g:VM_custom_remaps              = {'<c-p>': 'N'}
    let g:VM_custom_noremaps            = {'==': '==', '<<': '<<', '>>': '>>'}
    let g:VM_user_operators             = ['cx', 'yd', 'g~', 'gc']
    let g:VM_maps                       = {}
    let g:VM_maps["Undo"]               = 'u'
    let g:VM_maps["Redo"]               = '<C-r>'
    let g:VM_maps["Mouse Column"]       = '<C-S-RightMouse>'
    let g:VM_maps["Toggle Mappings"]    = '<Space>'
    let g:VM_maps["Reselect Last"]      = '\gv'
    let g:VM_maps["Visual Cursors"]     = 'C'
    let g:VM_maps["Select All"]         = 'gam'
    let g:VM_maps["Align"]              = 'gal'

    nmap <C-j> <C-Down>
    nmap <C-k> <C-Up>

    nnoremap g/ :VMSearch<space>

And `\\` creates a cursor. If I understood correctly it's what you're trying to do.

**Comment by AndreM222** [comment]
i dont want to add it to a new mapping but remove it completly so i can have another plugin using \\\\ and it wont wait to see if I type \\\\\\

**Comment by IndianBoy42** [comment]
Using VM_Maps/VM_Leader doesn't *add* it to a new mapping it changes the mapping, no mapping will exist anymore for \\\ and if that's the only mapping under \\ then neovim will not wait anymore when it sees \\. If it does then check `:map \\` to see what else is bound under there and change it

**Comment by AndreM222** [comment]
Thanks for the help. I tried it many times and was failing because I was writting it in a file outside the init . it seems is required to be in the init it cant be separated. thanks and now it works
