### ISSUE TITLE
Feature request: is it possible to support "select non adjacent lines"?

### ISSUE THREAD

**Issue by kgfly** [mg979/vim-visual-multi#236]
Eg. the file has 5 lines.

1 : aaa
2 : bbb
3 : ccc
4: ddd
5: eee

Is it possible to support "select non adjacent lines"? Etc, select line #2 and #4.

Thanks for your consideration.

**Comment by mg979** [comment]
It's already possible

    :help vm-remove-every-n

**Comment by kgfly** [comment]
Thanks. I tried but I cannot figure how to use it. 

Assume the file is

1
2
3
4
5
6
7
8
9

I want to select line 1/34/789. How to do it? May you please show an example?

I try

Select line 1, using V
Ctrl-N / q does not seem work. 

Thanks

**Comment by jeansagi** [comment]
Why do you want to select multiple lines?

If for example you want to delete distinct lines at once (as in you example:1/34/789) you could do:

* Put your cursor on 1.
* 8\<C-Down\> " Create cursors from line 1 to 9
* Move your cursor to line 5 (I use up arrows)
* 2Q " Clear cursors on line 5 and 6)
* Move your cursor to line 2 (I use up arrows)
* Q " Clear cursor on line 2

So you have cursors on lines 1/34/789

Now you could do whatever you want:

* D " Delete to the end of line
* dd " Delete the lines with cursors (you are left with lines 2, 5, and 6.
* \<Tab\> " Change from cursor mode to select mode

Of course, you can use help (as mr @mg979 suggested: `:help vm-remove-every-n)`.

And you can also follow the tutorial as in the readme (which is highly recommended):
`vim -Nu path/to/visual-multi/tutorialrc`


J.

**Comment by kgfly** [comment]
Thanks for your reply, @jeansagi .

Why do you want to select multiple lines?
->
I mainly need it for vim figurative, the git plugin. A simplified example is:

![image](https://user-images.githubusercontent.com/12282281/234020725-657e4e7b-b8a3-47a7-909f-2ad492f78ed5.png)

I want to select line 1 and line 3 and stage them, by pressing "s".

I tried what you suggested

_Put your cursor on 1
...._

Unfortunately, it does not work. 

Thanks

**Comment by jeansagi** [comment]
Fugitive you might say ;)

And BTW, what you want is beyond my knowledge.

J.
