### ISSUE TITLE
Confusion about `q`

### ISSUE THREAD

**Issue by musjj** [mg979/vim-visual-multi#239]
**Describe the issue:**
`q` has unexpected behavior in certain contexts.

**Steps to reproduce**  
Given this piece of text, with the cursor on `^`:
```
some word
^
stuff some
some time
```
Pressing `<C-n>nn` will select `some` in all lines. 
But I wanted to de-select the second `some`. 
So I pressed `Nq`. It de-selected the second `some`, like I expected, but my cursor ended up back on the first `some`. I would expect that my cursor move forward to the third `some`.
Is this intended behavior or a bug?

-----

- **Operating System**: Linux
- **Vim Version**: NVIM v0.10.0-dev-382+gebb10d624
- **commit SHA/branch**: 724bd53adfbaf32e129b001658b45d4c5c29ca1a

**Comment by mg979** [comment]
It's intentional. It skips and selects next in the current direction. Use `Q` to simply remove.

**Comment by musjj** [comment]
But what if you want to go to a previous match, deselect it and move to the next match?

> It skips and selects next in the current direction. Use Q to simply remove.

IMO, this is unintuitive because it means the the "current direction" is decided by the last `n`/`N`. This is different from how search works natively in vim (the direction is set by the initial `/`/`?`).

**Comment by mg979** [comment]
You can also use `[` and `]` to select a cursor, then remove it. It's how it works.

**Comment by musjj** [comment]
Thanks for the suggestion, that improves it a bit because the direction is more explicit. But the current direction is still modified by the last `[`/`]`, strangely. It would be nice if we can have an option to turn off this behavior.

**Comment by mg979** [comment]
As I said, it's intentional.
