### ISSUE TITLE
Unable to disable <C-n> mapping in Lua (neovim)

### ISSUE THREAD

**Issue by svanharmelen** [mg979/vim-visual-multi#241]
I'm trying to disable the `<C-n> mapping but no matter what I try, it keeps being mapped...

I tried:

```
        vim.g.VM_default_mappings = 0
        vim.g.VM_maps = { ['Find Under'] = '' }
```
And:
```
        vim.g.VM_default_mappings = 0
        vim.g.VM_maps = vim.empty_dict()
        vim.g.VM_maps['Find Under'] = ''
```

But in both cases `<C-n> is still mapped when restarting neovim. What am I missing?

**Comment by thiag0mei** [comment]
Having the same issue, if we check with `echo VM_maps["Find Under"], the variables are set correctly but they have no effect.

I recently switched to Lazy as my plugin manager and was thinking maybe this was the cause.

**Comment by svanharmelen** [comment]
I'm not using Lazy, so guess its not related to the package manager...

**Comment by urayoru113** [comment]
I got same issue, and after doing some research I found that this is because `VM_maps` do not directly point to the action.

You have to initialize before loading this plugin

like:

``` lua
-- lazy --
{
	"mg979/vim-visual-multi",
	branch = "master",
	init = function()
		vim.g.VM_maps = {}
		vim.g.VM_maps["Find Usesr"] = ""
	end,
}
```

**Comment by thiag0mei** [comment]
That was it! Great find.

**Comment by svanharmelen** [comment]
Nice! In case of [packer](https://github.com/wbthomason/packer.nvim#custom-initialization) it needs to be configured with `setup` instead of `config` to make it work as expected...

**Comment by MarkelCA** [comment]
Can someone give me an example of how it's done with Packer pls?

I'm trying this but as @svanharmelen said before, the variables are set but they have no effect:

`  use {
      'mg979/vim-visual-multi',
      branch = 'master',
      config = function()
          vim.g.VM_default_mappings=0
          vim.g.VM_maps = {
              ["Find Under"] = "<C-a>"
          }
      end,
  }
`
I'm new with packer & lua so I might be missing something.

Thanks!

**Comment by svanharmelen** [comment]
For reference, this is how I configured it now (please ignore the chars I mapped it too, they are specific ctrl+letter combo's on my mac 😏):

<img width="473" alt="image" src="https://github.com/mg979/vim-visual-multi/assets/4171547/be28d76e-fbbc-4e13-918f-7f6266eb324c">

I guess this is what you where looking for @MarkelCA (even through you removed your comment 😉)?

**Comment by MarkelCA** [comment]
Hi @svanharmelen! I finally made it, that's why I removed the comment 😅. Anyways, thanks for the fast reply! 

I was wondering if I could extract it to another file too, maybe using some "require" syntax like I did with other plugins. I'm not sure  if it's possible with this one since it's made with vimscript and lacks modules, but I ask just in case

```lua
-- example:
require("neo-tree").setup({
  default_component_configs = {
    icon = {
...
```

**Comment by alextricity25** [comment]
> For reference, this is how I configured it now (please ignore the chars I mapped it too, they are specific ctrl+letter combo's on my mac 😏):
> 
> <img alt="image" width="473" src="https://private-user-images.githubusercontent.com/4171547/253820087-be28d76e-fbbc-4e13-918f-7f6266eb324c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNTg2MjEsIm5iZiI6MTcxMzA1ODMyMSwicGF0aCI6Ii80MTcxNTQ3LzI1MzgyMDA4Ny1iZTI4ZDc2ZS1mYmJjLTRlMTMtOTE4Zi03ZjYyNjZlYjMyNGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMDEzMjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWJiZTIwNjRmZjQxNzU2MTEzMWE2MGRjN2Q2MzBjOGQzMjYwNTgzZTg1OGM0M2NlMzRhMzY5MjdkZTI2M2RjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eiNVXtxrQahJqrM3bzAzOoXP4CSoFVX-b-5ioUqzi4Q">
> I guess this is what you where looking for @MarkelCA (even through you removed your comment 😉)?

For me, `setup` needed to be `init`, like how @urayoru113 has it.
