### ISSUE TITLE
I installed the plugin using lazy.nvim; it doesn't seem to work? What should I do about it.

### ISSUE THREAD

**Issue by whxcode** [mg979/vim-visual-multi#245]
<img width="1800" alt="image" src="https://github.com/mg979/vim-visual-multi/assets/44012914/f1738922-54eb-4303-ac7e-edc07f54f3fe">

**Comment by whxcode** [comment]
is the reason I set it.

**Comment by mg979** [comment]
see https://github.com/mg979/vim-visual-multi/issues/241
