### ISSUE TITLE
Capitalizing with U when using visual multi select does not work

### ISSUE THREAD

**Issue by Napam** [mg979/vim-visual-multi#248]
**Describe the issue:**
Generally speaking in vim you can select text with visual mode then press U to capitalize letters in the selection.

When I select text using VM and then pressing "U" (which usually capitalizes whatever I have selected) the cursor just jumps to the top of the selection.

**Steps to reproduce**  

1. Enter Visual multi mode with Ctrl + n
2. Select some text
3. Press U

I have tried the minimal vimrc with just the plugin and the results were the same. I do get a warning though with my full config enabled:

```
b1: Overwritten imap: <BS> (I BS)  ->  v:lua.MPairs.autopairs_bs()
```
but i think it is unrelated

-----

- **Operating System**: Mac OS Sonoma 14.0
- **Vim Version**: Neovim 0.9.4
- **commit SHA/branch**: master ([724bd53](https://github.com/mg979/vim-visual-multi/commit/724bd53adfbaf32e129b001658b45d4c5c29ca1a))

**Comment by mg979** [comment]
The mappings for lowercase/uppercase are `gu`/`gU`, as for normal mode, because `u` is used for undo, and `U` shouldn't be used.

**Comment by Napam** [comment]
Thank you for the info! Just curious, why shouldn't U be used? Is that a neovim thing in general that U should be overridden?

**Comment by mg979** [comment]
Because `U` isn't remapped and it would do what `U` does in normal mode.
