### ISSUE TITLE
Visual Regex doesn't grab each occurrence on every line 

### ISSUE THREAD

**Issue by damianoognissanti** [mg979/vim-visual-multi#249]
If a Visual Regex is performed on the following block
```
aaaaa
baaab
babab
```

Searching for the letter `a` gives just one cursor on line 1, and one on line 2, but 2 on line 3. In kakoune, helix etc. it will instead place a cursor on each search result on every line regardless of repetitions, which means you can, for example, mark the string, `123456789`, search for `[0-9]` to place markers on each integer, press return and transform it into a list
```
1
2
3
4
5
6
7
8
9
```

**Comment by mg979** [comment]
If you do

    :<,>VMSearch a

it works as you say, I think `VMSearch` works better than Visual Regex.

You can use a mapping:

    xnoremap g/ :VMSearch<space>

**Comment by damianoognissanti** [comment]
Thank you, that seems to work :-)
