### ISSUE TITLE
Module not found error message on lazy.nvim

### ISSUE THREAD

**Issue by ekkyarmandi** [mg979/vim-visual-multi#254]
**Describe the issue:**
<img width="1439" alt="Screen Shot 2024-01-07 at 10 17 31 AM" src="https://github.com/mg979/vim-visual-multi/assets/59816970/bcf37e22-5966-4b79-a35e-6cf87e3634d7">

The plugin works. But I get the `module not found error` on the `lazy.nvim` when I restart the nvim. That's weird.

I'm using [AstroNvim](https://astronvim.com) and trying to install the plugin from the `~/.config/nvim/lua/user/plugins/user.lua`. I'm new to Neovim and I want to bring back multi-edit just like what I usually did on VS Code.

Does any body know why? Thank you

-----

- **Operating System**: Mac OS 12.2
- **Vim Version**: NVIM v0.9.2 Build type: Release 
- **commit SHA/branch**:  aec289a9fdabaa0ee6087d044d75b32e12084344

**Comment by ekkyarmandi** [comment]
I think I already solved the issue.

Just need to change the `opts` with `config` and an empty function. Like the code below:
```lua
return {
  {
    "mg979/vim-visual-multi",
    branch = "master",
    config = function() end,
    event = "User AstroFile",
  }
}
```

**Comment by T3sT3ro** [comment]
I'm trying to use this plugin inside Nv-chad and I can't for the love of god make it work and even see why it's not active. Only when I add `lazy=false` to the plugin config in lazy it works...

**Comment by SpongeBobWillReignSupreme** [comment]
@T3sT3ro, I see it has been over 2 months but I am trying to do the same thing inside of Nv-Chad but i cant get the plugin to work/load. Did you ever figure this out?

**Comment by T3sT3ro** [comment]
@SpongeBobWillReignSupreme Try using the following configuration in your `.config/nvim/lua/plugins/init.lua`:

```lua
return {
  -- ...
  -- https://github.com/mg979/vim-visual-multi
  {
    "mg979/vim-visual-multi",
    branch = "master",
    lazy = false,
    config = function() end,
  },
  
  -- ...
}
```

I still don't know what the heck is going on and how to configure it properly. I also noticed that invoking Ctrl+N (default action for opening NvTree) invokes... NvTree instead of visual-multi, but when I use CTRL+Up/Down to add cursor above/below, then from that moment on the Ctrl+N uses the action from visual-multi to add cursor at next word occurrence.

**Comment by carstenbauer** [comment]
Poor man's solution: choose a different key binding than Ctrl+N for visual-multi. Of course, it shouldn't be occupied already (which dramatically limits the options). I chose Ctrl + \ like so:

```lua
{
  "mg979/vim-visual-multi",
  branch = "master",
  enabled = true,
  lazy = false,
  config = function() end,
  init = function()
    vim.g.VM_maps = {
                    ["Find Under"] = "<C-\\>"
                }
  end,
},
```
