### ISSUE TITLE
`VM-Add-Cursor-At-Pos` custom mapping in Neovim doesn't work

### ISSUE THREAD

**Issue by alextricity25** [mg979/vim-visual-multi#263]
**Describe the issue:**
`VM-Add-Cursor-At-Pos` doesn't work with custom mappings. 

I have mapped `VM-Add-Cursor-At-Pos` using which-key like so:
```
wk.register({
  m = {
    name = "Visual Multi",
    m = { "<Plug>(VM-Find-Under)<Tab>", "Start Multiple Cursors", mode = { "n" } },
    a = { "<Plug>(VM-Select-All)<Tab>", "Select All", mode = { "n" } },
    r = { "<Plug>(VM-Start-Regex-Search)", "Start Regex Search", mode = { "n" } },
    **p = { "<Plug>(VM-Add-Cursor-At-Pos)", "Add Cursor At Pos", mode = { "n" } },**
    u = { "<Plug>(VM-Add-Cursor-Up)", "Add Cursor Up", mode = { "n" } },
    d = { "<Plug>(VM-Add-Cursor-Down)", "Add Cursor Down", mode = { "n" } },
    v = { "<Plug>(VM-Visual-Cursors)", "Visual Cursors", mode = { "v" } },
    t = { "<Plug>(VM-Toggle-Multiline)", "Toggle Multiline", mode = { "n" } },
  }
}, { prefix = "<leader>" })
```

My understanding is that `VM-Add-Cursor-At-Pos` should add a cursor at the current position, allowing me to add multiple cursors across lines that aren't necessarily directly above or below one another. However, whenever I invoke my mapping for `VM-Add-Cursor-At-Pos`, nothing happens. Short clip below.

https://github.com/mg979/vim-visual-multi/assets/4964964/670a5fd5-15ea-46df-9668-3424c9d39ad0

**Steps to reproduce**  

1. Map `VM-Add-Cursor-At-Pos` to a custom mapping
2. Run it.
3. No cursor appears

-----

- **Operating System**: Mac OS 14
- **Vim Version**: nvim v0.9.0
- **commit SHA/branch**: e2ff111

**Comment by mg979** [comment]
The other mappings you set that way, do they work? I have no problems using `g:VM_maps`.

Also consider that after you add a cursor at position, mappings are enabled, so you move the cursor with movements and you can't see it.

Update the plugin, then try setting `g:VM_add_cursor_at_pos_no_mappings' to 1 and see if it works.

**Comment by alextricity25** [comment]
> The other mappings you set that way, do they work? I have no problems using `g:VM_maps`.
> 
> Also consider that after you add a cursor at position, mappings are enabled, so you move the cursor with movements and you can't see it.
> 
> Update the plugin, then try setting `g:VM_add_cursor_at_pos_no_mappings` to 1 and see if it works.

The other mappings work just fine.  I see what you mean. `hjkl` moves the vim cursor and the VM cursor. I need to use the arrow keys to just move the vim cursor 🤯 

It looks like the setting that you just added (`g:VM_add_cursor_at_pos_no_mappings`) isn't quite doing the trick. I can use movements (hjkl) to move around now, but when I add more cursors then try to type something, the characters only show up where my vim cursor is. Video below.

https://github.com/mg979/vim-visual-multi/assets/4964964/e3fe75c5-919a-45cd-bb18-77761477e5fa

**Comment by mg979** [comment]
>  isn't quite doing the trick

That setting make it so that mappings _start_ disabled, but then you must enable them again when you're finished adding cursors. Key to toggle mappings is `space` by default.

**Comment by alextricity25** [comment]
Ah yes, you're right! I guess I was just confused about what it means to have mappings disabled vs enabled. Time to read the docs 😅 Thank you very much for you help ❤️
