### ISSUE TITLE
Help for visually selecting different words in different lines and changing them all at once.

### ISSUE THREAD

**Issue by dgokcin** [mg979/vim-visual-multi#268]
### Issue: How to Visually Select and Change Multiple Words

Hello and thanks for this plugin.

I have been mainly using this plugin for basic tasks like changing all or some occurrences of the same word. Now, I am trying to visually select different words on different lines and change them all at once. I spent a lot of time in the help pages, but I could not figure this out on my own. Could you please guide me through how to accomplish this?

I would like to be able to visually select `asd` and `pqt` and change both occurrences to `xyz`.

```txt
asd fgh
jkl
mno pqr
```

A few things to note about my Neovim setup:

- Arrow keys are mapped to `<Nop>`
- `<C-down>` or `<C-up>` trigger OS-level shortcuts, so they cannot be used
- Current plugin configuration:
  ```lua
  return {
    "mg979/vim-visual-multi",
    branch = "master",
    vscode = "true",
    event = "BufReadPost",
    init = function()
      vim.g.VM_maps = {
        ["Add Cursor Down"] = "<M-j>",
        ["Add Cursor Up"] = "<M-k>",
      }
    end,
  }
  ``` 

Thanks in advance!

**Comment by mg979** [comment]
You either use the mouse to visually select words, then select all matches on each of them, or 

1. select all matches of a word
2. disable mappings (`:help vm-mappings-toggle`)
3. move to another word
4. enable mappings again
5. repeat 1.

But I really prefer `:%s/pattern/replacement/g` to replace all occurrences of something.
