### ISSUE TITLE
Can't change mappings - Undefined variable: g:VM_maps

### ISSUE THREAD

**Issue by sblask** [mg979/vim-visual-multi#27]
See configuration in https://github.com/sblask/dotfiles/blob/vim-visual-multi/.vimrc.d.symlink/plugins.vim on branch vim-visual-multi of my dotfiles.

I get `Undefined variable` every time I open neovim now
```
Error detected while processing /home/sebastian/Clones/dotfiles/.vimrc.d.symlink/plugins.vim:
line  126:
E121: Undefined variable: g:VM_maps
Press ENTER or type command to continue
```
When I remove the line, the problem is gone too. What am I doing wrong?

**Comment by mg979** [comment]
You should initialize the variable first:
```
let g:VM_maps = {}
let g:VM_maps['Remove Region'] = '<c-x>'
```

Does it work?

**Comment by sblask** [comment]
Embarrassing! Didn't try that because I thought it's about modifying an existing map. Works like a charm.

**Comment by mg979** [comment]
Mappings are created on VimEnter, after the vimrc is read. That variable doesn't exist yet so it must be initialized.
