### ISSUE TITLE
g:VM_silent_exit=1 does not silently exit

### ISSUE THREAD

**Issue by miversen33** [mg979/vim-visual-multi#276]
**Describe the issue:**
There is a setting `g:VM_silent_exit` that when set, I would assume it would silently exit the visual multi mode. This however is not what it does. 

When it is "unset", you see the following message print

> Exited Visual-Multi
> Press ENTER or type command to continue

Indeed, setting `g:VM_silent_exit` = 1 does remove the 'Exited Visual-Multi' text. However I am still prompted to press enter to continue. I would assume that a silent exit would be silent. As in, not break my flow of work.

This was called out in #266 but it seems that (I am hoping) there was a miscommunication on the request.

Currently, it is impossible to completely silence this print message. This is due to [vm.vim:172](https://github.com/mg979/vim-visual-multi/blob/master/autoload/vm.vim#L174) which prints an empty line to the console when `g:VM_silent_exit != 0`.

I would submit a PR removing this line but given how #266 was handled, I am unsure if this project is open to PRs. I personally am _not_ interested in forking as I don't want to maintain a fork. I just want silent to indeed be silent.

Am I missing something here?

**Comment by mg979** [comment]
That PR was rejected because it was doing absolutely nothing. Can you try to change this line

https://github.com/mg979/vim-visual-multi/blob/38b0e8d94a5499ccc17d6159763d32c79f53417b/autoload/vm.vim#L174

to

    redraw!

instead? Tell me if it works for you, because I don't have problems with that setting.

**Comment by miversen33** [comment]
That works. I also tried simply shifting that echo up into the `if block` (as seen [here](https://github.com/miversen33/vim-visual-multi/blob/33e715ebb5ea7a95713350e6b14645c019a9b70b/autoload/vm.vim#L170-L174)).

I am more than happy to submit solution as a PR if you are open to it :)

**Comment by mg979** [comment]
Line 172 runs if the option is `0` so it's not the problem, since you set the option to `1`. It's `echo "\r"` that is problematic. If it works by replacing it with `redraw!` (leaving the rest unchanged), I can accept the PR.

**Comment by miversen33** [comment]
> Line 172 runs if the option is `0` so it's not the problem, since you set the option to `1`. It's `echo "\r"` that is problematic. If it works by replacing it with `redraw!` (leaving the rest unchanged), I can accept the PR.

That actually makes sense. The reason my original take on it "worked" was not because I moved the `echo` but because I removed it from the logic block that is ran after `silent_exit`.

Anyway, PR submitted :)
