### ISSUE TITLE
Can't add cursor with <M-j>

### ISSUE THREAD

**Issue by i6o6i** [mg979/vim-visual-multi#28]
I add the following configuration to .vimrc, but It doesn't work, instead, it exits the VM.
```
let g:VM_maps["Add Cursor Down"]             = '<M-j>'
let g:VM_maps["Add Cursor Up"]               = '<M-k>'
```
However, when I delete these two lines, I can use <C-Up> to add cursor.
I check my gnome(which is my desktop) key mapping, and I don't find any shortcut map <M-j>
Since I don't know where to store the terminal keymap, I don't know if there are some hotkeys map <M-j> in my terminal. Any help will be appreciated

**Comment by i6o6i** [comment]
here is my configuration https://github.com/i6o6i/Unamed/blob/master/.vimrc

**Comment by mg979** [comment]
What are you trying to do exactly? Vim version? Terminal or gui? OS? Can you correct the message escaping `<>` or using bacticks? It's not clear what you're doing. Here using this works fine:
```
let g:VM_maps = {}
let g:VM_maps["Add Cursor Down"] = '<M-j>'
let g:VM_maps["Add Cursor Up"]   = '<M-k>'
```

**Comment by mg979** [comment]
Also, consider that if you are in terminal, meta keys don't work by default, so `<M-j>` and `<M-k>` won't work, unless you set up meta bindings with some plugin (or by yourself).

**Comment by i6o6i** [comment]
I find the solution finally
```
let g:VM_maps["Add Cursor Down"]             = '<M-j>'
let g:VM_maps["Add Cursor Up"]               = '<M-k>'
```
I compile vim a few days ago, I use it in terminal(with GUI support)
Version: 8.1.513
OS:CentOS 7.5
I think is all about the meta key
thanks for your help

**Comment by mg979** [comment]
Terminal vim doesn't support meta keys by default (neovim does). If it was the problem, maybe you can say how you fixed it (and close the issue if it's all ok :) ). Thanks

**Comment by i6o6i** [comment]
Seems like it a good reason to switch to neovim, since I can not miss the plugin :D,Thanks.

**Comment by mg979** [comment]
There are ways to use meta keys in terminal vim, by the way (i use it, and I set up meta keys).

**Comment by i6o6i** [comment]
I find it needs a while to exit VM with my configuration above, And I finally find the solution.
I think it's convenient for someone who comes across the problem if I post the solution here.
```
set <M-j>=^[j
set timeout timeoutlen=5000 ttimeoutlen=500
let g:VM_maps = {}
let g:VM_maps["Add Cursor Down"]             = '<M-j>'
```
For more details, please visit [https://groups.yahoo.com/neo/groups/vim/conversations/topics/55886] 
(https://groups.yahoo.com/neo/groups/vim/conversations/topics/55886)

**Comment by mg979** [comment]
I added the scripts I'm using for this stuff in this repo

https://github.com/mg979/alt-mappings.vim

**Comment by i6o6i** [comment]
Thanks for your sharing, It works well
