### ISSUE TITLE
meta keys and doc issue

### ISSUE THREAD

**Issue by antoinemadec** [mg979/vim-visual-multi#29]
Hi!

_OS: Debian_GNULinux_testing_buster
Window manager: I3
Terminal: termite v14
Vim: VIM - Vi IMproved 8.1 Included patches: 1-504_

I already saw #28 and it seems meta keys do not work on my terminal vim, but doesn't work either on Gvim.
Also, the doc says that to add vertical cursors:
_You can use keys M-j / M-k (for cursor mode) or M-C-Down / M-C-Up (extended mode)_ 

I have 3 questions:

1. Could the default mapping not involve the Meta key?
2. Could the doc mention the Control mappings?
3. Are ```<C-up>``` and ```<C-down>``` using cursor or extended mode? How to you switch to the other mode without meta keys?

**Comment by mg979** [comment]
1. I should remove meta keys from all default mappings, for now to disable them set `g:VM_no_meta_mappings` to 1
2. it's mentioned [here](https://github.com/mg979/vim-visual-multi/wiki/M.-Mappings#meta-keys), but I should reorganize the wiki
3. to switch mode you use `Tab`
