### ISSUE TITLE
surpport for dyng/ctrlsf.vim  ?

### ISSUE THREAD

**Issue by hackingcat** [mg979/vim-visual-multi#3]
The plugins is awesome.I think it more wonderful if it can work with dyng/ctrlsf.vim.

**Comment by mg979** [comment]
There is a (yet) undocumented API, you should be able to call it like this:

```vim
nnoremap     <C-F>v :call VM_ctrlsf()<cr>
fun! VM_ctrlsf()
  let txt = b:VM_Selection.Regions[0].txt
  exe "CtrlSF ".txt
endfun
```

That is, you press \<C-d\>, then \<C-f\>v (or another mapping). I don't use that plugin but it should work.

**Comment by mg979** [comment]
What is it, that doesn't work in ctrlsf.vim, exactly? I tried it a bit and it seems to work in my system (linux, vim 8). Thanks.

**Comment by hackingcat** [comment]
I add 

    nnoremap <C-n> :call VM_ctrlsf()<cr>
    fun! VM_ctrlsf()
    let txt = b:VM_Selection.Regions[0].txt
    call vm#reset()
    exe "CtrlSF ".txt
    endfun

to my vimrc.You can check by the [link](https://asciinema.org/a/aOzizut1Wk6YugFgJxrHYcmXX).

**Comment by hackingcat** [comment]
In addition,you can add the suggestion that [mg979/vim-visual-multi](https://github.com/mg979/vim-visual-multi)  is able to  cooperate with [brooth/far.vim](https://github.com/brooth/far.vim).Last but not least,your plugin is out of the world , and thanks for your outstanding efforts.

**Comment by mg979** [comment]
Thanks for the apperciation. I'd like to make it work with all plugins without needing to say that a plugin works with it, so I'd rather fix the problem with ctrlsf ([my test](https://asciinema.org/a/0UvfTwZGjVc31wrmZwPOHoq75)). Which keys do you use to change text? The most reliable way right now is select, then press `c` to change while in extend mode, change in cursor mode (`c` + motion) isn't good enough yet. You can check the test branch and see if it works better (but I made a test with master and it worked, so it may be something else).

**Comment by mg979** [comment]
Does it happen only with crtlsf? Can you use arrow keys/backspace in normal buffers?

**Comment by fcying** [comment]
What features are not available in ctrlsf? I tried `<c-n>`, `q`  `]`  `[`, all work fine. vm config only set `<c-n>` instead `<c-d>`

**Comment by mg979** [comment]
I also think it works fine (mostly) with ctrlsf. The main problem is that `ctrlsf` buffer mapping are rewritten by `vm`, so I could have it restore them on exit.
