### ISSUE TITLE
merging lines introduces issues

### ISSUE THREAD

**Issue by antoinemadec** [mg979/vim-visual-multi#30]
Hi!

_OS: Debian_GNULinux_testing_buster
Window manager: I3
Terminal: termite v14
Vim: VIM - Vi IMproved 8.1 Included patches: 1-504_

File:
```
a
b
```

Commands:
```
<C-down>
<backspace>
<enter>
```

Expected result: same as original file.

Actual result:
```
a b
° 
° 
```

**Comment by mg979** [comment]
It seem to happen in lines that include the very first or the very last, not in between. I'll have to see what causes this.

**Comment by mg979** [comment]
Insert mode `<bs>` and `<del>` should behave much better now (in test branch). Still not perfect but they broke easily before with empty lines and other circumstances.
