### ISSUE TITLE
Shortcuts don't work on OS X

### ISSUE THREAD

**Issue by typoman** [mg979/vim-visual-multi#31]
First of all very nice Plugin. Although I can't seem to make the shortcuts work in the OSX default terminal app. So far the only shortcut which had worked is control+n which selects the next match (control+d doesn't work). Using control and arrow keys, nothing. Leader+A no results. My vim leader is set to space, so I also tried \a, also no results. control + mouse also doesn't work. Since the wiki is not clear about the mapping I was wondering if there is going to be any solution for these problems?

**Comment by mg979** [comment]
Could you try to change the leader to `\`? Just to be sure.

**Comment by typoman** [comment]
Changing the \<leader\> back to the default '\\' didn't have any effect. I also get many errors when installing the test branch. Many of these errors keep persisting after I go back to vim to edit files. So I had to restart the vim then the errors stopped.

```
Error detected while processing function vm#operators#after_yank:
line    1:
E121: Undefined variable: g:VM
Error detected while processing function vm#operators#after_yank:
line    1:
E15: Invalid expression: g:VM.selecting
Error detected while processing function vm#operators#after_yank:
line    1:
E121: Undefined variable: g:VM

```
I'm using the vim-multiple-cursor plugin at the moment but I would really like to switch to your Plugin because it feels more integrated into the vim. I'm a newbie in the vim but I would like to help if you need a hand on making this Plugin work in mac.

**Comment by mg979** [comment]
If you don't get errors using the master branch, use the master branch. But:

* vim version? vim 8.0 is required I think, and in MacOS (terminal) vim maybe is not new enough
* try MacVim if this is the problem

If the problem is the leader, try setting:

```
let g:VM_leader = '\'
```

Then you would use `\` as leader inside VM, and keep using `space` outside of it.
But from what you are saying it could be a problem of vim version being too old.

**Comment by typoman** [comment]
Here is my vim version which I compiled from the source:

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec  2 2018 03:52:24)
macOS version
Included patches: 1-556
Compiled by bahmaneslami@B-M-E.local
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               -perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         +python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
-cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       -lua               -ruby              +writebackup
+dialog_con        +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       -xim
-dnd               +mouse             +startuptime       -xpm
-ebcdic            -mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary        
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework AppKit     -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -ldl -framework CoreFoundation      
```
I changed the leader of the VM using your suggestion, nothing changed. Is there any command that I can execute manually to select all the patterns under the cursor to see if everything works? Also maybe if there are commands list that I can remap to something else, then I might be able to fix it?

**Comment by typoman** [comment]
BTW I also used MacVim, it wasn't different.

**Comment by typoman** [comment]
Thank you for the detailed answer. There is some progress but mostly in MacVim. I prefer to use to  VIm inside the OS X terminal because it has a better text engine. So far every plugin has worked there. Now for the VM if I disable the meta mappings the cursor gets duplicated with control + arrow up or down only in MacVim; nothing happens in the Vim inside the terminal. Also, I realized that using the `/` for the leader of the VM solved the problem for both Vim and MacVim, so I can find all the patterns, although I think `<leader>a` would be a better shortcut. Is there anyway to change it? I also think it's best if the multi-cursor movement happens using `<c-j>` or `<c-k>` instead of arrow keys. This might also solve the problem that control+arrow keys doesn't work in the terminal. After all, it's the Vim way not to use them :)!

**Comment by typoman** [comment]
BTW if I hit `c` after multiple selections, I can change the word. I can I also hit `i` to go to insert mode in the VM successfully, which doesn't work in the vim-multiple-cursor plugin.

**Comment by mg979** [comment]
So you say it's a terminal issue, that ctrl-uo/down don't work there? But does ctrl-n work? Can you change the word with `c`?

About changing the mappings, `<leader>a` is used to align cursors by default. You can change the mappings, though, for example:

```
let g:VM_maps["Select All"]        = '<leader>a'
let g:VM_maps["Visual All"]        = '<leader>a'
let g:VM_maps["Align"]             = '<leader>A'
```

This would use leader-a to select all, leader-A to align. I prefer the other way around though.
Same for adding cursors using `ctrl`:
```
let g:VM_maps["Add Cursor Down"]   = '<C-j>'
let g:VM_maps["Add Cursor Up"]     = '<C-k>'
```

Full mappings are [here](https://github.com/mg979/vim-visual-multi/wiki/M.-Mappings#full-mappings-list).

About terminal vim in Mac, if the problem is simply that `ctrl-arrows` don't work, you should try with the mappings above.

**Comment by typoman** [comment]
Yes if I hit `c` after multiple selections, I can change the word. I can I also hit `i` to go to insert mode in the VM successfully, which doesn't work in the vim-multiple-cursor plugin.

I tried your suggestions to change the key bindings by adding them to the vimrc file but I get this on vim startup:

`E121: Undefined variable: g:VM_maps`

No Idea what happened.

**Comment by mg979** [comment]
I forgot, you have to initialize the dict before. In your vimrc:

```
let g:VM_maps = {}
let g:VM_maps["Select All"]        = '<leader>a'
let g:VM_maps["Visual All"]        = '<leader>a'
let g:VM_maps["Align"]             = '<leader>A'
let g:VM_maps["Add Cursor Down"]   = '<C-j>'
let g:VM_maps["Add Cursor Up"]     = '<C-k>'
```

**Comment by typoman** [comment]
Great! Thanks a lot! All works fine. I guess the only feature missing would be the Control + mouse click which I have no idea how it would be possible to make it work. All I know that using Alt+Click takes Vim to the Visual Block Mode so I guess it has to be possible somehow.

**Comment by mg979** [comment]
Try:

```
let g:VM_mouse_mappings             = 1
```

and you should be able to add cursors with ctrl-click, unless in Mac it doesn't work.

**Comment by typoman** [comment]
It works! Many thanks!

**Comment by mg979** [comment]
It's in the [wiki](https://github.com/mg979/vim-visual-multi/wiki/Q.-Quick-start#using-the-mouse) by the way. Read the quick start page, don't trust the pics for the mappings, but you should trust the written text.

[Quick start](https://github.com/mg979/vim-visual-multi/wiki/Q.-Quick-start)
[Mappings](https://github.com/mg979/vim-visual-multi/wiki/M.-Mappings)

**Comment by typoman** [comment]
Some issue I encountered with other Plugins recently. If I use the VM plugin and exit the Multi Visual mode, some other shortcuts stop working. For example, python-mode plugin command :PymodeRun is mapped to <leader>r; in my case it's <space>r. So when I make changes using VM and hit <Esc> twice to exit the multi-visual mode, <space>r doesn't work anymore. I can't guess what would be the cause.

**Comment by mg979** [comment]
Yes it's a bug, I'll fix it. To avoid it for now, you shouldn't use `space` as leader.

**Comment by mg979** [comment]
Can you please try the test branch and tell me if it works now? Please test it with leader `space`. Thanks

**Comment by typoman** [comment]
Sure, when you say `space` leader for the Vim or the leader for the VM? The leader for VM now is `\` and for vim is `space`.

**Comment by mg979** [comment]
Please use `space` for vim, and remove the `g:VM_leader` setting from the vimrc. It should use `\` inside VM anyway, and your other `space` mappings should keep working after exiting VM.

**Comment by typoman** [comment]
It seems to be working now. But again installing the `test` branch causes the Vim to throw errors after the install so it has to be restarted to make them go away. Here are the errors:

```
Error detected while processing function vm#operators#after_yank:
line    1:
E121: Undefined variable: g:VM
Press ENTER or type command to continue
Error detected while processing function vm#operators#after_yank:
line    1:
E15: Invalid expression: g:VM.selecting
Press ENTER or type command to continue

```

**Comment by mg979** [comment]
Ok so it doesn't matter. I don't know what vim-plug does exactly, maybe it reloads the plugin in the same vim session and some function gets funny. Important is that you don't see them in regular use. Can you confirm that on restart the errors don't show up, and the leader mappings work?

**Comment by typoman** [comment]
Yes, absolutely. It works fine now! 👍

**Comment by flowsn4ke** [comment]
> So you say it's a terminal issue, that ctrl-up/down don't work there? But does ctrl-n work? Can you change the word with `c`?
> 
> About changing the mappings, `<leader>a` is used to align cursors by default. You can change the mappings, though, for example:
> 
> ```
> let g:VM_maps["Select All"]        = '<leader>a'
> let g:VM_maps["Visual All"]        = '<leader>a'
> let g:VM_maps["Align"]             = '<leader>A'
> ```
> 
> This would use leader-a to select all, leader-A to align. I prefer the other way around though. Same for adding cursors using `ctrl`:
> 
> ```
> let g:VM_maps["Add Cursor Down"]   = '<C-j>'
> let g:VM_maps["Add Cursor Up"]     = '<C-k>'
> ```
> 
> Full mappings are [here](https://github.com/mg979/vim-visual-multi/wiki/M.-Mappings#full-mappings-list).
> 
> About terminal vim in Mac, if the problem is simply that `ctrl-arrows` don't work, you should try with the mappings above.

How would rebinding Adding Cursor actions syntax be written in vimscript?
