### ISSUE TITLE
control arrow do not work on neovim

### ISSUE THREAD

**Issue by antoinemadec** [mg979/vim-visual-multi#32]
With the lastest neovim compiled from source, and this minimal vimrc:
```
set nocompatible
```

```<C-down>``` and ```<C-up>``` don't start cursors.

**Comment by mg979** [comment]
neovim still uses `<M-j>` / `<M-k>` by default right now, see [mappings](https://github.com/mg979/vim-visual-multi/wiki/M.-Mappings#options).

If you want to disable mappings with meta keys, set

```
let g:VM_no_meta_mappings = 1
```

I have to remove these inconsistencies between vim versions, sorry.
