### ISSUE TITLE
v:vim_did_enter causes vim7.4 to error out

### ISSUE THREAD

**Issue by antoinemadec** [mg979/vim-visual-multi#34]
Making progress on travis CI I stumble upon this issue:
```
#themes#init:
line    1:
E121: Undefined variable: v:vim_did_enter
```

The ```v:vim_did_enter``` was introduced in vim8 (Patch 7.4.1658), which is very recent.
I grep-ed in my 20+ plugins and ```vim-visual-multi``` is the only one to use it.

Questions:

1. can we do without this variable to allow vim 7.4 user to be able to use this plugin?
2. if not, can we update the plugin to error out with a clear message if vim is too old?

Cheers,
Antoine

**Comment by mg979** [comment]
Replacing that with a variable that is initilalized in the VimEnter block would be trivial (I didn't know `vim_did_enter` was that recent), but it's not the only problem for 7.4 compatibility. As far as I know, lambdas were introduced in vim 8, and there are lambdas everywhere in the plugin. Support for 7.4 would require changes everywhere, I'm not saying it's not possible but right now it isn't. Is there a category of people that still uses 7.4 and not 8?

**Comment by antoinemadec** [comment]
```
Ubuntu LTS 16.04: vim 7.4.1689
Ubuntu LTS 18.04: vim 8.0.1453
Debian Jessie (oldstable): vim 7.4.488
Debian Stretch (stable): vim 8.0.0197
Debian Buster (testing): vim 8.1.0549
```

And that is for distros that are more like personal machine distros.
In a work environment (RHEL, CentOs etc) it is very common to see ```vim 7.2```.

I compile vim from source, so I don't care that much.
Also, if ```vim8``` features are needed, this is OK to make this plugin require ```vim8```.

My point is that you should check the vim version at startup and make sure it is compatible with your plugin.
Otherwise, if your plugin becomes popular, you will see a lot of people opening issues like this one.

What do you think?

**Comment by mg979** [comment]
Ok, I don't think there is anything that *requires* vim 8. I'll have to convert those lambdas and test it in older vim versions. I'll do it later when the rest of the plugin is in a better shape. I still have to improve certain aspects and there are still bugs that pop up from time to time. It should be possible though to have it run in 7.4 or older.

**Comment by mg979** [comment]
Current test branch should be compatible with vim 7.4.330 (anything before that will never work because `matchaddpos()` was introduced in that patch).
