### ISSUE TITLE
nvim adds trailing spaces at the end of each line

### ISSUE THREAD

**Issue by antoinemadec** [mg979/vim-visual-multi#36]
Nvim seems to add trailing space at the end of each line when Vim does not.

```
> nvim --version
NVIM v0.3.2-974-g8b9f6103b
```

Once #35 is merged, you can try:
```
./test.py --nvim example
```
and diff the expected and generated output files.

**Comment by mg979** [comment]
VM adds those trailing spaces and then removes them, maybe nvim fails to remove the trailing spaces for some reason, I'll look into it.

**Comment by mg979** [comment]
Fixed in test
