### ISSUE TITLE
Map Exit VM

### ISSUE THREAD

**Issue by salah-saleh** [mg979/vim-visual-multi#39]
Hi, I was trying to map 'Exit VM' to something else other than Esc but it didn't work, is it possible at all?

**Comment by mg979** [comment]
Not possible. Why do you want to do that?

**Comment by salah-saleh** [comment]
Reaching for the Esc key is both annoying and slow. Also in insert mode, pressing esc key multiple times quickly doesn't exit VM for me, I have to wait a sec to exit insert mode, and then press esc again to exit VM :) I wish I can use Ctrl-C for that and map case sensitive to something else.

**Comment by salah-saleh** [comment]
Yes I have some mappings with esc in insert mode, the thing is I don't want to disable them :D 
What is against using <C-c> to exit VM?

**Comment by mg979** [comment]
> What is against using to exit VM?

Against using what?

> the thing is I don't want to disable them :D

I don't know how you can bear to wait 1s every time you exit insert mode. Imo you should correct your setup, Esc is the most obvious key to exit VM and causes no problems with a correct setup (imo).

**Comment by salah-saleh** [comment]
The situation with the Esc key is basically because of me using the Cursors in insert mode (which I find useful in many situation and for other mappings)

**Comment by salah-saleh** [comment]
I just found a good solution here that fixed the delay time with Esc https://www.johnhawthorn.com/2012/09/vi-escape-delays/
I am quite a newbie to vim, and still learning so still facing a lot of these issues for the first time. Thanks for bearing with me :)

**Comment by mg979** [comment]
No problem, I also use

    set timeoutlen=3000 ttimeoutlen=10
