### ISSUE TITLE
How set up the plugin   for deoplete.nvim correctly?

### ISSUE THREAD

**Issue by pittcat** [mg979/vim-visual-multi#4]

**Comment by pittcat** [comment]
My settings are as follows,

   let g:deoplete#enable_at_startup = 0
    " Set minimum syntax keyword length.
    let g:min_pattern_length=2

    " delay
    let g:deoplete#auto_complete_delay=0
    " auto_refresh
    let g:auto_refresh_delay=0
    
    let refresh_always=true
    autocmd InsertEnter * call deoplete#enable()

    fun! VM_before_auto()
        call MacroBefore()
    endfun

    fun! VM_after_auto()
        call MacroAfter()
    endfun

    function! MacroBefore(...)
        unmap s
        unmap S
        let b:deoplete_disable_auto_complete = 1
    endfunction!

    function! MacroAfter(...)
        nmap s <plug>sneak_s
        nmap S <Plug>Sneak_S
        let b:deoplete_disable_auto_complete = 0
    endfunction!
When cursor moves,the popup will appear,which is annoying .

**Comment by mg979** [comment]
Thanks for the report, I pushed a fix for this in the test branch, if you can try it.

**Comment by mg979** [comment]
Ok thanks, test branch has some other changes so if something is working strange please tell me :)
