### ISSUE TITLE
vim-visual-multi disables vim-indent-guides plugin

### ISSUE THREAD

**Issue by subev** [mg979/vim-visual-multi#42]
Hello,

I recently started using "nathanaelkane/vim-indent-guides" and it seems that when I enter visual-multi it disables the guides, I don't mind that but when I exit it is not enabled back. 
In details it actually looks the guides are not actually disabled but are not rendered or smth, is there a work around for this or smth? Maybe use some event and re-render the guides?

**Comment by mg979** [comment]
Try:

```vim
function VM_Exit()
  IndentGuidesEnable
endfunction
```
