### ISSUE TITLE
Selection si" fail when bracket is surrounded

### ISSUE THREAD

**Issue by ipod825** [mg979/vim-visual-multi#44]
Given the following  text ( where the cursor is before the first "Visual"):
```
let g:VM_maps["|Visual Regex"]                = 'g/'
let g:VM_maps["Visual All"]                  = '<leader>A'
```
Key Stroke: `<C-n><C-n>si"`

Result: the two rightmost " are selected while they are not expected to be selected.

**Comment by mg979** [comment]
Thanks for reporting, it should be fixed on the test branch. Please confirm that it's fixed for you too, if you can try it. Thanks

**Comment by ipod825** [comment]
Yes. It works properly now. Thanks!

**Comment by mg979** [comment]
Thanks
