### ISSUE TITLE
CocList opens when performing a multi-cursor delete 

### ISSUE THREAD

**Issue by Avi-D-coder** [mg979/vim-visual-multi#45]
Cross issue: https://github.com/neoclide/coc.nvim/issues/489
**Describe the bug**
Using [vim-visual-multi](https://github.com/mg979/vim-visual-multi) multi cursor delete with [coc.nvim](https://github.com/neoclide/coc.nvim) causes `CocList` to open.

Config that causes issue:
```vim
nnoremap <silent> "" :<C-u>CocList<cr>
```

![ezgif-2-8cb77a0619df](https://user-images.githubusercontent.com/29133776/53850076-114ef480-3f88-11e9-8a7c-a475a8230bb7.gif)

**Comment by mg979** [comment]
What happens if you press `df&` outside VM? For operations  at cursors, I'm using recursive mappings on purpose (so that custom text objects work), but that could trigger unusual mappings from plugins.

**Comment by Avi-D-coder** [comment]
Without vim-visual-multi loaded `df&` behaves normally.

**Comment by mg979** [comment]
Are those diagnostics bound to a mapping, and which one? Or do they appear automatically when they think they caught an error, so by autocommand?

**Comment by mg979** [comment]
Ok sorry, I didn't read that `""` remapping and I could reproduce it. Certainly it's the cause. The VM command issues `""df&` and that triggers your mapping. I should omit the register when it's `"`, right now it can't work with your mapping, I'll fix it soon.

**Comment by Avi-D-coder** [comment]
Thanks

**Comment by mg979** [comment]
It should be fixed in the [test branch](https://github.com/mg979/vim-visual-multi/wiki#master-and-test-branches). Please confirm if it's fixed for you too.

**Comment by Avi-D-coder** [comment]
Fixed. Thanks
