### ISSUE TITLE
Number ctrl-up/down should repeat n + 1 times

### ISSUE THREAD

**Issue by Avi-D-coder** [mg979/vim-visual-multi#47]
In gif `7<C-Down>` adds cursors to relative line `6` because vim relative line commands start at `0` not `1`.

![ezgif-2-8cb77a0619df](https://user-images.githubusercontent.com/29133776/53850076-114ef480-3f88-11e9-8a7c-a475a8230bb7.gif)

**Comment by mg979** [comment]
Yes it's the current default behaviour. I thought it would have been easier to think `count` as the number of created cursors, rather than the motion as in `7j`. In fact `<c-down>` and `2<c-down>` have the same effect, right now. It could be changed to better match vim behaviour in these cases.

**Comment by Avi-D-coder** [comment]
The `count` being different adds mental overhead. I would suggest the default behavior match vim motions, so people starting out are not confused.

**Comment by mg979** [comment]
I'll change it. Consider also that it will skip shorter lines, so a perfect identity with vim motions won't be there in those cases.

**Comment by Avi-D-coder** [comment]
Would it be possible to make motion version of that matches vim's behavior completely?

**Comment by mg979** [comment]
Can you try it now? You must set:
```
let g:VM_skip_shorter_lines = 0
```
Default is going to stay 1 because I think it's better in most cases. You can also set a mapping to toggle it as needed.

**Comment by Avi-D-coder** [comment]
Works great!
Thanks
