### ISSUE TITLE
Revised mappings system

### ISSUE THREAD

**Issue by mg979** [mg979/vim-visual-multi#49]
I can summarize changes as follow:

* there is a default `g:VM_leader`: it is `\\` (two backslashes)
* most mappings will use it: alignment becomes `\\a`, select all becomes `\\A`, etc
* adding single cursors at position is done with `\\\`
* mappings that were using `z` key will use it: `\\z` (run normal command), `\\@` (run macro), etc
* even the `gs` operator uses it: `\\gs` (`gs` is easily remapped and I don't want to overwrite it)
* examples of mappings that *don't* use it: maps with arrows, `c-n`, `Tab`, `s`, `m`, `R`, `S` and mappings that replicate vim functionalities at cursors (`c`, `d`, `p`, `y`, `~`, `.`, `c-a`, `c-x`, etc)
* `<space>` (toggle mappings), `<cr>` (single region mode), `<bs>` (block mode): they all use the leader

Basically, most VM-specific commands will use it, simple reimplementation of *basic* vim commands won't.
 
-----------

But the most important thing is: ***VM buffer mappings won't overwrite anymore other buffer mappings, set by other plugins***. Even if using a dedicated leader can solve many issues, many commands won't use it. If you have plugins (eg ftplugins) that apply a lot of buffer mappings, there could be clashes and VM won't overwrite those mappings anymore. This can also happen with insert mode mappings (since they can't use the leader).

----------

#### Debugging mapping conflicts

If there are clashes, you'll be notified when you run VM in a buffer for the first time: you can then run
```
:VMDebug
```
in that buffer, to see what mappings couldn't be applied, and what is using them instead.

--------

#### Skip mappings check

If you want, you can skip all checks and let VM mappings always take over:

per buffer, with an autocommand on BufEnter, maybe per filetype:
```
let b:VM_check_mappings = 0
```
or with a global variable (applied on all buffers):
```
let g:VM_check_mappings = 0
```

--------

#### Force individual mappings

per buffer, with an autocommand:
```
let b:VM_force_maps = [ a list of mappings, eg '\\a', 'd', 'y' ]
```

or globally:
```
let g:VM_force_maps = [ a list of mappings, eg '\\a', 'd', 'y' ]
```

**Comment by masaeedu** [comment]
Hi @mg979. Would you be willing to consider making <leader><Spacebar> simply toggle a cursor at the current position instead of repeatedly adding multiple cursors? If a cursor is already present at the current position it will remove it, and vice versa.

**Comment by mg979** [comment]
@masaeedu could you please open an issue for this? I should have locked this one.
