### ISSUE TITLE
How can I disable/change <c-j> <c-k> and <tab> imap?

### ISSUE THREAD

**Issue by diegonogueira** [mg979/vim-visual-multi#5]
Hi! How can I disable or change the <c-j> <c-k> and <tab> imaps? 
I'm using these maps to autocomplete(deoplete).

thanks

**Comment by mg979** [comment]
I'll remove the `<c-h> <c-j> <c-k> <c-l>` mappings in insert mode (not necessary anymore). But I didn't define a `<tab>` imap mapping, what's the issue you're having with that?

**Comment by mg979** [comment]
`<c-h> <c-j> <c-k> <c-l>` mappings in insert mode have been removed in the test branch now.

**Comment by diegonogueira** [comment]
Thanks!

I found the problem with <tab>.. It's my autocomplete map.. :(

:)

**Comment by mg979** [comment]
Ok thanks, be sure to use the test branch for the `<c-h> <c-j> <c-k> <c-l>` mappings.
