### ISSUE TITLE
The plugin can't works well with machakann/vim-highlightedyank.

### ISSUE THREAD

**Issue by pittcat** [mg979/vim-visual-multi#50]

**Comment by pittcat** [comment]
vim-visual-multi can have good cooperation with neoclide/coc-yank,and I have switched to coc-yank.

**Comment by pittcat** [comment]
![bug](https://user-images.githubusercontent.com/22888402/54269666-b71de700-45b8-11e9-9bc5-d622f1deb86a.png)

The picture above shows the problem that vim-visual-multi works with machakann/vim-highlightedyank.

**Comment by mg979** [comment]
If the problem is related to highlight matches, you can try:
```
let g:VM_clear_buffer_hl = 0
```

and see if machakann/vim-highlightedyank works.

**Comment by mg979** [comment]
Also, now in devel branch there is a new function that you can call:
```vim
fun! VM_Start()
  HighlightedyankOff
endfun

fun! VM_Exit()
  HighlightedyankOn
endfun
```

**Comment by pittcat** [comment]
It works like a charm.Thank you for your efforts.:smiley:
