### ISSUE TITLE
Is "let g:VM_sublime_mappings = 1" still  valid? 

### ISSUE THREAD

**Issue by enricozb** [mg979/vim-visual-multi#52]
I was trying to change the `<c-n>` default mapping to `<c-d>`. I found some documentation referring to `g:VM_sublime_mappings`, but even when I set this to `1`, it doesn't make any difference, and `<c-n>` remains. What is the current proper way to set `<c-d>` as my desired mapping for multi-cursor use.

Awesome plugin btw, much faster than `vim-multicursor`.

**Comment by mg979** [comment]
No, it's not valid anymore.

https://github.com/mg979/vim-visual-multi/wiki/Mappings

To change mappings read here:

https://github.com/mg979/vim-visual-multi/wiki/Mappings#customization

**Comment by enricozb** [comment]
This is perfect. Thanks a ton!

**Comment by mg979** [comment]
Be sure to read also [here](https://github.com/mg979/vim-visual-multi/issues/49), thanks.
