### ISSUE TITLE
"Unsynced" transpose while same number of elements are selected on each line

### ISSUE THREAD

**Issue by masaeedu** [mg979/vim-visual-multi#53]
I'd like to be able to perform the "unsynced" transpose where the all elements are rotated around regardless of how many elements are selected on each line. It seems like if I coincidentally have the same number of selections on each line, it goes into the "synced" transpose mode (which in this case I don't want). The undesired behavior is shown below:

![2019-03-24-21-43-51](https://user-images.githubusercontent.com/3674056/54890185-92f6bb80-4e7e-11e9-8807-0b29a80340f5.gif)

**Comment by mg979** [comment]
I didn't consider this, right now it isn't possible. It would need a switch or something, I'll add it in the future.

**Comment by mg979** [comment]
In devel branch it's possible to add a mapping for this, for example:

let g:VM_maps['Rotate'] = '\\T'

It's not mapped by default (default transposition method is the old one)

**Comment by masaeedu** [comment]
Awesome, thank you so much!
