### ISSUE TITLE
Key for toggling cursor on the current position

### ISSUE THREAD

**Issue by masaeedu** [mg979/vim-visual-multi#55]
Instead of (or in addition to) an operation for adding a cursor to the current position regardless of whether there is already a cursor there, it would be useful to have an operation that toggles the presence of a cursor on the current position. For positions that already have a cursor it would simply remove the cursor, and for positions that don't have a cursor it would add one. This would be handy for adding cursors in a number of positions using various motions, then moving back and removing a few.

**Comment by mg979** [comment]
It could be a good idea. Consider that you can already remove single cursors/selection (`q` skips, `Q` removes only), so you should be able to do it with key `Q` already.

**Comment by mg979** [comment]
Cursors can be toggled now (in devel branch)
