### ISSUE TITLE
Reset error with Dracula colorscheme

### ISSUE THREAD

**Issue by sQVe** [mg979/vim-visual-multi#56]
Hey!

I've started getting errors when escaping visual multi, i.e. pressing `<Esc>`. I get the following error:

```
Error detected while processing function vm#reset:
line   43:
E492: Not an editor command:                    links to DraculaSearch
Error detected while processing function vm#reset:
line   43:
E492: Not an editor command:                    links to DraculaSearch
```

Pretty confusing. It starts working as soon as I change `colorscheme` or manually set `:VMTheme`.

https://github.com/dracula/vim

**Comment by mg979** [comment]
Yes I'm getting the same with Dracula. I'm looking for the cause.

**Comment by mg979** [comment]
Ok the problem is that it uses highlight linking, I'm working on a fix.

**Comment by sQVe** [comment]
@mg979 As responsive as always. Many thanks. :pray:

**Comment by mg979** [comment]
It should be fixed in the test branch. By the way, if you're using deoplete, could you tell me if it's working ok? Because I made changes that should make it work normally (without workarounds such as manual completion with tab). Thanks for reporting

**Comment by sQVe** [comment]
@mg979 I actually moved away from deoplete today to coc.nvim. So, I can't test it easily. I'll try it with coc later today though.

**Comment by mg979** [comment]
Ok if you don't use it no problem. If you confirm the fix is working I'll merge it into master.

**Comment by sQVe** [comment]
@mg979 Works fine with my setup now!
