### ISSUE TITLE
E118: two many arguments error

### ISSUE THREAD

**Issue by SolaWing** [mg979/vim-visual-multi#57]
git: master head: 7ef1e1c2e00091200bae8e8ec8dfa6a5c3ab0188

reproduce: enter multi-cursor, then exit.

seems there are many function omit the param in definition.

like `fun! s:ftype()` in `vm/comp.vim`

**Comment by mg979** [comment]
Thanks for reporting. Can you please confirm it's fixed?

**Comment by SolaWing** [comment]
autoload/vm/special/help.vim:fun! s:Pad()
autoload/vm/special/help.vim:  return b:VM_Selection.Funcs.pad(a:t, a:n, 1)
autoload/vm/special/help.vim:endfun
autoload/vm/special/help.vim:fun! s:Sep()
autoload/vm/special/help.vim:  return b:VM_Selection.Funcs.repeat_char(a:c)
autoload/vm/special/help.vim:endfun

these function still has error

**Comment by mg979** [comment]
Could you please try it now? Thanks

**Comment by SolaWing** [comment]
it looks good now

**Comment by mg979** [comment]
Thanks
