### ISSUE TITLE
Down arrow behaves like right in multi mode.

### ISSUE THREAD

**Issue by Avi-D-coder** [mg979/vim-visual-multi#58]
Expected behavior is to select next pum item.
![ezgif-4-f8e8a5b8dc46](https://user-images.githubusercontent.com/29133776/56634992-f0268e00-6631-11e9-8a83-233e2a6720ba.gif)

**Comment by mg979** [comment]
Yes, it's not checking for the popup. I'll fix it, you can use `c-n/c-p` for now (or tab if you have mapped it)

**Comment by mg979** [comment]
It should be fixed in test branch, you can tell me if it works as expected.

**Comment by Avi-D-coder** [comment]
Thanks
