### ISSUE TITLE
[Feature request] Stop matching when hitting the last match

### ISSUE THREAD

**Issue by ipod825** [mg979/vim-visual-multi#59]
It would be nice to stop the matching when `Find Under` and `Visual FInd` hits the last match and jumps back to the first match. Currently, it will continue matching so I need to look into line number to ensure that I've hit the first match again.

**Comment by mg979** [comment]
If you mean the last match in the file, you could simply type `mG` to find all matches until the end of the file, is this what you mean?

[Find operator](https://github.com/mg979/vim-visual-multi/wiki/5.-Operators#find-operator)

**Comment by ipod825** [comment]
`mG` does not select matches previous to the starting match. I know that there's a mapping to select all matches. But it does not work if you also want to skip some occurrences. Cycling through matches after selecting and cancelling some of them would work but again, you'll miss where you start as the cycling does not end.

**Comment by mg979** [comment]
I can add a warning when wrapping to the begin of the file, as vim does. I can also prevent the error when a match is not found and `nowrapscan` is set, so that you can do:

```vim
fun! VM_Start()
  set nowrapscan
endfun

fun! VM_Exit()
  set wrapscan
endfun
```

Basically I want VM to follow vim settings as closely as possible, so if you have `wrapscan` set, VM will use it too.

**Comment by ipod825** [comment]
It's not about the begin/end of the file. It's about hitting the first match again. For example, if the file looks like:
```
foo
|foo
foo
```
Selecting the second foo using `<C-n>` and continue pressing `<C-n>` would continue to select the third and the first foo. I would like vim-visual-multi to stop (or print a warning) at the first foo.

**Comment by mg979** [comment]
Understood, then a warning when reselecting a region.

**Comment by mg979** [comment]
This should work in the test branch, but you should add the setting:

```
let g:VM_notify_previously_selected = 1
```

This simply notifies in the command line, to stop selecting would need an entirely different command, it's possible to do it but obviously it couldn't be the default.

**Comment by ipod825** [comment]
This works fine. Though it would be even better to have an option to stop the selection entirely. Do you think a callback `VM_on_select` (just like `VM_Start` and `VM_Exit` above) is doable?

**Comment by mg979** [comment]
Ok now it should notify if you set
```
let g:VM_notify_previously_selected = 1
```

and stop entirely if you set
```
let g:VM_notify_previously_selected = 2
```

Can you update test branch and report? Thanks

**Comment by ipod825** [comment]
Works as expected. Thanks a lot.

**Comment by mg979** [comment]
Just a note: this will prevent reselection of any previously selected region with find_next/find_previous, but it doesn't check patterns, if you add some new pattern you could have trouble finding all patterns you need because you can't leave your last selection. You could add a command/mapping to switch as needed:

```
command! VMToggleReselect
            \ if !get(g:, 'VM_notify_previously_selected', 0)
            \ | let g:VM_notify_previously_selected = 2
            \ | else | let g:VM_notify_previously_selected = 0 | endif
```
