### ISSUE TITLE
Setting up tests

### ISSUE THREAD

**Issue by mg979** [mg979/vim-visual-multi#6]
I'd like to set up some tests, but vim-vader doesn't seem to work (maybe it can't handle buffer mappings, I don't know). I'd try with Vspec, but I couldn't figure out how to set it up (needed programs/installation steps and such). If somebody has experience with it, some hint would be appreciated, thanks.

**Comment by balta2ar** [comment]
Maybe @junegunn or @blueyed could give a hint about the setup but I guess a more specific description of the problem is required.

**Comment by mg979** [comment]
Thanks, I'm giving another try at vader and being slightly more successful, but still not working as I expected. I'll keep trying. It's hard to give a better description because I don't know exactly what's not working. Basically I can't change text in multicursor mode (delete works, but not change or insert).

**Comment by blueyed** [comment]
@mg979 
Some autocmds are not emitted (see README), and you would have to do `doautocmd` yourself.

btw: I am currently experimenting with using Neovim's remove client (via neovim-python-client) for tests of deoplete, which allows to really control and inspect the editor.  Maybe you want to go that route.
Let me know and I can pastebin some fixture(s) for pytest already then.

**Comment by blueyed** [comment]
When you get it working either way, consider using https://github.com/Vimjas/covimerage also (for Vimscript based tests), with the pytest approach you could use coveragepy directly, of course - but covimerage makes sense then additionally (to see what Vimscript is covered when using neovim-python-client); haven't experimented with that yet though.

**Comment by mg979** [comment]
@blueyed thanks, I'll try to do what I can with vader first (I had read the warning about aucmds, but the first try didn't go well), I could already add a basic test that doesn't start insert mode.

I'll also try to figure out how to run tests with neovim-python-client, if it can work better.

Not sure how coveragepy could help me though, is that for performance profiling? Because I just want to keep regressions on check for now. Thanks

**Comment by blueyed** [comment]
covimerage/coveragepy report coverage, i.e.. how much of your code is covered in tests.
covimerage builds on top of coveragepy, and uses Vim's :profile to get this information.  covimerage is basically coveragepy for Vimscript, whereas coveragepy is for Python.  First get your tests working though.. :)

**Comment by blueyed** [comment]
Check out https://github.com/neomake/neomake/blob/master/Makefile maybe - I am using Vader there, and it also uses vim-testbed to test different Vim versions in Docker.
But for starters you might want to check the part(s) that run Vader locally.

**Comment by blueyed** [comment]
Vader is a bit tedious to setup, a cli would be good (https://github.com/junegunn/vader.vim/issues/156).

See also https://github.com/junegunn/vader.vim/pull/107 for better reporting of error locations (but that would be a second step after you have it running already).  I will likely merge this soon anyway, so you could also just wait.

**Comment by mg979** [comment]
Right now I just run tests with

```vim
nnoremap <silent>    <leader>V      :Vader t/*<cr>
```

from inside vim, do I need more than that :stuck_out_tongue:?

If I can't make much progress with vader (because of impossibility to reproduce commands inside of it, for example `feedkeys()` not working makes everything more difficult), then I'll have to find an alternative for insert mode stuff.

If I can do that with `neovim-python-client` I could try that, but I have no idea how to setup tests of a vim plugin with it, is there some example around? Thanks for your time

**Comment by blueyed** [comment]
> do I need more than that

You want to run it in CI in the end, no? :)

Pushed my WIP using pytest here: https://github.com/Shougo/deoplete.nvim/pull/807/files

The main thing is the `nvim` fixture, and it can be created manually, e.g. in an ipython shell.
When using $NVIM_LISTEN_ADDRESS of a running Neovim instance, you can then control it from Python, e.g. `nvim.feedkeys('A')` - see the test itself for special characters like backspace.

Much saner that writing Vader tests if it gets complicated - no need for funky timers/callbacks and `!` with feedkeys etc.

**Comment by mg979** [comment]
Thanks. I'm giving up with vader except for things that it can easily work with. I'll try to setup a pytest like yours.

**Comment by antoinemadec** [comment]
I am making good progress with vimrunner for python.
Will keep you posted.

**Comment by antoinemadec** [comment]
@blueyed correct.
This is maybe not maintained anymore but it works well and the setup is easy.

Using a python script and the vim server/client interface seems better than using vimscript.
That way -on top of checking the plugin keys combinations- we can easily measure time, fork tests etc.

What do you think?

**Comment by blueyed** [comment]
Yes, client/server is great, but often not needed - e.g. with Neomake using Vader is fine.

I've stopped with the tests for deoplete, but using pytest and its fixtures it is really trivial to get this going, and I would rather go that route.  Check out https://github.com/Shougo/deoplete.nvim/pull/807 maybe if you haven't yet.

I recommend not using something unmaintained in general (but maybe you could help there then if it turns out to be good, of course), and it appears to be a drawback that only Vim is supported, but not Neovim (but that's just the other way around for my WIP, and Neovim might be easy to add for vimrunner).

**Comment by antoinemadec** [comment]
For Neovim to be supported by vimrunner, we just needed to create wrapper supporting:
```
nvim_wrapper --serverlist
nvim_wrapper --servername
```
And create the server like this:
```python
vimrunner.Server(executable=nvim_wrapper)
```
Here is what is needed to run a vimrunner test:
https://github.com/antoinemadec/vim-visual-multi/blob/master/test/test.py

I like the simplicity of it and the fact that this allow us to use python instead of vimscript.
Regarding pytest, it does not seem to be flexible nor simple enough to use.

I'd rather use something simple, robust and custom.
What do you think?

**Comment by antoinemadec** [comment]
I created a small flow that allows to create new tests rather simply, without modifying the script.
We can later on build up on this and check time (by adding a output/time/expected for instance) or other neat features.

Everything is explained in the README.md. 

Let me know what you think:
https://github.com/antoinemadec/vim-visual-multi/tree/master/test

**Comment by mg979** [comment]
@antoinemadec Thanks a lot! I've been trying to run the tests on Windows (can't run Linux on my laptop) but I get an error. I put vimrunning.py in the test directory (the same of test.py):
```
$ ./test.py

#--------------------------------------------------------------
# tests\example
#--------------------------------------------------------------
reproduce: ./test.py tests\example
using default vimrc
Traceback (most recent call last):
  File "./test.py", line 61, in <module>
    run_one_test(test)
  File "./test.py", line 33, in run_one_test
    command_path = Path('tests/', test, 'commands.py').resolve(strict=True)
  File "D:\Gianmaria\Scoop\apps\python\current\lib\pathlib.py", line 1123, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "D:\Gianmaria\Scoop\apps\python\current\lib\pathlib.py", line 184, in resolve
    return self._ext_to_normal(_getfinalpathname(s))
FileNotFoundError: [WinError 3] Impossibile trovare il percorso specificato: 'tests\\tests\\example\\commands.py'
```

I looks like it searches the files in the wrong directory, but I guess you had it working on Linux?

**Comment by antoinemadec** [comment]
Yes, this works on linux. Will fix it for windows tomorrow.

**Comment by antoinemadec** [comment]
I updated my test to make it windows compliant.
Vimrunner has to be slightly modified to make add support for Windows:
  https://github.com/andri-ch/vimrunner-python/pull/12

Could you please try with my new commit and the vimrunner modifs?
I just have an issue on my side, I cannot send ```:somecommand \<CR>``` with the vim version I have for windows. It appears to be Vim related and not vimrunner related. It might work for you.

Please let me know if this works for you.

Is Windows support a must have? If so, we could investigate this plugin for Neovim:
  https://github.com/neovim/pynvim

I won't have much time in the future, but my script can easily refactor to use pynvim if you feel like it.

Thanks,
Antoine

**Comment by mg979** [comment]
> Is Windows support a must have?

Sorry if it took some more time to do that, I thought it was something trivial. Windows tests aren't important, if they work well in Linux. I just can't run Linux on my laptop because wifi isn't recognized but I will test them on Linux as soon as I can. I tried the modified vimrunner but I still get the same error. I will try now with a Linux USB stick and see if I can run them there. Just don't bother with Windows support for tests anyway, thanks a lot for what you've done already :)

**Comment by mg979** [comment]
Ok updated but I get different errors, I'll try on Linux in a couple of days.

**Comment by antoinemadec** [comment]
I just created a test using Neovim (with pynvim):
https://github.com/antoinemadec/vim-visual-multi/tree/nvim/test

**Comment by mg979** [comment]
@antoinemadec I'm trying the tests in Linux with vimrunner.
Doing this with an USB stick with Debian stable (python 3.5.3)

I get this error:

```
$ python3 ./test.py

#--------------------------------------------------------------
# example_bad
#--------------------------------------------------------------
reproduce: ./test.py example_bad
Traceback (most recent call last):
  File "./test.py", line 89, in <module>
    main()
  File "./test.py", line 75, in main
    if run_one_test(test, f) is not True:
  File "./test.py", line 36, in run_one_test
    vimrc_path = Path('tests/', test, 'vimrc.vim').resolve(strict=True)
TypeError: resolve() got an unexpected keyword argument 'strict'
```
If I run the test from within vim with `:!python3 %` it just says:
```
#--------------------------------------------------------------
# summary: SUCCESS
#--------------------------------------------------------------
```
even if I change the example to be wrong. Not understanding what's going on...

**Comment by mg979** [comment]
I tried to delete the `strict` parameter, but I get a different error:

```
$ python3 ./test.py

#--------------------------------------------------------------
# example_bad
#--------------------------------------------------------------
reproduce: ./test.py example_bad
using default vimrc
Traceback (most recent call last):
  File "./test.py", line 89, in <module>
    main()
  File "./test.py", line 75, in main
    if run_one_test(test, f) is not True:
  File "./test.py", line 43, in run_one_test
    gen_out_file_path = Path('tests/', test, 'generated_output_file.txt').resolve()
  File "/usr/lib/python3.5/pathlib.py", line 1109, in resolve
    s = self._flavour.resolve(self)
  File "/usr/lib/python3.5/pathlib.py", line 330, in resolve
    return _resolve(base, str(path)) or sep
  File "/usr/lib/python3.5/pathlib.py", line 315, in _resolve
    target = accessor.readlink(newpath)
  File "/usr/lib/python3.5/pathlib.py", line 422, in readlink
    return os.readlink(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/demo/.vim/my_plugins/visual-multi/test/tests/example_bad/generated_output_file.txt'
```

**Comment by antoinemadec** [comment]
Debian_GNULinux_bustersid (Debian testing, up to date)
Python 3.6.7
> pip3 show vimrunner
Name: vimrunner
Version: 1.0.3

From the logs you are not using the latest version of my repo.
Could you please update and try again, both the 'master' branch and the 'nvim' branch?

Thanks,
Antoine

**Comment by mg979** [comment]
@antoinemadec Thanks and sorry for the long silence, my laptop hates linux, but I've been making good progress, I could install a newer python version with [pyenv](https://github.com/pyenv/pyenv) so now I can run the tests (nvim tests fail but probably a mapping issue). Still not perfect (the last example dowsn't report success or fail and I see no summary as for nvim) but I was using it on top of an older VM commit so maybe that's the problem. Unfortunately I'll be stuck with my laptop in the next days, I'll try to install linux with virtualbox or something.

**Comment by antoinemadec** [comment]
@mg979 no problem. Havent had a lot of time either lately.
I will finish setting up travis CI when i have more time.

Happy holidays 🎅

**Comment by mg979** [comment]
@antoinemadec Thanks to you too :). I could get the tests running in virtualbox, I had to make a couple of changes in the test.py file, introducing a delay because it was misbehaving on my system, but it seems to work fine. I also added an option for a different default vimrc, and to get a vimrc (or test) description from a vimrc file.

If you want to test it, the edited test.py is [here](https://gist.github.com/mg979/9783dad2b23b96579a6ce875e05a4962). If it's ok then you could make a PR if you want (but please rename the test directory "vimrunner" and use the test branch as base). Thanks.

**Comment by antoinemadec** [comment]
Can you please create a pull request on my repo? Ill take a look at it when i have time 😊

**Comment by mg979** [comment]
Ok, but your repo is based on master, it should be based on the test branch at least. Can you fix that? Making another branch from test.

**Comment by antoinemadec** [comment]
This won't affect your repo, could you please merge it on my master?
When it's time to merge it back on your repo, we will be able to do it on
whatever branch you want.

Thanks,
Antoine

**Comment by mg979** [comment]
Ok done but the example2 test will fail on master because of a bug. Travis can't find vimrunner so... PR is there though.

**Comment by antoinemadec** [comment]
@mg979 can we close this issue now that #37 has been merged?

**Comment by mg979** [comment]
Yes
