### ISSUE TITLE
Multiple cursors in a row, append, backspace [last line of file]

### ISSUE THREAD

**Issue by balta2ar** [mg979/vim-visual-multi#60]
Hi! I got this behavior on master and test branches. First, I select all commas using `Ctrl-D`, then press `a` and `<Backspace>`. I'd expect commas to be deleted, but it deletes more than that.
```
$ cat lines.txt
Blue,Brown,Purple,Red,Teal
```

![vis-multiple-in-a-row](https://user-images.githubusercontent.com/340676/58618837-3d022200-82cc-11e9-9eb9-1365835cda34.gif)

Could you please take a look? Thanks!

**Comment by mg979** [comment]
There's currently a bug that affects the last line of the file (in your case also the first one). It's probably been there from the beginning, I still have to fix it. Not sure what's causing it, I'll look into it these days.

**Comment by mg979** [comment]
It should be fixed in both master and test

**Comment by balta2ar** [comment]
Thank you very much!
