### ISSUE TITLE
Hitting escape with selection causes error on small terminals

### ISSUE THREAD

**Issue by jamespharvey20** [mg979/vim-visual-multi#63]
In both vim 8.1.1467 and nvim nightly (v0.4.0 rc series), if I select an area using "Select Cursor Up|Down" or "Select h|l", and hit `ESC`.....

If I'm on a large terminal, I just get the expected message:

````
Exited Visual-Multi.
````

If I'm on a small terminal (like 34 wide x 71 high), I also get an error:

````
Exited Visual-Multi.
Error detected while processing function vm#reset:
line   33:
E492: Not an editor command:
              ctermbg=11^@
           guifg=Black^@
         guibg=Yellow
````

----

I think sometimes `^@` represents a newline character in vim.  Maybe there's something in vim-visual-multi looking at terminal width, and adding newlines, like for menus?  And maybe this formatting function shouldn't be formatting this string?  Just a guess.

----

`:let g:Vm.search_hi` shows.....

If I started the selection on a large terminal:

````
g:Vm.search_hi         hi! Search ctermfg=0 ctermbg=11 guifg=Black guibg=Yellow
````

But, if I started the selection on a small terminal:

````
g:Vm.search_hi         hi! Search ctermfg=0^@                   ctermbg=11^@                   guifg=Black^@                   guibg=Yellow
````

**Comment by mg979** [comment]
Thanks, it should be fixed, you can reopen it if it doesn't.
