### ISSUE TITLE
[Request] Integration with vim-airline

### ISSUE THREAD

**Issue by jamespharvey20** [mg979/vim-visual-multi#64]
[Your wiki](https://github.com/mg979/vim-visual-multi/wiki/3.-Infoline#integration-with-lightlinevim) shows how to integrate with lightline.

I'd love to see this integrated with vim-airline, to support showing both cursor and extended mode.  I see `g:Vm.is_active` can be used to show in lightline that the plugin is active.  How would one differentiate further, to tell between cursor and extended modes?

Integration would probably require changes in vim-airline code.  Once I know how to differentiate between cursor and extended modes, I can open an issue with vim-airline and see if they'll add support for it.

EDIT: Ahh, I see.  `g:Vm.is_active` then use `g:Vm.extend_mode` to differentiate.   Opened an issue with [vim-airline](https://github.com/vim-airline/vim-airline/issues/1933) asking for support.

Up to you if you want to close this, help contribute to vim-airline, or leave this open for a while to see what they do.

**Comment by mg979** [comment]
Rather than checking `g:Vm.is_active` I'd use
```vim
" check if VM is active
return exists('b:VM_Selection') && !empty('b:VM_Selection')
```

I'm sure it's possible to achieve airline integration, but I don't know how since I don't use it. I'll add a function that returns some infos that can be useful for statusline integration.

**Comment by mg979** [comment]
You can call a new [function](https://github.com/mg979/vim-visual-multi/wiki/3.-Infoline#integration-with-a-statusline) now, it returns a dictionary with useful infos for a statusline. You should be able to build a statusline section with those. If you have more questions you can reopen this.

**Comment by Shatur95** [comment]
@mg979, What does the status key in the `VMInfos()` function correspond to? It usually returns 'Hsv'.

**Comment by mg979** [comment]
`:h vm-infoline`

It's a bit outdated, it's `m` for mappings, `s` for single region mode, `v` for multiline mode, uppercase when the option is active.

**Comment by Shatur95** [comment]
Yes, I saw this, but was not sure because of the `H` in `Hsv`. `H` stands for "mapping enabled", right?

**Comment by mg979** [comment]
It's `M` not `H`

**Comment by Shatur95** [comment]
Oh, sorry, for unknown reason I thought it was `H`. Yes, it's `M`. Thank you for the explanations.

**Comment by mohityadav7** [comment]
> You can call a new [function](https://github.com/mg979/vim-visual-multi/wiki/3.-Infoline#integration-with-a-statusline) now, it returns a dictionary with useful infos for a statusline. You should be able to build a statusline section with those. If you have more questions you can reopen this.

Hi, It seems like the wiki is missing for statusline integration. I want to integrate with lualine. Could you please help with that?

**Comment by mg979** [comment]
:help g:VM_set_statusline

You can use built-in statusline, change this value to 3 if it gets overwritten. Or you can use the aforementioned function inside lualine, but I can't help you with that.
