### ISSUE TITLE
Meta shortcuts don't work on MacOS

### ISSUE THREAD

**Issue by daniele-orlando** [mg979/vim-visual-multi#7]
Meta key in VIM doesn't work on MacOS (Terminal or iTerm2 app). It means that many VM shortcuts are not accessible.

**Comment by mg979** [comment]
Yes I know. Personally I use terminal vim 8, but I have my scripts to set up Alt+key mappings.
Other alternatives are:

* on option for terminal-friendly mappings (with no meta-keys mappings)
* allow full customization of mappings, by using a copy of the mapping file in ~/.vim/autoload

The first one would be a bit cumbersome. The second one would require a lot of attention by the user (buffer mappings must be both set and unmapped on exit). I can work on option 1 for now.

**Comment by mg979** [comment]
Could you (or somebody else) please tell me if, in MacOS, Alt+arrow keys work? Because in linux (terminal vim) they do, even if other Alt+key combinations don't.

**Comment by mg979** [comment]
Now in terminal vim the option `g:VM_no_meta_mappings` should be active by default.

See the [wiki](https://github.com/mg979/vim-visual-multi/wiki/M.-Mappings#options-and-customization) for details.

I'd still like to know if meta-arrow keys work in MacOs terminal vim.

**Comment by daniele-orlando** [comment]
About first question: from my test ALT+`arrow-key` does the same of `arrow-key`
For example in VIM:
```
i C-v ALT+↓
i C-v ↓
```
produces
```
<Down>
<Down>
```

Same result with `cat` from the shell:
```
$ cat
^[[B^[[B
```

**Comment by mg979** [comment]
Ok thanks, so I'll remove also M-arrows combinations from mappings without meta keys.
