### ISSUE TITLE
(NOT AN ISSUE), why this plugin works so fast, even with the built-in visual insert took awhile

### ISSUE THREAD

**Issue by baIIoon** [mg979/vim-visual-multi#71]
So sorry because this repo dont have `gitter` , just this scratches me a little bit

**Comment by mg979** [comment]
I didn't understand the question, can you elaborate, please? Thanks

**Comment by baIIoon** [comment]
I mean with vim, i visual-block down, then shift+i, to insert multiple line, then after that it delays a little bit then expand. It just the plugin running so fast without any delay, im just curious about that

**Comment by mg979** [comment]
I don't have any delay with visual block `I`, maybe it depends on `ttimeoutlen`? Try this:
```vim
set ttimeout timeoutlen=3000
" low value for <esc>-key not to be confused with an <a-…> mapping
set ttimeoutlen=10
```

**Comment by baIIoon** [comment]
Thank you so much

**Comment by mg979** [comment]
So did it work?

**Comment by baIIoon** [comment]
Screw it, i dont care, im using your plugin now, very good doc, wiki, implementation. Im learning vimscript now, did try to analyzing your code to learn more but give up 'cause it so diffucult at my level :)

**Comment by mg979** [comment]
The code is old and bloated on spots, some parts were written when I didn't know well vimscript, some parts should be even removed because they add nothing, I wouldn't try to learn from it, but thanks :).
