### ISSUE TITLE
[Feature request] recall last cursors

### ISSUE THREAD

**Issue by eyalk5** [mg979/vim-visual-multi#72]
Hi,

It would be useful if there would be an option to recall last cursors, as by accidentally pressing another esc, exiting multi-mode, you might lose considerable work. I expect there would an option to return to the previous state in terms of cursours (suppose no relevant change  has been made).

Thanks.

**Comment by mg979** [comment]
Could you please try test branch? New command is there, default mapping is `\\gS` (or `VM_leader` + `gS`).

**Comment by eyalk5** [comment]
I have tested it, it seems to be working.

**Comment by mg979** [comment]
Updated master with this command.
