### ISSUE TITLE
Restore buffer mappings

### ISSUE THREAD

**Issue by ipod825** [mg979/vim-visual-multi#73]
Hi,
Not sure if this is a general problem. But I found that `<Esc>` mapping was not restored after exiting vim-visual-multi. 

To reproduce, open vim, run `:nnoremap <buffer> <Esc> <Nop>` then enter vim-visual-multi (for e.g. use `<C-n>`). Then press `<Esc>` to exit vim-visual-multi. Now if I type
`:map <Esc>`, I got `No mapping found` while it is expected to show `n  <Esc>       *@<Nop>`.

**Comment by mg979** [comment]
Mappings are not 'restored', the plugin avoids to overwrite them if it finds that the key is already mapped, but I'm not checking for the `esc` key (it will overwite a `esc` buffer mapping).

What kind of buffer maps `esc` as a buffer mapping? Generally they are scratch buffers that would be closed with esc, I don't think it makes sense to enable VM there, and I'd prefer to avoid to make `esc` remappable (what if the remapped key is also used? it couldn't solve the problem for all buffers).

What I would do, is to prevent VM from starting when `esc` has been mapped as a buffer mapping.
Do you have a specific case?

**Comment by ipod825** [comment]
Yes,
my plugin [vim-netranger](https://github.com/ipod825/vim-netranger) uses `<Esc>` as the default mapping to [exit editing mode](https://github.com/ipod825/vim-netranger/blob/93f9516f44d229f033f6bb054a7d476d1c1f43ea/doc/vim-ntranger.txt#L116).

I do think restoring mapping is a better idea, though I know the implementation is kind of tedious. Here's an not-so-sophisticated (global) mapping unmap/restore functions:

```vim
function! Save_mappings(keys, mode) abort
  let mappings = {}
  for l:key in a:keys
    let mappings[l:key] = maparg(l:key, a:mode)
  endfor
  return mappings
endfu

function! Restore_mappings(mappings, mode) abort
  for kv in items(a:mappings)
    if (kv[1]!="")
      execute a:mode.'map '.kv[0]." ".kv[1]
    else
      execute a:mode.'unmap '.kv[0]
    endif
  endfor
endfu
```

**Comment by mg979** [comment]
That method wouldn't work as-is, because `maparg` called that way only returns the rhs, but if the mapping uses `expr`, `silent` etc you wouldn't know it. I can't use it as a method to restore mappings. I tried once with `maparg` as dictionary but it's even more complex and I'm not sure it's reliable either. So the only choices are:

1. custom mapping to exit VM (but then a buffer could map that custom mapping, and `esc` makes the most sense anyway)
2. prevent starting VM if `esc` is mapped as buffer mapping (it should only concern special buffers where VM has no real business)

I prefer option 2.

**Comment by ipod825** [comment]
Would you mind to add a hook on existing VM? That way I can do whatever mapping restore  I want. And for option 2, you just give a warning that there's some mapping conflict while still entering VM.

**Comment by ipod825** [comment]
Something like user defined autocmd.

**Comment by mg979** [comment]
There is already a hook, it's called before mappings are applied:

    :help vm-faq-functions

I should add an autocommand as well.

**Comment by ipod825** [comment]
An autocmd would be better. That way I can integrate this seamlessly without overwriting user's VM_Exit. Thanks!

**Comment by mg979** [comment]
Test branch has User autocommands (`visual_multi_start` and `visual_multi_exit`) if you want to try, thanks

**Comment by ipod825** [comment]
Works as expected. Thanks!
