### ISSUE TITLE
the plugin sets highlighted search 

### ISSUE THREAD

**Issue by eyalk5** [mg979/vim-visual-multi#74]
Hi,

Even if highlighted is off to begin with(like in my case), the plugin still executes `set hlsearch` at times, ignoring my preferences.  

Could it please be fixed? 

Tired of doing :noh :)

**Comment by mg979** [comment]
The plugin needs `hlsearch` to highlight unselected matches, it's very hard to work with `hls` from scripts, because they don't work if set from scripts.

I'll try to fix it, for now the easiest solution is to have `set hlsearch` in your vimrc (it should start disabled anyway).

**Comment by ipod825** [comment]
An easy fix would be to save the user options on visual_multi_start and restores them on visual_multi_exit.

**Comment by mg979** [comment]
@eyalk5 It should be fixed in the test branch, please report if it works for you

**Comment by mg979** [comment]
I had to revert that 'fix' because it introduced more problems. The fix is really easy, just put in your vimrc:
```vim
set hlsearch
```

**Comment by eyalk5** [comment]
I don't want highlighted search for every search I do. So far, I have disabled manually all the cases you do set hisearch and it worked fine. Thanks anyway

**Comment by mg979** [comment]
@eyalk5 understood, then I'm simply not enabling search highlight if it was disabled. You could update test branch, it's working this way.

**Comment by mg979** [comment]
Should be fixed on master, reopen if necessary, thanks.
