### ISSUE TITLE
Changes to some default mappings

### ISSUE THREAD

**Issue by mg979** [mg979/vim-visual-multi#76]
I'm going to change the default mappings for Find Next/Find Previous:
```
Find Next          ] -> n
Find Previous      [ -> N
Goto Next          } -> ]
Goto Previous      { -> [
```
This is already effective in the master branch.

I'm doing this to keep default mappings closer to vim defaults. If you then want the old behaviour:
```
let g:VM_maps = {}
let g:VM_maps["Find Next"] = ']'
let g:VM_maps["Find Prev"] = '['
let g:VM_maps["Goto Next"] = '}'
let g:VM_maps["Goto Prev"] = '{'
```

**Comment by keitoku-c** [comment]
I encountered an issue with changing mappings.
when I try to use 'x' to skip selection by doing
```
let g:VM_maps = {}
let g:VM_maps["Skip Region"] = 'x'
```
it doesn't take effect and pressing 'x' still cuts a char.
even if 'x' has been mapped to <nop> in normal mapping.

**Comment by mg979** [comment]
And before the change it worked differently? I find it strange that it could work before.
Try remapping also `x` and `X`:
```
let g:VM_maps["x"] = 'q'
```
But why would you switch `q` with `x`? `x` is a useful key, especially with multiple cursors, and `q` is easy anyway.

**Comment by keitoku-c** [comment]
Now it works as expected after mapping 'x' to 'q'.
I am not sure if it works or not previously. This switching is just something to do with my usual practice.

**Comment by mg979** [comment]
Probably x is mapped before Skip Region, so when you try to map it it's already been mapped. Remappings work so, that if a key is mapped already, it is skipped. It works so for other plugins mappings, but also for VM itself.
