### ISSUE TITLE
vim-visual-multi does not work well with vim airline

### ISSUE THREAD

**Issue by blayz3r** [mg979/vim-visual-multi#77]
![image](https://user-images.githubusercontent.com/12205650/64744680-bbc54880-d4d2-11e9-8f67-2c1bf39c7057.png)
![image](https://user-images.githubusercontent.com/12205650/64744708-d992ad80-d4d2-11e9-80bc-2a4948600839.png)
The "Exited Visual-Multi" message seems to remain longer than I would like. Can it go away after a while.

**Comment by mg979** [comment]
What is the problem exactly?

If you don't want the exit message:

    let g:VM_silent_exit = 1

If you don't want the custom statusline:

    let g:VM_set_statusline = 0

See `:help visual-multi-settings`

**Comment by blayz3r** [comment]
Thanks
