### ISSUE TITLE
Custom vim-surround bindings

### ISSUE THREAD

**Issue by enricozb** [mg979/vim-visual-multi#78]
I have custom `vim-surround` bindings such as
```
vmap ( S)
vmap ' S'
vmap " S"
vmap { S}
```
These make it so that the behavior to surrounding a selection is very similar to Sublime Text's. These do not work when using `vim-visual-multi`. It's as if these vmaps don't exist at all when using multiple cursors.

Is there any way to have the functionality of selecting multiple selections (using `vim-visual-multi`), and then pressing a key such as `(` and having each selection surrounded? I'd imagine there should be a way to write a custom command in the same spirit as [n/i/v]map, and have it apply to each selection.

Here is my full list of `vim-surround` maps of this form:
```
vmap ( S)
vmap ' S'
vmap " S"
vmap { S}
vmap [ S]

" markdown
vmap _ S_
autocmd FileType vimwiki,markdown let g:surround_95 = "[\r]()"

" latex
vmap ` S`
autocmd FileType latex let b:surround_96 = "``\r''"
autocmd FileType latex vmap $ S$
autocmd FileType latex vmap \| S\|
```

**Comment by mg979** [comment]
You could do like this:

```vim
fun! VM_Start()
  nmap <buffer><nowait> ( S)
  nmap <buffer><nowait> ' S'
  nmap <buffer><nowait> " S"
  nmap <buffer><nowait> { S}
  nmap <buffer><nowait> [ S]
endfun

fun! VM_Exit()
  unmap <buffer> (
  unmap <buffer> '
  unmap <buffer> "
  unmap <buffer> {
  unmap <buffer> [
endfun
```

But it's normal mode, so you're overriding default functionalities (" for registers, [ for cycling regions) just to save one keystroke.

You could remap [ and ], but " is not mapped:
```vim
let g:VM_maps = {}
let g:VM_maps['Goto Prev'] = '<C-t>'
let g:VM_maps['Goto Next'] = '<C-g>'
```

**Comment by enricozb** [comment]
Yep this is exactly what I wanted.

> just to save one keystroke

Yea I'm literally trying get 100% of sublime keybindings working on vim exactly as they do in sublime. Just to see what that's like.

Thanks!
