### ISSUE TITLE
[Feature Request] Ability to filter regions by visual lines

### ISSUE THREAD

**Issue by eyalk5** [mg979/vim-visual-multi#80]
Hi,

Say I have selected a word all over the document using VM. Or have some regions. 
Then I want to restrict the regions only to a certain part of the document.
I want to select lines (or chars) and only to include regions in this visual selection.  
Or I want to erase all regions in this visual selection. 

Can I do it now somehow that I have missed, or is it possible to arrange such an option? 

Thanks!

**Comment by mg979** [comment]
Try the tools menu \\\\`

then `filter lines with regions`, you can also change the buffer, and save to update the original buffer, I use this function from time to time but it's not well tested and I'll probably remove it and put it in some `optional commands` section.

**Comment by mg979** [comment]
> Or I want to erase all regions in this visual selection.

You can do this with `visual subtract` (default `\\s` in visual mode), operations from visual mode don't have an entry in the documentation yet, I have to add it.

**Comment by mg979** [comment]
> Or I want to erase all regions in this visual selection.

Now it should be possible, default mapping is `\\r` (Visual Reduce) in visual mode. It removes all regions that are outside of visual selection.

**Comment by eyalk5** [comment]
Cool! Thanks a lot. So far you have been the most responsive to my requests.
