### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by NicklasLallo** [mg979/vim-visual-multi#81]
Thanks for an amazing plugin! However, while reading the documentation I found a small error.

In the help documentation (visual-multi.txt) the section `g:VM_Leader` incorrectly use a capital L in Leader while the variable is actually called `g:VM_leader`. I had to check the source code to see why I couldn't change the leader key at first. The wikipage is however correct.

**Comment by mg979** [comment]
Thanks for spotting! I'm fixing it now.
