### ISSUE TITLE
Need more examples

### ISSUE THREAD

**Issue by D1mon** [mg979/vim-visual-multi#82]
The pictures show what is happening but it is not clear which keys were pressed. Add to the readme which keys you pressed. Add "Vim command sequence" how is it done in "vim-multiple-cursors"? And add more examples. Because it is a very complex plugin with very great features.

**Comment by mg979** [comment]
I won't expand the wiki, maybe reduce it. There's documentation in `help` format and a [tutorial](https://github.com/mg979/vim-visual-multi#tutorial) that teaches the basics. Creating good animated gifs is very time-consuming and it's not that useful when there's already documentation.

**Comment by D1mon** [comment]
Yes, I read. But apart from those examples, I cannot do anything else, because it is not clear.

**Comment by mg979** [comment]
I think I'll expand the tutorial and add examples for more commands. If there's something you'd like to be clearer, you can tell me so I can improve it in the tutorial, if it's something specific I can tell you now.

**Comment by D1mon** [comment]
The simplest: press Ctrl + V, j, j, j - select several lines. How do I add cursors to the end or beginning of each highlighted line. Maybe this is written in the documentation, but I read for a long time and maybe it didn’t go. So I'm sorry in advance.

**Comment by mg979** [comment]
`:help vm-visual-mode`, I will put it more in evidence. To create cursors from visual mode you press `\\c` (`\\` is the g:VM_leader).

**Comment by D1mon** [comment]
but can it be made to work when pressing shift + i (a)?

**Comment by mg979** [comment]
You want that when you are in visual line mode and press shift-i/a you go into multiple cursors mode? That's not possible because it would overwrite some basic vim mappings, but it can be scripted (by yourself), for example:
```vim
xmap I \\cI
xmap A \\cA
```
These things can be done with user mappings, there's no need to make options
and stuff.

Also, I prefer not to use VM when there are alternatives. I can recommend this plugin for this kind of things:

https://github.com/kana/vim-niceblock

Or just add this to the vimrc:
```vim
fun! s:niceblock(next_key)
  return s:setup_keyseq_table[a:next_key][mode()]
endfun

let s:setup_keyseq_table = {
\   'I': {'v': "\<C-v>I", 'V': "\<C-v>^o^I", "\<C-v>": 'I'},
\   'A': {'v': "\<C-v>A", 'V': "\<C-v>0o$A", "\<C-v>": 'A'},
\   'gI': {'v': "\<C-v>0I", 'V': "\<C-v>0o$I", "\<C-v>": '0I'},
\ }

xnoremap <expr> I   <sid>niceblock('I')
xnoremap <expr> gI  <sid>niceblock('gI')
xnoremap <expr> A   <sid>niceblock('A')
```

**Comment by D1mon** [comment]
Thanks
