### ISSUE TITLE
Insert mode remap

### ISSUE THREAD

**Issue by ipod825** [mg979/vim-visual-multi#83]
Is there a way to add customized insert mode mapping:
For example, I have this in my vimrc:
```vim
inoremap <c-h> <Left>                                                                                                                          
inoremap <c-l> <Right>
```
I would like to also map them in VM inserting mode.

**Comment by mg979** [comment]
You could use the VM_Start() and VM_Exit functions, see here:

https://github.com/mg979/vim-visual-multi/issues/61#issuecomment-497853266

**Comment by ipod825** [comment]
Thanks!
