### ISSUE TITLE
Not working for JSX/TSX filetype

### ISSUE THREAD

**Issue by sQVe** [mg979/vim-visual-multi#85]
Hey :wave:,

I use https://github.com/sheerun/vim-polyglot together with `vim-visual-multi` and I noted today that `vim-visual-multi` breaks when the filetype is either `javascriptreact`, `javascript.jsx`, `typescriptreact`, `typescript.tsx`. Here's an example:

```shell
echo "foo foo foo" > tmp.jsx
```

Open `tmp.jsx`, place cursor on first `foo` and press `<Control>n` 3 times (to mark all words). It does not work now to change all marked words with `c`.

**Comment by sQVe** [comment]
This issue is due to the plugin https://github.com/AndrewRadev/tagalong.vim. Uninstalling it solves the issue. Closing.

**Comment by mg979** [comment]
It's surely a mapping conflict. An easy fix is to unmap/remap using the start/exit functions

```vim
fun! VM_Start()
  " unmap the tagalong.vim mapping 
endfun

fun! VM_Exit()
  " restore the tagalong.vim mapping 
endfun
```

I'll add a compatibility fix by the way.
