### ISSUE TITLE
What does "VM has started with warnings. :VM_Debug for more info" mean?

### ISSUE THREAD

**Issue by themightyoarfish** [mg979/vim-visual-multi#88]
When editing C++ files, I as of today get the warning
```
VM has started with warnings. :VM_Debug for more info
```

But there is no `:VM_Debug` command to run. 
What do?

**Comment by mg979** [comment]
Sorry, the command is `:VMDebug`, it happens when some keys could not be mapped because they would overwrite some buffer mappings. Can you run `:VMDebug` and see what it says? Thanks
