### ISSUE TITLE
Auto complete seems to only change a single instance

### ISSUE THREAD

**Issue by sittim** [mg979/vim-visual-multi#91]
When I select multiple instances of a word, then use `c` to change, the [COC](https://github.com/neoclide/coc.nvim) autocomplete kicks in and changes just one instance at #6 on the image below.  I looked for shortcuts to see if there is a shortcut to apply the change to all of the instances but cannot find it.  Am I missing something?

![image](https://user-images.githubusercontent.com/8825037/68384708-32bf3c00-0126-11ea-8d11-d02a28745490.png)

**Comment by mg979** [comment]
I tried VM with coc.nvim and it's working for me (a basic setup).
What is the output of `:VMDebug` in that buffer? Can you post your configuration (VM and coc) and the coc extensions you are using? A reproducible case in a specific file? I can try to debug it if I can reproduce it.

**Comment by sittim** [comment]
Thank you for trying.  This issue goes away when I remove this line:

```vim
autocmd TextChanged,InsertLeave *.cpp,*.h,*.go,*.tpl silent! update
```
Any way to make it work with this saving when leaving the insert mode?

**Comment by sittim** [comment]
OK, this method seems to work:

```vim
autocmd TextChanged,TextChangedI *.cpp,*.h,*.go*.tpl silent write
```
I will be testing it over the next few days.

**Comment by mg979** [comment]
I suggest that you remove at least the autocommands that have to do with insert mode (`InsertLeave` and `TextChangedI`, especially the latter is called at every keystroke...), VM relies on autocommands to update the text and too many interferences can cause troubles. Is it necessary to update the file that often? `TextChanged` should be ok. If you can't leave without it you could enclose that `silent! update` in a function that checks if VM is active

```vim
autocmd TextChanged,InsertLeave *.cpp,*.h,*.go,*.tpl call s:update()

fun! s:update()
  if exists('b:VM_Selection') && !empty(b:VM_Selection)
    return
  endif
  silent! update
endfun
```

and maybe update on VM exit:
```vim
  autocmd User visual_multi_exit    silent! update
```

**Comment by mg979** [comment]
By the way, I could reproduce it without coc.nvim, the `update` in `InsertLeave` prevents the VM `InsertLeave` autocommand from being executed.

**Comment by mg979** [comment]
In the test branch this should be fixed (it works with `update` on `InsertLeave`). It may be a while before I push this to master because I'm not sure that the new system won't cause problems with other plugins.

**Comment by mg979** [comment]
I had to revert that commit. For now there's no solution, except the one I explained [here](https://github.com/mg979/vim-visual-multi/issues/91#issuecomment-551897809).

**Comment by sittim** [comment]
Your solution seems to work well for me, I really like this plugin, I used to use the vim-multiple-cursors, this plugin is much more stable.

**Comment by mg979** [comment]
Thanks, I'll add a troubleshooting section to the docs for this kind of issues.
