### ISSUE TITLE
Remap <C-n>

### ISSUE THREAD

**Issue by habamax** [mg979/vim-visual-multi#92]
Is there a way to remap `<C-n>`? It clashes with vim-yoink (kill-ring like plugin).

I wanted to make it `<leader>n` but can't find information on how to do it.

**Comment by mg979** [comment]
`:help visual-multi-mappings` or in the [quick start](https://github.com/mg979/vim-visual-multi/wiki/Quick-start#select-word-or-subword-under-cursor)?

**Comment by habamax** [comment]
Damn! How could I miss it?
Thx!
