### ISSUE TITLE
[Feature Request] Ability to remap hjkl movement keys in visual-multi mode

### ISSUE THREAD

**Issue by theniceboy** [mg979/vim-visual-multi#93]
Hi! I love the plugin, however, I'm a colemak user, and the default hjkl keys in the visual-multi mode is really annoying. Is there a way to remap that with this plugin?

**Comment by mg979** [comment]
Can you try this setting?

    let g:VM_custom_motions  = {'h': 'j', 'j': 'h'}

this means `remap h -> j, remap j -> h`, it's an example,  you should set the remappings you want.

**Comment by theniceboy** [comment]
Amazing! Thank you so much!

**Comment by Leandros** [comment]
This should be mentioned in `|vm-mappings|`, I believe.
