### ISSUE TITLE
[Feature request] motions that don't extend regions

### ISSUE THREAD

**Issue by eyalk5** [mg979/vim-visual-multi#94]
Hi,

Often in extend-mode, one wants to move fast to another place using the standard vim motions, in order to select another region. However, motions such as `w` cause vim to extend the region. 

It would be nice to have such an option(another mode?)  

Thanks.

**Comment by mg979** [comment]
There is a mapping for this, set to `\\<space>` by default, I remap it to `<space>`
```
let g:VM_maps = {}
let g:VM_maps["Toggle Mappings"] = '<Space>'
```
When you press it, all VM mappings are disabled, except that one and `<esc>`, so you press it again to restore mappings.

**Comment by eyalk5** [comment]
I glad to see it exists. I would call it otherwise. Instead of "toggle mappings", maybe "toggle: motion affects regions". This is clearer, I think.
