### ISSUE TITLE
hello, do you know what happened?

### ISSUE THREAD

**Issue by fgheng** [mg979/vim-visual-multi#98]
my config:
```
let g:VM_default_mappings = 0
let g:VM_maps = {}
let g:VM_maps['Find Under'] = '<c-d>' 
let g:VM_maps['Find Subword Under'] = '<c-d>'
let g:VM_maps['Select All'] = '<c-a>' 
let g:VM_maps["Add Cursor At Pos"]  = '<c-c>'
```
when i use ctrl-c to add a cursor at current pos, errors occured

VMDebugInfo:
```
b1: Overwritten imap: <CR> (I Return)  ->  <SID>AutoPairsOldCRWrapper73<SID>AutoPairsReturn      
b1: Overwritten imap: <BS> (I BS)  ->  <C-R>=AutoPairsDelete()<CR>
```

**Comment by mg979** [comment]
I don't get any error with that configuration. What does the error say? Or is it just this warning?

    VM has started with warnings. :VMDebug for more info

 In that case it's because autopairs causes mapping conflicts. I added an option to disable warnings if this is the case:

    let g:VM_show_warnings = 0

Also post vim version and OS, if this doesn't solve it, thanks.

**Comment by fgheng** [comment]
i am sorry, it can be selected today. I don't know what happened. i want to know how to change the color of selected region

**Comment by fgheng** [comment]
oh sorry, i found it, thank you very much
