### ISSUE TITLE
Remap Insert keys: i, I, a, A

### ISSUE THREAD

**Issue by theniceboy** [mg979/vim-visual-multi#99]
Hi! Can I remap insert keys such as `i`, I`, `a`, `A` to other keys?

For example, I have this `VM_custom_motion` setting:
```
let g:VM_custom_motions  = {'n': 'h', 'i': 'l', 'u': 'k', 'e': 'j', 'N': '0', 'I': '$', 'h': 'e'}
```
So what should I do if I want to be able to press `k` to enter insert mode in VM mode?

Thanks!

**Comment by mg979** [comment]
Those aren't motions, try

    let g:VM_maps['i'] = 'k'

**Comment by theniceboy** [comment]
Thank you! that did work. However, `c` operation does not go into insert mode with these settings:
```
let g:VM_maps = {}
let g:VM_custom_motions  = {'n': 'h', 'i': 'l', 'u': 'k', 'e': 'j', 'N': '0', 'I': '$', 'h': 'e'}
```
Any ideas? @mg979

**Comment by mg979** [comment]
`VM_custom_motions` only supports motions, not `I` or other stuff, you have to remove them from that variable or your mappings will be messed up.

**Comment by mg979** [comment]
Mm no I find out the issue, I'll fix it, right now `i` can't be remapped this way.

**Comment by mg979** [comment]
Can you try now?

**Comment by theniceboy** [comment]
Thank you! It works now.
